### ISSUE TITLE
TLS using go-kit

### ISSUE THREAD

**Issue by guru1306** [go-kit/kit#1012]
Hi All

I am trying to implement TLS for both HTTP and GRPC.  I am unable to find any resources to implement the TLS . Google grpc is providing a way to implement it.  Is there a way to implement using go-kit?

Thanks
Guru

**Comment by basvanbeek** [comment]
Go kit uses the standard gRPC & HTTP servers and clients so enabling TLS for Go kit services is no different. You can follow normal Go tutorials on enabling TLS for gRPC and HTTP. 

If you look add the `addsvc` example you will see the standard services (without TLS) being started. This is where you can inject the needed logic for TLS. e.g.:

Regular HTTP server:
https://github.com/go-kit/kit/blob/master/examples/addsvc/cmd/addsvc/addsvc.go#L195

Regular gRPC server:
https://github.com/go-kit/kit/blob/master/examples/addsvc/cmd/addsvc/addsvc.go#L211

**Comment by guru1306** [comment]
Thanks for your reply.

The issue is google's GRPC gives its own  [Server option implementation](https://pkg.go.dev/google.golang.org/grpc?tab=doc#ServerOption) . Google's grpc.creds function provides a way of getting the Serveroption for TLS implementation . But the goKit expects it's own gokit.ServerOption implementation. That leads to incompatible type.

**Comment by basvanbeek** [comment]
You're confusing the Go kit grpc Transport and the actual grpc Server. 

You probably need to alias the import file of either native grpc or the Go kit grpc server transport.

If you need more help I suggest going to gophers slack and ask for help in the Go kit channel. Issues are not the right place for asking for guidance.
