### ISSUE TITLE
unknown revision v2.1.2 for casbin

### ISSUE THREAD

**Issue by AydenHex** [go-kit/kit#1024]
Hello,

I try to  build my uService, and i have this error : 

```
go: github.com/go-kit/kit@v0.10.0 requires
        github.com/casbin/casbin/v2@v2.1.2: reading github.com/casbin/casbin/go.mod at revision v2.1.2: unknown revision v2.1.2
```

Anyone know how to fix that ?

Thanks ! :)

**Comment by ChrisHines** [comment]
There appears to be a properly tagged casbin v2.1.2 release, see https://github.com/casbin/casbin/blob/v2.1.2/go.mod and https://pkg.go.dev/github.com/casbin/casbin/v2@v2.1.2. Maybe you can trying building with `-v` or `-x` flags to see if more detailed logging from the build process can explain the problem.

**Comment by hsluoyz** [comment]
@AydenHex any update?

**Comment by sagikazarmark** [comment]
Casbin will be upgraded in the latest release to a new version.

The error sounds like a local cache problem, but even if something is wrong with that specific version, the upgrade should resolve it.
