### ISSUE TITLE
log.Caller results "unsupported value kind"

### ISSUE THREAD

**Issue by tgulacsi** [go-kit/kit#103]
With the logger `Log` of

```
    logger = log.NewContext(log.NewLogfmtLogger(os.Stderr)).
        With("ts", log.DefaultTimestampUTC,
        "caller", log.Caller(6))
    Log = levels.New(logger)
```

I get 
```ts=2015-08-20T08:17:12Z caller="unsupported value type" level=debug msg="reference date format in dataURL: 2006/1/2"
```

If I change the `log.Valuer` to `func() string`, then everything works.
I think maybe a fmt.Stringer would be enough (or anything what gopkg.in/logfmt.v0 accepts).

**Comment by ChrisHines** [comment]
@tgulacsi: @peterbourgon reported that problem to me in Slack a couple days ago. The problem was due to package `gopkg.in/stack.v1` not implementing `fmt.Stringer` on its types. I have added the required methods to that package, so `go get -u gopkg.in/stack.v1` should solve the problem.

**Comment by tgulacsi** [comment]
@ChrisHines thanks, that helped.
