### ISSUE TITLE
The canonical way to structure files and packages with go-kit

### ISSUE THREAD

**Issue by alebabai** [go-kit/kit#1042]
There are no real world examples of service structure using go kit (e.g. in terms of https://github.com/golang-standards/project-layout). 
There are only some kind of "hello world" for presentation/conference purposes.
All examples in this repo can be used only for demo/learning purposes, they can't be used as maintainable/scalable codebase.

Every article in medium/etc about golang project structure and go-kit reinvents the wheel and compose files and packages in some specific "new" maner based on another bunch of articles - it produces a mess.

Let's discuss and provide some standard way of structuring go microservice using go-kit.
So, based on it we can build a template repository or simple codegen tool.

My proposal is based on https://github.com/golang-standards/project-layout

- cmd/
  - <executable_name>/main.go
- ...
- pkg/
  - <domain_name>/
    - endpoint/
      - endpoint.go
      - request_response.go
    - transport/
      - http/
        - http.go
        - ...
      - grpc/
        - grpc.go
        - ...
    - middleware/
      - logging.go
      - ...
    - pb/
      - <domain_name>.pb.go
      - ...
    - <service_impl_1>/
      - ....
    - <service_impl_2>/
      - ....
    - <domain_name>.go
    - service.go

**Comment by peterbourgon** [comment]
There is not and will never be a canonical way to structure Go kit repositories. Neither Go repositories in general.

**Comment by alebabai** [comment]
> There is not and will never be a canonical way to structure Go kit repositories. Neither Go repositories in general.

Disagree. There is nothing so unique or special in the development of most microservices, they are all about the same for the most part. So why not offer a general recommended approach to repository and package structure?
In Golang we have "idiomatic" way of writing a code (official golang resources/articles and source code), so we should have at least a recommended one, as in most mature techologies of other languages.

**Comment by peterbourgon** [comment]
> There is nothing so unique or special in the development of most microservices, they are all about the same for the most part

Not usually, no. In Go, package and repo structure typically follows the domain, not the pattern. And what constitutes good structure can be totally different depending on project size, maturity, number of active maintainers, etc.

**Comment by alebabai** [comment]
> In Go, package and repo structure typically follows the domain, not the pattern

Golang not much different from other actual programming languages used for the same purposes (microservices stuff at this point) - all of the projects have some business logic, data layers, controllers, events, etc. And there is always a pattern, even in golang: structuring files as a mess in the root, using https://github.com/golang-standards/project-layout, etc. And why here we can't have it, it is a question for me - we can simply add example how to "properly" (the option that is already used in most production projects).
This situation is similar to the situation with redux in js world, where the authors also don't show the recommended way how to organize directories and files, but most projects that use redux use the same structure (from some article or somewhere) adapting it to its architectural approach.
So, if go-kit is about building microservices, architecture, guides - why it doesn't provide clear approach how to structure it - it is also open question for me.

**Comment by peterbourgon** [comment]
(shrug) I answered the question, as far as I can tell.
