### ISSUE TITLE
Construction of logging dynamically

### ISSUE THREAD

**Issue by suntong** [go-kit/kit#1046]
I want to construct my logging statement dynamically step by step, is that possible? 

E.g., instead of having everything at hand at once, like

	logger.Log("taskID", "2", "event", "task complete")

I need to build my logging step by step, first `"taskID", "2"`, then `"event", "task complete"`, etc. Eventually I'll construct a

	p := []interface{}{"taskID", "1.5", "event", "task complete"}

then call 

	logger.Log(p)

to log it. 

But I tried it, and it doesn't work that way. How can I make it works? thx.

**Comment by peterbourgon** [comment]
```go
logger.Log(p...)
```
