### ISSUE TITLE
go-kit dependency footprint

### ISSUE THREAD

**Issue by sylr** [go-kit/kit#1048]
Hi,

I got frustrated when I generated the dependency graph of a project of mine and saw that a big part of it was generated by `go-kit`.

The thing is, I don't even use `go-kit` directly, it's been included with all its dependencies because `github.com/prometheus/common` use `github.com/go-kit/kit/log`.

I did a little experiment and declared `github.com/go-kit/kit/log` as its own module, [see this patch](https://github.com/sylr/go-kit/commit/a5038ddf61bc300d0ebebde44304c350a7f1bd8d), and used it instead in `github.com/prometheus/common`, [see this other patch](https://github.com/sylr/prometheus-common/commit/c54569a8aa69a5d39a629e0e0dc4cf8b98954515).

The dependency graph of `github.com/prometheus/common` went from:

![image](https://user-images.githubusercontent.com/153052/103462629-d6a27880-4d26-11eb-8065-a4acc04c8d8d.png)

to

![image](https://user-images.githubusercontent.com/153052/103462640-e6ba5800-4d26-11eb-8c99-8f4dce9a85be.png)

I don't know what to think of this, even if I think it would be best I'm not expecting that all root go-kit's modules like `log` be declared as their own module.

Thoughts ?

**Comment by sylr** [comment]
`go-kit/log`'s footprint can be lowered even more by [breaking out log/zap & log/logrus](https://github.com/sylr/go-kit/commit/11d0b12e814fc7a5bd027bf78c42e6655f5c6f71). 

![image](https://user-images.githubusercontent.com/153052/103463775-4a488380-4d2f-11eb-91f4-f115fe6cd321.png)

**Comment by ChrisHines** [comment]
I don't think breaking out every package into its own module is a good idea. It would create significant friction for contributors to the project and probably a lot of confusion about the version management within the project as well.

When considering the dependency graph of a project, it is important to remember that simply following the `go.mod` require directives of each project is throwing too wide a net. In many cases only a subset of the packages within a required module are actually used. The Go compiler ignores unused packages at build time and their code is not included in your binary. I recommend only considering those packages and their transitive dependencies when drawing the dependency graph. It is a more accurate representation of how builds work.

**Comment by sylr** [comment]
@ChrisHines Thanks for your insights.
