### ISSUE TITLE
How does one log different level of verbosity with go-kit?

### ISSUE THREAD

**Issue by yonasstephen** [go-kit/kit#1056]
Understood from the examples like [addsvc](https://github.com/go-kit/kit/blob/master/examples/addsvc/pkg/addservice/middleware.go#L26-L31) that logging is done through a middleware / decorator pattern so that it's separated from the core business logic. It is indeed cleaner than inserting logging lines within the service itself. However, there is a trade off made here that is inability to log multi level of verbosity within the service. For example:
```go
func (s Service) RegisterUserAccount(u User, a Account) error {
  if !u.Valid() {
    return ErrUserInvalid
  }
  
  // async operation to update the cache
  go func() {
    cacheKey := fmt.Sprintf("%s_%s", u.Name, a.ID)
    res := s.CacheRepository.Update(cacheKey, a.Balance)
    // TODO: log.Debugw("cache update result:", res)
  }

  return s.DB.UpdateUserAccount(u, a)
}
```
In the example above, with a logging middleware it could only capture the DB error, but not the cache error. How does one normally work this out using go-kit?

**Comment by peterbourgon** [comment]
By using a pattern like https://github.com/peterbourgon/ctxdata.
Does that do what you need?

**Comment by yonasstephen** [comment]
@peterbourgon thanks for your reply. That's an interesting take and yes will solve the logging for synchronous flow. But it's a little bit tricky to solve asynchronous flow with `ctxdata` though, because the async code may have or have not finished setting the context data by the time the logging happens. So unless there is some kind of a wait in the logging middleware, the log output will be non-deterministic.

**Comment by peterbourgon** [comment]
What is an asynchronous flow?

Go kit supports synchronous (RPC) requests.

**Comment by yonasstephen** [comment]
I meant in the example above, updating the cache was done asynchronously with a goroutine. So if I were to use `ctxdata` it would look as follows
```go
go func() {
  res := s.CacheRepository.Update(cacheKey, a.Balance)
  ctxdata.From(ctx).Set("cache_result", res)
}
```

**Comment by peterbourgon** [comment]
This isn't valid — you can't give a context to a goroutine that outlives the goroutine that serves the request.

Hopefully this was enough of a pointer to get you going.

**Comment by yonasstephen** [comment]
Fair enough. I suppose the alternative for logging in an async flow is to decorate the CacheRepository with another logging middleware.
