### ISSUE TITLE
 Integer Overflow or Wraparound in go-kit dependency

### ISSUE THREAD

**Issue by kari-awake** [go-kit/kit#1057]
Nancy tool reports CWE-190: Integer Overflow or Wraparound in:

go.etcd.io/etcd v0.0.0-20191023171146-3cf2f69b5738

https://github.com/etcd-io/etcd/issues/12605
fixed in https://github.com/etcd-io/etcd/pull/12645

It's fixed in release-3.4 branch but it seems that there is no tag yet that has this fix..

**Comment by peterbourgon** [comment]
We're waiting for a new etcd release for some other reasons, too...

**Comment by kari-awake** [comment]
Any updates on this? Latest etcd 3.4.15...

**Comment by peterbourgon** [comment]
I spent 10 minutes trying to update Go kit's etcd version, and couldn't figure it out. The etcd repo doesn't appear to follow Go modules' conventions. Can someone give me a tip?

**Comment by peterbourgon** [comment]
Oops.

**Comment by kari-awake** [comment]
related? https://github.com/go-kit/kit/pull/1067

**Comment by sagikazarmark** [comment]
This is fixed on master, will be released soon.
