### ISSUE TITLE
gokit.io is down

### ISSUE THREAD

**Issue by mars** [go-kit/kit#1058]
The documentation site is returning Not Found:

<img width="1057" alt="Screen Shot 2021-02-18 at 09 51 50" src="https://user-images.githubusercontent.com/17164/108399408-ee4a9900-71ce-11eb-8f37-a49e6dae3342.png">

**Comment by peterbourgon** [comment]
Yep, I knew about it, but thanks for creating the issue. https://go-kit.github.io still works, so it's a problem with the custom domain. Working on it.

**Comment by peterbourgon** [comment]
I've tried everything I could think of with no luck. I'm waiting on GitHub support at this point. Sorry for the interruption.

**Comment by peterbourgon** [comment]
It's back now, thanks GitHub support! HTTPS coming soon.
