### ISSUE TITLE
Typo in auth/jwt package

### ISSUE THREAD

**Issue by amidam** [go-kit/kit#1071]
I have noticed a typo which was repeated a couple of times in `auth/jwt` package.
As JWT stands for JSON Web Token, so the Token after JWT is somehow redundant.
I was wondering if you are OK to revise all of the occurrences of `JWT Token` to `JWT`?
This change also includes the revision of `JWTTokenContextKey` to `JWTContextKey`.

**Comment by sagikazarmark** [comment]
Fixed in #1070
