### ISSUE TITLE
Casbin middleware

### ISSUE THREAD

**Issue by bernadd** [go-kit/kit#1073]
Hello, I am not sure if this is right place for question. I am considering to use this toolkit set in my upcoming project and I mostly understand all components/tools, except that casbin middleware for authorization. I notice it recieve model and policy set through context key/value, however I am not sure where are these set exactly and is this middleware used in transport layer.

**Comment by aryan828** [comment]
Hey @bernadd you can check [this](https://casbin.org/docs/en/get-started) to get started and how to use casbin. Casbin stores model in a .conf file and the policies can be either loaded into .csv file or from a database. Currently it supports 
- MySQL
- PostgreSQL
- Sqlite3
- SQL Server

There are other adapters made for casbin. You can check it out in the [repositories](https://github.com/casbin).

**Comment by ErikQQY** [comment]
Hello @bernadd, Casbin use the .conf file which contains **request**, **policy**, **policy_effect** and **matchers** to implement the authorization for subject, object and actions, you can define your .conf file according to your needs, reading [official docs](https://casbin.org/docs/en/overview) would be of great help. You are welcomed to open issues and ask questions in [Casbin community forum](https://forum.casbin.com/).
