### ISSUE TITLE
Can't join Slack Channel

### ISSUE THREAD

**Issue by JasonTruter** [go-kit/kit#1074]
Can't join the slack channel due to the link not being available. 

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/60793852/112798712-9aed2580-906d-11eb-85e4-deb8d17e0051.png">

**Comment by kallydev** [comment]
First join the `gophers` workspace, then search for the `go-kit` topic.

https://join.slack.com/t/gophers/shared_invite/zt-o2s1e0w3-uQ1wyrfVloMffstqOgKIZQ
