### ISSUE TITLE
old version of etcd-io/etcd

### ISSUE THREAD

**Issue by satr** [go-kit/kit#1075]
kit uses old version of `github.com/etcd-io/etcd`, which is reported by Snyk as having vulnerability
"Denial of Service (DoS)"
https://snyk.io/vuln/SNYK-GOLANG-GOETCDIOETCDV3ETCDMAIN-1083901
Snyk  reports issue in `github.com/prometheus-operator/prometheus-operator` because of this.
`Introduced through:   github.com/prometheus-operator/prometheus-operator@v0.44.0  ›  github.com/go-kit/kit@v0.10.0  ›  go.etcd.io/etcd@v0.0.0-20191023171146-3cf2f69b5738`

**Comment by peterbourgon** [comment]
#1057
