### ISSUE TITLE
add  GOFIBER (fiber) the  best performant web framework to kit

### ISSUE THREAD

**Issue by gitsupi** [go-kit/kit#1081]

**Comment by peterbourgon** [comment]
No.

**Comment by yzia2000** [comment]
Oh just curious, are there any issues fiber as to why it is not added here?

**Comment by peterbourgon** [comment]
Two main reasons. 

Fiber uses fasthttp, which doesn't implement HTTP/2 at all, provides an incomplete implementation of HTTP/1, and (IMO) has very low code and documentation quality. The fasthttp package is a niche optimization for specialized use cases, and inappropriate as a default choice.

Two, Fiber is a transliteration of a Javascript framework, and values a "Javascript-like" developer experience very highly. That preference seems to outweigh following Go language idioms and best practices. The most common examples that come to mind are misuse of [the empty interface](https://pkg.go.dev/github.com/gofiber/fiber/v2#App.Use) to simulate a dynamic type system, and misuse of [variadic params](https://pkg.go.dev/github.com/gofiber/fiber/v2#New) to express optional semantics. Fiber encourages bad habits.

**Comment by yzia2000** [comment]
Thanks for the comprehensive explanation!
