### ISSUE TITLE
How to redirect my request?

### ISSUE THREAD

**Issue by OhhhThatVarun** [go-kit/kit#1088]
So, I want to redirect my request to some other service. But the function ```redirect``` requires access to ```ResponseWriter and *Request```. I'm not getting where to put the redirect. Any help would be appreciated.

**Comment by peterbourgon** [comment]
Why? The answer will inform the best design.

**Comment by whiteboy19787bm** [comment]
I would like to try but I would need a tutor

**Comment by xescugc** [comment]
If you want to do it on a "encoder", what I normally use is

```
	w.Header().Set("Location", "/redirected-location")
	w.WriteHeader(http.StatusSeeOther)
```
