### ISSUE TITLE
Endpoint middleware use in documentation / examples

### ISSUE THREAD

**Issue by a-dot** [go-kit/kit#1103]
Hi,

I've been going through the various examples and I'd like to get some clarification regarding the use of Middlewares. In the first example, stringsvc, we can read: "Use endpoint middlewares for transport-domain concerns, like circuit breaking and rate limiting. Use service middlewares for business-domain concerns, like logging and instrumentation.". However when looking at the addsvc example, more specifically looking at pkg/addendpoint/middleware.go, the endpoint.Middleware is used to set up logging and instrumentation.

Which of the two examples should be used and considered the "right" way?

Thanks!

**Comment by peterbourgon** [comment]
There is no correct way.

With that said, the purpose of the endpoint middlewares in addsvc is to demonstrate how endpoint middlewares can work. As you can see, they don't have access to very much information, so it's probably not where you want to do any kind of detailed telemetry.
