### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by sagikazarmark** [go-kit/kit#1109]
Let's update the dependencies of this project to use latest versions.

I'd prefer finishing #1100 first, because it already changes dependencies considerably.

**Comment by ChrisHines** [comment]
#1105 includes a commit where I made a pass at that. Of note, I got some panics it the metrics/cloudwatch2 tests after upgrading. Also I believe there are breaking API changes in the newest versions of those dependencies someone should take a look at.

**Comment by sagikazarmark** [comment]
Thanks, I'll take a look at that.

We should consider upgrading to the v2 SDK for AWS. It's not a giant module anymore for every service.

**Comment by ChrisHines** [comment]
> We should consider upgrading to the v2 SDK for AWS. It's not a giant module anymore for every service.

Yeah, I noticed that, but didn't want to take on the effort of figuring out how to use the new API. I agree it is probably a good idea for someone to do, though.

**Comment by sagikazarmark** [comment]
I'm gonna take a look at it.

**Comment by sagikazarmark** [comment]
PRs sent. I left the "old" AWS SDK in place for now. I couldn't tell the difference between cloudwatch and cloudwatch2. If the only difference is the AWS SDK version, we could just deprecate the old one.

**Comment by sagikazarmark** [comment]
Dependencies are updated. We can run `go get -u` one more time before tagging the final release. I'm closing this issue for now.
