### ISSUE TITLE
Add a new log level debug1

### ISSUE THREAD

**Issue by VineethReddy02** [go-kit/kit#1114]
Currently `"github.com/go-kit/kit/log/level"` only supports  log levels `warn`, `error`, `info` & `debug`.

Support a new log level i.e. `debug1` that offers levels of logging for debugging purposes. It also helps to reduce the degug logs noise in `debug` and includes all the detailed debug info in `debug1`.

**Comment by ChrisHines** [comment]
Thanks, but we are not changing the levels supported in this package. There are many opinions about what a proper set of logging levels are. Go-kit provides one possible set of levels that we think are minimally useful, but we don't believe it is the only correct choice.

We intentionally decoupled the level package from the base log package to make it easy for anyone to choose a different set of levels that suits their needs. The `github.com/go-kit/kit/log/level` package demonstrates how anyone might implement log levels on top of the general `log.Logger` interface.
