### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by sagikazarmark** [go-kit/kit#1126]
A lot of issues are often about asking help or showcasing Go kit examples. GitHub released a new feature called Discussions a while ago which is more like a forum, better suited for this kind of topics. It allows keeping issues more focused on bugs and feature requests.

At can also act as a channel for announcements (eg. releases, major changes, etc).

WDYT?

**Comment by ChrisHines** [comment]
Do you know if there is a way to get notified about activity on the discussions?

**Comment by sagikazarmark** [comment]
I think you get emails the same way as about issues. In fact, I often find it annoying that I can't make a difference between issue and discussion emails.

**Comment by peterbourgon** [comment]
I like the idea of culling all of the question-tagged issues, and I like the _idea_ of Discussions. Has anyone used? Does it work in practice?

**Comment by sagikazarmark** [comment]
I use it in [Dex](https://github.com/dexidp/dex/discussions). People started to use it instead of opening issues which is _huge_. The situation will become even better with [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms): issue types can be formalized (bug reports, feature requests), everything else can go to discussions.

**Comment by ChrisHines** [comment]
I've read through some discussions on other people's repos. I don't have any objections, I'm just curious how it works from a maintainer's perspective. I don't expect any problems. Like @peterbourgon, I think the idea is good.

**Comment by peterbourgon** [comment]
Can you recommend a reasonably active Discussions I can poke around in?

**Comment by sagikazarmark** [comment]
From a notification perspective I see no difference between issues and discussions. In projects I maintain (Dex, Viper) I try to gear people towards discussions: a discussion can always be converted to an issue if needed (ie. it turns out to be a feature request).

As I mentioned, I think it allows keeping the issue tracker clean. For me personally, that's a huge relief: issues mean there is something to be done, but that's not necessarily the case with support requests: it's often just answering a question and closing the issue.

A community that uses Discussions actively is Twitter Bootstrap: https://github.com/twbs/bootstrap/discussions
I know that because they were one of the initial alpha testers.

**Comment by ChrisHines** [comment]
I've been reading through the discussions over on https://github.com/cue-lang/cue where they have been pushing people toward them for several months. They seem like a good thing and yes, the notifications work as I would want as well. So I'm 👍  on this idea.

**Comment by peterbourgon** [comment]
OK! Let's try it. I just flip the switch in settings? Anything I should be careful of?

**Comment by sagikazarmark** [comment]
Nothing special. I'd add an announcement category in addition to the existing, normal categories for announcement and release discussions.

When you flip the switch, GitHub offers to create a discussion in general: it's an initial message to the community. You can also pin that if you want.

Here is an example for a project I maintain: https://github.com/spf13/viper/discussions

**Comment by peterbourgon** [comment]
https://github.com/go-kit/kit/discussions
