### ISSUE TITLE
4 of 5 links on https://gokit.io/examples/ broken

### ISSUE THREAD

**Issue by httpdigest** [go-kit/kit#1130]
Hey,

I was just trying to learn about Go kit and found its website https://gokit.io/ and within it the site https://gokit.io/examples/ which links to a couple of examples.
However, most of them are broken right now. In fact, only the first one works and links to https://gokit.io/examples/stringsvc.html .

**Comment by sagikazarmark** [comment]
The source was updated, but apparently the travis CI automation doesn't work.

**Comment by peterbourgon** [comment]
Yep, it's busted at the moment. I'll fix it, or replace it, shortly. Apologies!!

**Comment by peterbourgon** [comment]
Gefixed.
