### ISSUE TITLE
Convert over to "official" rabbitmq library

### ISSUE THREAD

**Issue by SteelPhase** [go-kit/kit#1178]
### What would you like?

the RabbitMQ team has pulled in https://github.com/streadway/amqp into https://github.com/rabbitmq/amqp091-go

You can see the conversation [here](https://github.com/streadway/amqp/issues/497#issuecomment-791068860)

**Comment by sagikazarmark** [comment]
My gut tells me that it should probably be a new transport outside of the code repository, but I'm a bit hesitant to be honest: Go kit is going to face a large refactor once generics is released and I'm not sure starting to decompose the core repository before that is a good idea.
