### ISSUE TITLE
v0.12.0 

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#1186]
Shall I tag 251777ff as v0.12.0?

/cc @ChrisHines @sagikazarmark

**Comment by ChrisHines** [comment]
LGTM

**Comment by sagikazarmark** [comment]
LGTM

**Comment by peterbourgon** [comment]
https://github.com/go-kit/kit/releases/tag/v0.12.0

Please publicize as you see fit, I'm unable to do so at the moment.
