### ISSUE TITLE
Kafka transport implementation

### ISSUE THREAD

**Issue by alebabai** [go-kit/kit#1209]
### What would you like?

Hi,

I've implemented module with Apache Kafka transport abstractions for use with go-kit.
It follows common go-kit code style, has documentation and examples (separate modules).

If you find this interesting and useful, it would be great if you could leave a link to it somewhere.

For community: any help, advice, contribution is appreciated.

Thanks.

https://github.com/alebabai/go-kit-kafka

**Comment by sagikazarmark** [comment]
I don't think there is a section in the readme for third-party transport implementations, so your may be the first one. I'd say feel free to open a PR and add it somewhere in the readme (maybe below or above the code generator section).

@peterbourgon do you have any preference?

**Comment by Reasno** [comment]
@alebabai while I appreciate the effort in making this cleanly written and well-documented repo, I think it treats Kafka as a pub/sub, instead of an RPC transport. All other modules in go-kit focus on Request-Response pattern only, including AMQP.

**Comment by alebabai** [comment]
@Reasno Hi, thanks for feedback.
AMPQ and Nats here are implemented as a pub/sub with RPC concepts (endpoints, request/response), my transport is inspired by them and implemented same way using same principles.

**Comment by peterbourgon** [comment]
We're not merging new transports, but I'm happy to add a section to the README for this. I think there are probably several more that warrant inclusion. Please open a new PR!
