### ISSUE TITLE
Empty error response

### ISSUE THREAD

**Issue by gunjan5** [go-kit/kit#121]
In [stringsvc1](https://github.com/go-kit/kit/blob/master/examples/stringsvc1/main.go#L100) example, when you send a normal string to /uppercase you get {"v":"HELLO",**"err":null**}, but when you send an empty string "", you won't see the error in response {"v":"",**"err":{}**}.

If this is an expected behavior then what is the recommended way to get the **ErrEmpty** as part of the response? 

Would be useful if that is explained in the example documentation.

Thanks!
Gunjan

**Comment by peterbourgon** [comment]
Yes, this is an oversight. Fix incoming...

**Comment by peterbourgon** [comment]
Argh, bad push. Hold on...

**Comment by peterbourgon** [comment]
OK, fixed in master.
