### ISSUE TITLE
publisher/factory workflow should provide mechanism for cleanup of persistent resources

### ISSUE THREAD

**Issue by EcofitBrendan** [go-kit/kit#122]
When using the publisher/factory/load balancer workflow, there is no mechanism currently provided for a publisher to trigger the cleanup of an endpoint which is no longer provided.

**Comment by peterbourgon** [comment]
Thanks for filing the issue. Per the discussion in Slack, we have some ideas, most promising of which is probably to model it like the database/sql connection pool.

If there are any more concrete ideas, I'm happy to hear them. I'll find some time to sketch some prototype implementations this week.

**Comment by peterbourgon** [comment]
I'm thinking of two different ways to do this...

1. In the factory, couple each manufactured endpoint with the physical resource used to implement it. Track the tuple in each publisher, and when it falls out of scope, invoke some kind of close method. This is the smallest patch, but perhaps a bit awkward.
2. Redefine endpoint as a single-method interface. When it falls out of scope, try to upgrade it to a closer, and if successful, invoke close. Factories produce a closable or non-closable endpoint as appropriate. This is a (much) bigger patch, but perhaps an endpoint interface makes a lot more sense...

**Comment by EcofitBrendan** [comment]
I think point 1 has some merit to it. This could be achieved by altering the factory interface to:

```
type Factory func(instance string) (endpoint.Endpoint, io.Closer, error)
```

This creates a more complicated return type, but would allow the publisher to then take on responsibility for when a given endpoint is no longer in scope. This would require all factories which do not use closable resources to return a NopCloser of some kind as well.

2 would open the possibility of this being used outside of publisher/factory loop, which could be useful or dangerous depending on the application.
