### ISSUE TITLE
Services will panic when logging

### ISSUE THREAD

**Issue by bketelsen** [go-kit/kit#123]
If you don't explicitly create and pass in a Logger when creating a service, the service will panic when it tries to log an error.

Fixes:
1) fail to create new service without logger
2) default a logger if none created
3) Profit?

**Comment by ChrisHines** [comment]
Another option: Skip logging if the Logger is `nil`.

**Comment by bketelsen** [comment]
Principle of least surprise is to create a default logger to stdout

**Comment by ChrisHines** [comment]
Yes, but in the code you pointed out on Slack, https://github.com/go-kit/kit/blob/master/examples/stringsvc3/main.go#L57, there is no constructor function to do the check and create a default logger.

**Comment by bketelsen** [comment]
True, but it could be a simple check at the beginning of ServeHttp
https://github.com/go-kit/kit/blob/master/transport/http/server.go#L46

**Comment by ChrisHines** [comment]
I believe that would be racy without a mutex.

**Comment by bketelsen** [comment]
it would, true.

**Comment by ChrisHines** [comment]
Another option is to declare `httptransport.Server.Logger` as a [`log.SwapLogger`](http://godoc.org/github.com/go-kit/kit/log#SwapLogger). But most likely we should define `httptransport.NewServer` as a proper constructor.

**Comment by peterbourgon** [comment]
My bad. Will fix by using a constructor + functional options.
