### ISSUE TITLE
Upgrade to prometheus/client_golang 1.12.2

### ISSUE THREAD

**Issue by rootulp** [go-kit/kit#1243]
### What would you like?

https://github.com/go-kit/kit/blob/50c38262a8c71be2532f45100e622025bc5ffedf/go.mod#L23

I'd like to leverage new features in prometheus/client_golang [1.12.2](https://github.com/prometheus/client_golang/releases/tag/v1.12.2). Are there any objections to upgrading this dependency?

**Comment by ChrisHines** [comment]
How do you want to leverage the new features? Do you want to use them in Go kit code or your own code?

**Comment by rootulp** [comment]
In a consuming application ([celestiaorg/celestia-core](https://github.com/celestiaorg/celestia-core)) I wanted to use `counter.Inc()` which I thought was only available in 1.12.2 ([here](https://github.com/prometheus/client_golang/blob/v1.12.2/prometheus/counter.go#L40)) but it also appears available in 1.11.1 ([here](https://github.com/prometheus/client_golang/blob/v1.11.1/prometheus/counter.go#L40)). So I investigated this codebase a little more and learned that my feature request would imply adding `Inc()` to 
https://github.com/go-kit/kit/blob/50c38262a8c71be2532f45100e622025bc5ffedf/metrics/metrics.go#L5-L8

and this method may not be applicable to counters for other packages in https://github.com/go-kit/kit/tree/50c38262a8c71be2532f45100e622025bc5ffedf/metrics

Do you have thoughts here? It's likely that this issue can be closed as not planned

**Comment by peterbourgon** [comment]
Feel free to add a PR that adds Inc to Counter, but it's not obvious to me that 

```go
c.Inc()  // is better than
c.Add(1) // in any meaningful sense
```

**Comment by peterbourgon** [comment]
Said another way,

> I'd like to leverage new features in prometheus/client_golang [1.12.2](https://github.com/prometheus/client_golang/releases/tag/v1.12.2). Are there any objections to upgrading this dependency?

You don't need to upgrade the dependency to use the new features. So I guess I'll close this for now.
