### ISSUE TITLE
Log Caller does not work with json logging

### ISSUE THREAD

**Issue by kris-runzer** [go-kit/kit#130]
I've noticed that using NewJSONLogger that caller is always an emtpy {} when logging:
​
logger = log.NewJSONLogger(os.Stderr)
logger = log.NewContext(logger).With("caller", log.DefaultCaller)
​logger.Log()
​
Results in the following log output:
​
{"caller":{}}

**Comment by ChrisHines** [comment]
Thanks for the issue report.

**Comment by ChrisHines** [comment]
I have added a test case for this issue: https://github.com/go-kit/kit/commit/c158bb5fdfa4a8cbf7927b08a6961821e5d2d11a.

The fix is implemented in the upstream package gopkg.in/stack.v1: https://github.com/go-stack/stack/commit/03cd31e5ea99ead703a7df9b8971e2defc718d39.

To get the fix, run:
```
go get -u gopkg.in/stack.v1
go get -u github.com/go-kit/kit
```
