### ISSUE TITLE
transport/http: Cannot do type-checking of error in customer errorEncoder

### ISSUE THREAD

**Issue by smreed** [go-kit/kit#133]
If an error is returned from a `requestDecoder` passed to `http.NewServer`, it is wrapped by the unexported `badRequestError` type before it is passed to the `errorEncoder`.

Unfortunately, this means the type of the original error, thrown by the `requestDecoder`, is lost.

If using a customer `errorEncoder`, you will not be able to switch on the error type to determine if it's one of your own errors, you must look at the error text itself.

**Comment by peterbourgon** [comment]
Thanks for the report. We use the custom badRequestError type as a means to provide a different status code. It seems like this can be solved by exporting the badRequestError, and allowing the custom error encoder to type-switch on the error, just like the [defaultErrorEncoder](https://github.com/go-kit/kit/blob/144a8c62fa80f4c76e40c55f965c21ba153ebdb0/transport/http/server.go#L112) does. Do you agree?

**Comment by smreed** [comment]
That would help in most cases. However, If I want to return a specific
error from my own request decoder, I won't be able to detect it later on,
as it will have been wrapped.

**Comment by peterbourgon** [comment]
@smreed You can detect it like this, I think? → https://play.golang.org/p/Ddez4B_YPA

**Comment by smreed** [comment]
Yeah, you're totally right. That'll work, thanks. We just need the badRequestError exported as you suggested.
