### ISSUE TITLE
BadRequestError does not reveal the embedded error to ErrorEncoder

### ISSUE THREAD

**Issue by yookoala** [go-kit/kit#144]
`BadRequestError` has `error` as embedded type. Since `error` starts with small cap, it is an implicit unexported field of `BadRequestError`. That means only code within `transport/http` package can access the raw error value. This leave no room for `ErrorEncoder` implementation to unpack error messages of custom error types.

Suggest either to:
1. To add a `BadRequestError.Raw{}` method that returns the raw error inside.
2. Change `BadRequestError` from `type struct{error}` to `type struct{ Raw: error }`.

**Comment by peterbourgon** [comment]
Thanks. With the fixes I mentioned in #146 I'm happy to merge.
