### ISSUE TITLE
EndpointCache returns sorted Endpoints

### ISSUE THREAD

**Issue by jerome-laforge** [go-kit/kit#159]
Hello,
I would be great that `loadbalancer.EndpointCache` will return the list of sorted Endpoints(alphanumeric).
My underlying usage is that I want to try as much as possible to redirect the same type of request (the type can be calculated with hash of specific attribute of request or something else) on the same endpoint with my own loadbalancer. 
By the way, I think with defined order will allow that the `loadbalancer.RoundRobin` to  be more consistency as it returns Endpoint sequentially.

If you think this feature can be accepted, I can create PR.

Many thx

**Comment by cihangir** [comment]
hi @jerome-laforge 
In the course of unifying loadbalancer implementations, i've removed EndpointCache and made `Static` , parent to all [LoadBalancers](https://github.com/cihangir/kit/commit/9a1b71fabfb283f88d94f47f77409f202a971f65#diff-82c756797b9906d268074fe4b52a842aR19) and `Static` maintains the given order. You can [see here](https://github.com/cihangir/kit/commit/9a1b71fabfb283f88d94f47f77409f202a971f65#diff-974f103d2b8d8ca09525b35b124fd8aaR108)  I was waiting for @peterbourgon 's thoughts before cleaning up the code and opening a PR. related [conversation](https://github.com/go-kit/kit/pull/143#issuecomment-152326664)

**Comment by jerome-laforge** [comment]
hi @cihangir 
Thx for this.
By the way, you could use atomic.Value on `func (p *Publisher) Endpoints() ([]endpoint.Endpoint, error)` and don't use rwlock.
See this gist, where I just use atomic.Value with bench:
https://gist.github.com/jerome-laforge/b60d75fba7f78c8a4a94

And the bench result

RWLock:
```text
BenchmarkEndpointCache-4        10000000               175 ns/op              16 B/op          1 allocs/op
BenchmarkEndpointReplaceCache-4  3000000               526 ns/op             160 B/op          2 allocs/op
```

atomic.Value
```text
BenchmarkEndpointCache-4        50000000                26.9 ns/op             0 B/op          0 allocs/op
BenchmarkEndpointReplaceCache-4  2000000               661 ns/op             208 B/op          4 allocs/op
```
