### ISSUE TITLE
Oversight with new level logger?

### ISSUE THREAD

**Issue by kris-runzer** [go-kit/kit#162]
With the recent changes made to levels.Logger the keyvals have been left behind... for example:

```
func (l Levels) Debug(keyvals ...interface{}) log.Logger {
	return l.ctx.WithPrefix(l.levelKey, l.debugValue)
}
```

To get the previous effect we need to now do:

`transportLogger := log.NewContext(lvlLogger.Error()).With("component", "transport")`

I was going to create a pull request with the following:

```
func (l Levels) Debug(keyvals ...interface{}) log.Logger {
	return l.ctx.WithPrefix(l.levelKey, l.debugValue).With(keyvals...)
}

```

this would allow the following:

`transportLogger := lvlLogger.Error("component", "transport")`

**Comment by kris-runzer** [comment]
Another solution would be instead of returning `log.Logger` to return `log.Context` instead and remove those keyvals entirely.

**Comment by kris-runzer** [comment]
Please see the following PR: https://github.com/go-kit/kit/pull/163

**Comment by ChrisHines** [comment]
Wow! You are right. I don't know how I missed that, but that is certainly something we need to fix. I will take a look at the PR and we'll go from there.

Thanks for the issue report.

**Comment by ChrisHines** [comment]
OK, reviewing my thought process here. I was intending to remove the keyvals all together, and at the call site they would be passed to the `Log` method instead of (for example) the `Debug` method.

So when an application used to call:
```go
lvlLogger.Debug("k", "v")
```
It would now call:
```go
lvlLogger.Debug().Log("k", "v")
```
The code that was pushed does work this way, but unfortunately left behind the dormant `keyvals` parameters.

**Comment by kris-runzer** [comment]
The only benefit of leaving the keyvals as per my PR are it allowed me to pass a level.Levels around and instantiate new loggers off of that.

```
logger := levels.New(...)

doSomething(logger)

func doSomething(logger levels.Levels) {
	errLogger := logger.Error("context", "doSomething")

	if err := boom(); err != nil {
		errLogger.Log("err", err)
	}
}
```

If this keyvals is removed I need to use `log.NewContext(...)` everywhere so I can have access to the `With(...)` or `WithPrefix(...)`.  Or I could just cast it use `.(log.Context)`

Is there an intended usage of this that I'm failing to see?

**Comment by ChrisHines** [comment]
@kris-runzer I think you are missing the fact that `level.Levels` has a `With` method that eliminates the need to call `log.NewContext`

I think without the keyvals on the `Error` method your example would be written as:
```go
logger := levels.New(...)

doSomething(logger)

func doSomething(logger levels.Levels) {
    errLogger := logger.With("context", "doSomething").Error()

    if err := boom(); err != nil {
        errLogger.Log("err", err)
    }
}
```
Please correct me if I have misunderstood your use case.

**Comment by kris-runzer** [comment]
@ChrisHines Ok I see you point; I was indeed missing the fact that `level.Levels` had a `.With(...)`.  I was actually using this in another portion of code.  Doh!  Thanks for the clarification on that.  That being said; I see now that `keyvals` should just be removed :)

**Comment by ChrisHines** [comment]
@kris-runzer OK. I'm glad it was that simple. I will take care of removing the unused `keyvals` parameters.
