### ISSUE TITLE
question: Is it sensible to look at incorporating MQ also ?

### ISSUE THREAD

**Issue by joeblew99** [go-kit/kit#166]
I am expecting to be blasted for suggest this, and its really more of a roadmap question.

This is a MQ, with no broker. It support all the standard patterns, has zero external dependencies and is well tested.  It also supports many transports.
https://github.com/gdamore/mangos

I have used it for a few projects, but i also like what kit offers. So, i am wondering about options to incorporate the two together for example.

**Comment by peterbourgon** [comment]
I think this has been asked before. I'm happy to take a PR that adds a transport/mangos package, i.e. I'm happy for Go kit to support mangos as a transport. I'd also be curious to hear where this is being used — I've not ever seen it in the wild.

**Comment by peterbourgon** [comment]
I think that answers the question! :)
