### ISSUE TITLE
Support response stream from transport/http.Client

### ISSUE THREAD

**Issue by rolaveric** [go-kit/kit#170]
The `endpoint.Endpoint` produced by `transport/http.Client.Endpoint()` has a defer that closes the HTTP response body.
https://github.com/go-kit/kit/blob/master/transport/http/client.go#L79
Normally this is fine, especially when dealing with succinct messages encoded as JSON.

However, I have a use case where some (but not all) endpoints on a service are returning binary data (PDFs, to be specific).
I don't want to buffer the whole byte stream if I don't need to (eg. If I'm just going to pipe it to another output stream), which means I need to call response.Body.Close() myself after the endpoint has returned.

I've got a solution that involves adding a `stream bool` flag to the `Client` struct, changing the `Endpoint` method to wrap the defer call in a `if !c.stream { }` block, and then creating an Option function which sets `c.stream = true`.
That keeps everything backwards compatible while enabling streaming when required.

```go
// transport/http/client.go

type Client struct {
  // ...
  stream bool
}

// StreamClient prevents resp.Body.Close() from being called by the endpoint
func StreamClient() ClientOption {
	return func(c *Client) { c.stream = true }
}

func (c Client) Endpoint() endpoint.Endpoint {
  // ...
  if !c.stream {
    defer func() { _ = resp.Body.Close() }()
  }
 // ...
```

If that sounds reasonable, I'll write up a test and submit a PR.

**Comment by wangtuanjie** [comment]
+1

**Comment by peterbourgon** [comment]
Interesting. Endpoint is strictly RPC, so I assume the stream is always finite?

**Comment by rolaveric** [comment]
Yes, we'd be talking about a single finite byte stream, like a file.  Not like a stream of messages over time.
'Buffered stream' might be a better way to word it.

**Comment by peterbourgon** [comment]
Then this sounds great to me.

**Comment by anxiousmodernman** [comment]
+1 for this. I have a use case that is very similar for uploading/downloading files. I would like to reap the benefits of the `Endpoint` abstraction for these http calls near the "edge" of our system.
