### ISSUE TITLE
URL-pattern support

### ISSUE THREAD

**Issue by tspecht** [go-kit/kit#179]
Hi guys,

I was just wondering if support for regex-based URLs is planned in a way similar to gorilla/mux (http://www.gorillatoolkit.org/pkg/mux) ? I'm needing this because I want to put the resource ID I'm planning on operating on inside the URL.

**Comment by dobegor** [comment]
+1 to this, I was just about to create an issue about that.
Would be awesome.

**Comment by peterbourgon** [comment]
I've just [pushed a branch and PR](https://github.com/go-kit/kit/pull/180) with an example service that uses gorilla/muc for REST-y request routing. Take a look and please give me feedback!

**Comment by dobegor** [comment]
@peterbourgon 
That's exactly what I need!
This is really a painkiller for me, excellent work.

As the feedback, it would be nice if you can edit this example so that it would have exactly the same structure as strinvsvc{1,2,3} examples (separating encoding/decoding stuff, main file, proxy stuff and etc), but it isn't important, example is very good.
Thanks a lot!

**Comment by dobegor** [comment]
@peterbourgon
Well, to be honest, I don't really understand why the Context is passed to service bussiness logic in this example.

**Comment by peterbourgon** [comment]
> Well, to be honest, I don't really understand why the Context is passed to service bussiness logic in this example.

In the example, it's not used. But almost any microservice is going to eventually need some way to pass information across context boundaries, and to use that information in the business logic domain. For example, transaction IDs or authorization tokens. The context is the correct way to do that, and so I think it makes sense to wire it in from the beginning.

**Comment by peterbourgon** [comment]
>  it would be nice if you can edit this example so that it would have exactly the same structure as strinvsvc{1,2,3} examples

Sure! I'll try it out and see if it makes it easier to understand. Thanks for the feedback.

**Comment by tspecht** [comment]
Peter, this is exactly was I was looking for! Thanks a lot :) I'm still trying to get a decent-ish test suite up and running for my new project (since I'm completely new to Go ..) but once I'm done with that I'll incorporate the mechanism from your PR - looks really promising as far as I can tell!
Thanks for putting it together so quickly :)

**Comment by dobegor** [comment]
@peterbourgon 
The behaviour of /profiles/{id} PATCH & PUT requests doesn't have any sense, it returns errAlreadyExists always, but that's a bussiness logic's problem :laughing:

**Comment by peterbourgon** [comment]
@dobegor Thank you, you're right! I've updated the PR. See additional explanation [here](https://github.com/go-kit/kit/commit/258590126b0e4b4e684f4636e3707ddbafce7b8e#diff-64da03fd9db084e1c377bc95ad96dfa8R98).

**Comment by dobegor** [comment]
@peterbourgon LGTM, thanks.
I wish there was an example for pure proxy application with something like etcd for services discovery, but it's more advanced theme.

**Comment by peterbourgon** [comment]
@dobegor Sounds like an API proxy?

**Comment by dobegor** [comment]
@peterbourgon yes, like one in stringsvc3, but separated from logic, with load balancing. I wonder how to use etcd for discovery with go-kit and it would be a useful example for everyone.

**Comment by peterbourgon** [comment]
I've merged the PR. Thanks for the question. Hope the new example is helpful.
