### ISSUE TITLE
Why mutex in publisher's Endpoints() ?

### ISSUE THREAD

**Issue by dobegor** [go-kit/kit#181]
https://github.com/go-kit/kit/blob/master/loadbalancer/fixed/publisher.go#L24
Why it's there?
Endpoints() method is called only for reading the endpoints list, I can't figure out why there's a mutex.
That means all goroutines serving http requests on proxy will wait for this mutex while being "proxied".

This doesn't really affect the performance, but why?

**Comment by peterbourgon** [comment]
It's a read lock, and it's necessary to prevent the slice itself from being modified when it's being read by an Endpoints() caller.
