### ISSUE TITLE
Package transport/httprp

### ISSUE THREAD

**Issue by karmeye** [go-kit/kit#186]
Say you have a bunch of services. Only one or a few are open to the public, lets call these Frontends. The Frontends may utilize serveral Backend services that are not open to the public.

User <-> | Internet | <-> Frontend <-> Backend

There is business logic in the Frontends for some Endpoints.
But there are also Endpoints in the Frontends that do not have business logic: they only forward the requests from the user to Backend services.

In the latter case, the interface specification for both Endpoints in Frontend and Backend are identical (as specified by the business logic). For these Endpoints, the Frontends could act a "dumb" reverse proxy and forward all requests to the corresponding Backend Endpoints, without applying any logic. This would avoid any unnecessary encoding/decoding at the Frontend, which — for large Backend responses — benefit performance and save resources.

There is the stdlib httputil.ReverseProxy that can do the proxying. But there is no easy way to use it with Gokit.

What about a separate transport for this proxying logic, that takes advantage of the  httputil.ReverseProxy to do the proxying. 

With this in place, the Frontends could proxy the requests for their subset of Endpoints where business logic is defined by Backend services, and at the same time, utilize Gokit tools such as load balancers, rate limiters and circuit breakers.

**Comment by peterbourgon** [comment]
Solved with #214. Thanks for raising the issue! Let me or @skidder know if you have any problems or questions with that new transport.
