### ISSUE TITLE
Writing clients for services that using gorilla mux

### ISSUE THREAD

**Issue by dobegor** [go-kit/kit#188]
Is there any way to create a client with go-kit for service which uses Gorilla's mux with paths like
/users/{id} for queries?

I.e. [profile service](https://github.com/go-kit/kit/tree/master/examples/profilesvc).
I was looking for client example [here](https://github.com/go-kit/kit/blob/master/examples/addsvc/client/httpjson/client.go#L18), but it doesn't have a possibility to do such thing, neither to apply a custom http client (it uses only http.DefaultClient), see #187.

**Comment by dobegor** [comment]
For example, I've made a workaround that works for me:
``` go
func EncodeGetUserRequest(r *stdhttp.Request, request interface{}) error {
	id := request.(endpoints.GetUserRequest).ID
	r.URL.Path += id //this attaches id to form a URL like /users/{id}
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(request); err != nil {
		return err
	}
	r.Body = ioutil.NopCloser(&buf)
	return nil
}
```
But I don't think it's the right way to do this in production. If there really no plans to add some exstension to existing http client to do this job in more "go-kit way", close this issue, as this will require creating another "muxed" http client.

**Comment by peterbourgon** [comment]
Please see https://github.com/go-kit/kit/tree/master/examples/profilesvc. Does that answer your question?

**Comment by peterbourgon** [comment]
I am reworking all of the examples in #235 and will include a client package for profilesvc.

**Comment by peterbourgon** [comment]
profilesvc now has [a client](https://github.com/go-kit/kit/blob/master/examples/profilesvc/client/client.go). [Here is the interesting bit](https://github.com/go-kit/kit/blob/dee283944e96f171d2951fa67fab7c686a92c904/examples/profilesvc/endpoints.go#L56-L86) of client-side construction logic. Hope it helps!

**Comment by dobegor** [comment]
Thanks, that's really helpful.
