### ISSUE TITLE
Data races detected in tests

### ISSUE THREAD

**Issue by taion809** [go-kit/kit#193]
Hello,
From a previous pull request some data races were surfaced [link](https://api.travis-ci.org/jobs/109158701/log.txt?deansi=true):

Races were detected in the following tests:

  - `TestRefreshNoChange`
  - `TestBadFactory`
  - `TestServiceUpdate`
  - `TestCounter`
  - `TestGauge`
  - `TestCallbackGauge`
  - `TestHistogram`

**Comment by peterbourgon** [comment]
Thanks. I knew about many of these and just wasn't concerned with fixing them. I'm still not sure that they're worth fixing. Let me dig a little deeper.

**Comment by basvanbeek** [comment]
The race conditions found in TestBadFactory & TestServiceUpdate all originated from the mocked Zookeeper Client not the actual implementation. It has been fixed in pull request #195.

**Comment by peterbourgon** [comment]
These should be fixed now.
