### ISSUE TITLE
Zipkin IsSampled header

### ISSUE THREAD

**Issue by taion809** [go-kit/kit#230]
Hello!
As mentioned in the slack channel I am interested in getting the `X-B3-IsSampled` header implemented.  (chat log below for context).

The `X-B3-IsSampled` header signals to downstream services that they should sample this request and send it to zipkin [ref](https://twitter.github.io/zipkin/Instrumenting.html#communicating-trace-information).

The first issue I have is where does this code live?  Sampling is done on the collector itself and as soon as spans are checked the request has already been sent making it not possible to set the header prior to sending downstream.

chat log:
> 
Nicholas Johns [09:20] 
@bas: hi, i see you’ve been working on the zipkin package recently.  Are you planning on implementing `X-B3-Sampled` for sampling?  if not I will have some time to work on that in a week or two
> 
Peter Bourgon [09:24] 
@nicholas: sampling is already supported, I wasn't aware it required a header?
> 
Bas van Beek [09:27] 
I have not looked at that either so had no plans yet
> 
Nicholas Johns [09:28] 
sampling doesn’t but in order to flag downstream services there is a header you can pass
> 
Bas van Beek [09:28] 
We should honor this
> 
[09:29] 
makes total sense to at least have a fully annotated span if the originating service creates the root span and microservices are sampling
> 
Peter Bourgon [09:29] 
@nicholas: ah, I see

**Comment by basvanbeek** [comment]
To add this we need to do a little rework on when sampling occurs. Currently this happens on the collector but as @taion809 already mentioned collection happens after the trace has been sent downstream.

Most obvious place to set the sample flag would then be at the root span when the actual traceId is created. Each downstream service would identify if it needs to trace the upstream span based on the flag and would send the flag value with its following client calls.

Also good to note is that sampling currently presents an issue which is described here: https://github.com/openzipkin/zipkin/issues/446

**Comment by peterbourgon** [comment]
@basvanbeek I think this can be closed now?

**Comment by basvanbeek** [comment]
That is correct. The IsSampled header and logic of bypassing the local sampler in case an upstream Span has been sampled has been implemented.

**Comment by peterbourgon** [comment]
:tada:
