### ISSUE TITLE
Make the Errors returned by Client.Endpoint in transport/http.

### ISSUE THREAD

**Issue by Ayiga** [go-kit/kit#231]
It would be incredibly beneficial, if an error returned from the Client.Endpoint call would return an error that would give you access to the original Error.

Something that would take the following code:

```go
if err = c.enc(req, request); err != nil {
	return nil, fmt.Errorf("Encode: %v", err)
}
```

and would return an Error with the original error reference intact, something like this:

```go
if err = c.enc(req, request); err != nil {
	return nil, Err{"Encode", err}
}
```

supposing that the structure for `Err` looking like:

```go
// Err represents an Error occurred in the Client transport level.
type Err struct {
	// Domain represents the domain of the error encountered.
	// Simply, this refers to the phase in which the error was
	// generated
	Domain string

	// Err references the underlying error that caused this error
	// overall.
	Err error
}

// Error implements the error interface
func (e Err) Error() string {
	return fmt.Sprintf("%s: %v", e.Domain, e.Err)
}
```

This would allow for the original Error to be referable, and would add a layer of indication to inform the overall scope of the error, and possibly why it was incurred.  This Error would also maintain the original output style that is already being used, if that is a requirement as well.

The primary use-case for doing this, is to make Exported errors easier to check without using string comparison.

For example, I could take the returned error, and see if the underlying issue was due to a specific cause that I might handle, as a special case.

```go
response, err := client.Endpoint()(ctx, request)
if err != nil {
	if e, ok := err.(httptransport.Err) {
		if e.Err == context.Canceled {
			// special handling
		}
	}
}
```

**Comment by peterbourgon** [comment]
That merge closed the issue. Thanks!
