### ISSUE TITLE
Support OpenTracing API

### ISSUE THREAD

**Issue by basvanbeek** [go-kit/kit#237]
Next to our native implementation of Zipkin it could be very beneficial to support the OpenTracing API.

http://opentracing.io/

We can probably get it done quickly by using this package: https://github.com/opentracing/opentracing-go

**Comment by peterbourgon** [comment]
Indeed Zipkin is becoming OpenTracing, on a long-enough timeline. Last I checked, a few months ago, the Go implementation was just a sketch, but it looks a little further along now. In any case, +1!

**Comment by bensigelman** [comment]
@peterbourgon I just saw this... I'm happy to do the work if there's interest here.

**Comment by peterbourgon** [comment]
@bensigelman Please! Let me know what you need.

**Comment by bensigelman** [comment]
@peterbourgon if you have any initial guidance about the go-kit side and/or specific requirements, that would be welcome. If not, I will just do my best to make sure that existing code continues to work and that new code can use OpenTracing with go-kit.

**Comment by peterbourgon** [comment]
Woohoo!

**Comment by bensigelman** [comment]
@peterbourgon thanks for your help :)
