### ISSUE TITLE
etcd service discovery package has low test coverage

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#239]
The client has 0% coverage, and the other component has no tests for the `<-responseChan` block in the main loop. It should be very straightforward to write two new tests to add this functionality.

**Comment by Bigguy34** [comment]
So is this Issue fixed? Or can someone still work on it?

**Comment by peterbourgon** [comment]
@AlexPikalov is working on it in #242. How's that going?

**Comment by jstordeur** [comment]
tentative PR: [#344](https://github.com/go-kit/kit/pull/344)

**Comment by jstordeur** [comment]
PR updated following code review and extra tests added for registrar

**Comment by peterbourgon** [comment]
Fixed! 🎉
