### ISSUE TITLE
log: Provide a simple concurrent safe Logger wrapper.

### ISSUE THREAD

**Issue by ChrisHines** [go-kit/kit#246]
#### Proposal

Add a new exported function to `Go-kit/log`.

```go
// NewMutexLogger returns a logger that uses a sync.Mutex to synchronize
// concurrent use of the wrapped logger.
func NewMutexLogger(logger Logger) Logger
```

#### Motivation

Go-kit/log should not require external code to use safely in a concurrent manner.

#### Status Quo

Go-kit/log carefully documents that `Logger` implementations must be safe for concurrent use. `NewLogfmtLogger` and `NewJSONLogger` document that they require an `io.Writer` safe for concurrent use *if the logger will be used concurrently*. That is to say that the Logfmt and JSON loggers are safe, but their side effect of writing data may not be safe. Unfortunately many implementations of `io.Writer` are not safe for concurrent use.

#### Alternatives

* A mutex based concurrent safe `io.Writer`, or a
* A channel based asynchronous Logger.

A MutexWriter allows the log event formatting to occur concurrently outside the scope of the mutex. A channel based AsyncLogger offloads log event formatting to a single background goroutine and also guarantees concurrent safe writing of the formatted data without additional locking, but it also complicates error handling and application shutdown.

**Comment by peterbourgon** [comment]
Strong +1. This should be not much code, do you think?

**Comment by ChrisHines** [comment]
The code is trivial. I am interested in opinions on the alternatives as well. I see advantages to each, and I have used an asynchronous Logger in production with log15 in the past. I can imagine a future where Go-kit/log included all three varieties, but I am concerned that doing so might introduce the paradox of choice. Thoughts? I can elaborate on the alternatives if that will help the discussion.

**Comment by basvanbeek** [comment]
I think choice is not necessarily a bad thing if the pros/cons are diligently documented. By elaborating on the alternatives we start that process and might end up with the conclusion that either a single solution is the best or choice is needed. Either way we'll have the arguments for our future decision written down.

**Comment by ChrisHines** [comment]
@peterbourgon & @basvanbeek Thanks for the feedback.

To move this forward I will create a PR that implements all three options. We can review and decide which to keep. It may be a few days before I have the time to put the PR together.

**Comment by peterbourgon** [comment]
I reckon this can be closed?
