### ISSUE TITLE
Filter leveled logging below a set level

### ISSUE THREAD

**Issue by bishoprook** [go-kit/kit#250]
Apologies if this is something that's been dealt with before but I couldn't find it in past issues or PRs.

If I set up a leveled logger and do some leveled log statements e.g.:

```
logger := levels.New(log.NewJSONFormatter(os.Stdout))
logger.Debug().Log("msg", "some debug stuff")
logger.Error().Log("err", "got an error")
logger.Info().Log("action", "user action was taken")
```

I would want the ability to set a log level above which I receive the log statements but below which they're discarded. Something like:

```
logger.LogLevel(levels.Error)
logger.Debug().Log("msg", "more debug stuff")  // now doesn't log anything
```

This saves a bit of CPU and I/O cost. It's a feature that log15 had, seems it just never came over here.

Also, you could prevent the evaluation of `Valuer`s, so I can do:

```
logger.Debug().Log("wowza", func() inferface{} { return someExpensiveOp() })
```

...but if the log level is set to Info or above, not only does this line not get evaluated, `someExpensiveOp` never gets called.

I'm game to do the work and send the PR if this sounds like something desirable!

**Comment by ChrisHines** [comment]
@bishoprook I would like to see a good implementation of this idea in the log/levels package. I will gladly review a PR along these lines.

The approach taken by log15 is to filter the log events after they enter the logging stack with `log15.LvlFilterHandler`. Taking that approach allows for an interesting composition with `log15/ext.EscalateErrHandler` which can change the level of a log event based on other fields, potentially allowing it to pass the level filter anyway.

Implementing level filtering directly in `log/levels.Levels` allows less flexibility, but provides the opportunity to do less work for filtered events.

My preference is for the first approach but that could change once we see what the code looks like.

**Comment by bishoprook** [comment]
See the PR I just submitted and let me know what you think. :)

**Comment by peterbourgon** [comment]
This is now accomplished with [level.Options](https://godoc.org/github.com/go-kit/kit/log/level#Option).
