### ISSUE TITLE
Create a new `kit/metrics/graphite` package for aggregating and emitting metrics to Graphite

### ISSUE THREAD

**Issue by jprobinson** [go-kit/kit#251]
To help transition users of go-metrics & go-metrics-graphite to kit's metrics package, I would like a new package for aggregating counters, timers and gauges and periodically emitting the stats to graphite directly.

**Comment by jprobinson** [comment]
I'm going to spend some time over the few couple of days taking a whack at this one.

So far, I'm playing with creating an interface to tie the different metric types together and periodically push the data to a graphite host via a shared TCP connection (similar to go-metrics's Registry + go-metrics-graphite's Graphite type).

At this point, the interface is looking like:
```
type GraphiteEmitter interface {
    NewCounter(string) metrics.Counter
    NewHistogram(string) metrics.Histogram
    NewGauge(string) metrics.Gauge

    Start()
    Emit() error
}
```
The pattern of use would be:
  1. create a new 'emitter': `NewGrahpiteEmitter(addr *net.TCPAddr, prefix string, interval time.Duration) GraphiteEmitter`
  2. add any counters, gauges or histograms needed
  3. `Start()` the emitter to push the data every interval
  4. Users call `Emit()` in case the process needs to shut down and current stats need to be flushed to graphite first.

**Comment by jprobinson** [comment]
So far, gauges and counters are no problem. The more I look at histograms, though, the more I'm thinking we might not to write _another_ implementation. 

On that note, any thoughts on bringing https://github.com/codahale/hdrhistogram in for just for this package?

**Comment by peterbourgon** [comment]
@jprobinson That's what I did in metrics/expvar :) I think it's a fine idea. s/Emit/Flush?

**Comment by jprobinson** [comment]
👍 awesome.

I went back and forth on Emit/Flush too. Flush is definitely a more recognizable method for this purpose. I guess I was trying to avoid creating a 'GraphiteFlusher' interface as it sounds a bit like metrics would be going down the toilet. 😜 I'll keep the `GraphiteEmitter` monicker, but use `Flush()`.

**Comment by peterbourgon** [comment]
:tada:
