### ISSUE TITLE
package auth/jwt

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#255]
I think it would provide a lot of value if we could have some middleware that used JWT to do service-to-service auth. I think it should compose pretty well, lifting and pulling keys from the context.

**Comment by basvanbeek** [comment]
I'm in need of such a thing and about to build it with my team so we'll work on a PR

**Comment by peterbourgon** [comment]
From Slack—

There should be I think two endpoint.Middlewares. Start with the validation side: a middleware that extracts the JWT tokens from the context.Context, checks they're valid, and returns an error if they're not. Then you'll need various helper functions to move JWT information from e.g. an HTTP request or gRPC context into the context.Context. Package tracing/zipkin has examples of that.

Then there's the other side, i.e. injecting JWT information into (presumably outgoing?) requests. I'm not super familiar with JWT infrastructure so I'm not sure how that will look. I speculate it will be the same thing only reversed: middlewares that query a JWT authority and inject information to the context.Context, and helper functions to move JWT information from the context.Context to the HTTP or gRPC request.

**Comment by briankassouf** [comment]
Hey @peterbourgon is this still needed? I'd like to make a PR implementing JWT service-to-service auth.

**Comment by peterbourgon** [comment]
Very much yes. Is the design and implementation plan clear?

**Comment by ifraixedes** [comment]
In case that it may helps.
Here there's some part of the implementation that I was doing a certain point but I put it in the shelf due other priorities.

https://github.com/ifraixedes/kit/tree/jwt-auth/auth/jwt

**Comment by briankassouf** [comment]
@peterbourgon I believe so. I created a WIP pull request with the initial design. It implements the middleware and helper functions for passing into grpc requests.

checkout #335 and let me know what you think!

**Comment by briankassouf** [comment]
@peterbourgon One main question is, should it be it's own package (`github.com/go-kit/kit/auth/jwt`) or should it be an auth package (`github.com/go-kit/kit/auth`) with functions for creating the middleware. This second option is similar to how the circuit breaker and ratelimiting packages work.

**Comment by peterbourgon** [comment]
circuitbreaker and ratelimiter are different in the sense that they implement exactly the same concrete middlewares, they just differ depending on which specific implementation of a breaker or token bucket you want to use. I think JWT is different: I think the mechanics of JWT-style auth are going to be sufficiently different than e.g. HTTP Basic-Auth to warrant completely different packages. So, tl;dr: please use `auth/jwt`.

I will try by best to find some time for a review in the next day or two. Thanks very much for the contribution!

**Comment by briankassouf** [comment]
Got it, thanks for the explanation! 

@ifraixedes thanks for the reference! i think i will borrow some of your naming conventions

**Comment by ifraixedes** [comment]
@briankassouf take as many things as you want
