### ISSUE TITLE
Support Zipkin via OpenTracing

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#256]
After #247, it should be possible to provide Zipkin integration through the OpenTracing scaffolding. I'd love to do it that way, and standardize on a single set of mechanics!

**Comment by basvanbeek** [comment]
PR #271 allows Zipkin integration through the OpenTracing scaffolding.

**Comment by basvanbeek** [comment]
This is now available including documentation on how to migrate from the proprietary package to the new OpenTracing package.
