### ISSUE TITLE
RequestFunc should accept the http.ResponseWriter besides the http.Request

### ISSUE THREAD

**Issue by pengux** [go-kit/kit#257]
Currently, there is no way to write response headers when there is an error with the request in a RequestFunc as there is no http.ResponseWriter. Therefore, when calling a before function, it should also pass the http.ResponseWriter to it.

**Comment by peterbourgon** [comment]
Can you say a bit more about your use case? RequestFuncs are intended only as a way to move information from the HTTP request into the context. Request validation (and possible request termination) should happen in your DecodeFunc (if it's a serialization or format error) and/or a middleware (if it's a business-logic error).

**Comment by pengux** [comment]
One use case is to terminate the request and return a response with correct headers with HTTP Basic Auth for example or continue but setting variables in the request context. This can't be done as the context is only accessible inside the before/decode functions but they in turn don't have access to the http.ResponseWriter.

**Comment by peterbourgon** [comment]
BeforeFunc is the wrong place to do that work. You should do that in [DecodeRequest](https://godoc.org/github.com/go-kit/kit/transport/http#DecodeRequestFunc). Return an error if you want to terminate request processing.

**Comment by pengux** [comment]
Yes, but as I mentioned, DecodeRequest doesn't have access to http.ResponseWriter either so I cannot set the correct response headers when terminating the request either. Is there a way around this?

**Comment by peterbourgon** [comment]
Yes, have DecodeRequest return a custom error that your ErrorEncoder knows how to interpret and set the response headers and terminate the request there.

**Comment by pengux** [comment]
Will it works for non-error responses to, such as redirection (300+) in status codes?

**Comment by peterbourgon** [comment]
Your ErrorEncoder can return whatever status code, headers, body it wants :) [Here's the relevant code](https://github.com/go-kit/kit/blob/e82fca6ef3304f43c54f07b53d20324ab646b7c4/transport/http/server.go#L86-L91), you can see it just gets called and then the handling stops.

**Comment by pengux** [comment]
OK, just feel a little off to generate an error for redirection though.
