### ISSUE TITLE
log: add a benchmark

### ISSUE THREAD

**Issue by philips** [go-kit/kit#258]
There is a Go logger benchmarking tool. We should try and benchmark the log library against it: https://github.com/imkira/go-loggers-bench

**Comment by peterbourgon** [comment]
@ChrisHines Is this interesting for you? Otherwise I can take a crack at it.

**Comment by ChrisHines** [comment]
I am interested in the results, but feel free to write the code. I'll be
happy to review it if you Cc me on it.

**Comment by ChrisHines** [comment]
BTW, I have done a less detailed version of this type comparison before. I updated the results after the recent performance improvements we've made. Here is what I have done: https://gist.github.com/ChrisHines/5c32bd11dd16db713776.

**Comment by peterbourgon** [comment]
https://github.com/imkira/go-loggers-bench/pull/1

**Comment by philips** [comment]
neato, thanks Peter!

**Comment by peterbourgon** [comment]
It was merged in.
