### ISSUE TITLE
Improve OpenTracing documentation

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#260]
I'm guessing this is primarily a richer README, but maybe @bensigelman has additional ideas.

**Comment by bensigelman** [comment]
@peterbourgon can you assign this to me? (I don't think I have privileges to do so)

**Comment by basvanbeek** [comment]
Do we consider this one closed too or will we add more to the README?

**Comment by bensigelman** [comment]
@basvanbeek let's close it! Thanks again.
