### ISSUE TITLE
Example profilesvc does not run

### ISSUE THREAD

**Issue by joni8a** [go-kit/kit#261]
Hello, when I try to run the profilesvc example I get the following errors:
`./main.go:34: undefined: ProfileService
./main.go:36: undefined: newInmemService
./main.go:37: undefined: loggingMiddleware
./main.go:42: undefined: makeHandler`

Unfortunately I am just started with go so I think I am not able to solve this myself yet.

**Comment by peterbourgon** [comment]
You need to `go build`, not `go run main.go`.

**Comment by peterbourgon** [comment]
I'm pretty sure that was the issue. Please re-open if it doesn't work :)
