### ISSUE TITLE
metrics: Provider interface

### ISSUE THREAD

**Issue by bmarini** [go-kit/kit#262]
What do you think about adding an interface like this?

``` golang
type Provider interface {
	NewCounter(name string) Counter
	NewGauge(name string) Gauge
	NewHistogram(name string) Histogram
	NewTimeHistogram(name string) TimeHistogram
}
```

This would allow calling code to easily add new metrics and allow the backend to be easily swapped out system wide. I'm adding this interface to my code so I can  implement a provider with expar and dogstatd backends, and some global tags for all metrics. I'm not sure how else I would do this in the calling code unless I knew all the Counters, Gauges, and Histograms I would need ahead of time and passed them all in...

**Comment by yurishkuro** [comment]
1. Factory would be a more accurate name, because it builds a new instance rather than "providing" an existing one
 1. I would recommend `NewXxx(name string, tags [string]string) Counter` interface. A single string name for metrics (default in statsd / Grafana) is quite limiting for aggregation purposes. Tags allow aggregations by different dimensions. At the same time, implementation can always degrade to a single string name if the backend does not support tags

**Comment by bmarini** [comment]
Each metric type interface allows for tagging with `With(f metrics.Field)` that adds a tag to a metric, so having it be part of the constructor is not strictly necessary. Could be nice though.

**Comment by yurishkuro** [comment]
> Each metric type interface allows for tagging with With(f metrics.Field) that adds a tag to a metric,

ok, I didn't know that. My main point was that once a counter, gauge. etc. is created, the user code should store the reference and only call update methods like `counter.Inc(delta)`, because passing and handling tags for every sample is way too expensive. It also prevents users from emitting unique tag values for every sample, which can very easily kill a backend like graphite.

**Comment by peterbourgon** [comment]
@yurishkuro Your previous experience may be coloring your expectations here. It is absolutely desirable and necessary that users may emit unique tag values for every sample. The fact that this kills backends like Graphite is a fundamental design problem with Graphite. kit/metrics is very much in the Prometheus school of instrumentation.

**Comment by peterbourgon** [comment]
@bmarini 

> I'm not sure how else I would do this in the calling code unless I knew all the Counters, Gauges, and Histograms I would need ahead of time and passed them all in...

Yes, you should definitely know all of your Counters, Gauges, and Histograms _a priori_. Is that not the case for you? Can you give more details of your context?

**Comment by bmarini** [comment]
@peterbourgon I'm adding instrumentation to a new application. I haven't used go-kit before, but have used statsd and dogstatsd. I'd like to implement metrics with interfaces throughout my application so I can easily swap out statsd with prometheus, or have multiple backends like dogstatsd and expvar.

Here's some example code, lets assume this is a sub system in my application:
https://play.golang.org/p/B0zkfpplQy

For this code, I need a handful of counters, gauges and histograms. What I'm struggling with is how best to inject them into my `PoolManager` struct. It would be pretty clunky to specify all of them as concrete fields on the struct. This is the motivation for the Provider. I could add a Provider to the PoolManager struct easily. (This provider would be configured in main() and passed down through the application where ever instrumentation is needed.) Am I approaching this wrong?

**Comment by yurishkuro** [comment]
@peterbourgon 
> It is absolutely desirable and necessary that users may emit unique tag values for every sample.
then
> Yes, you should definitely know all of your Counters, Gauges, and Histograms a priori.

Isn't this a contradiction? If you know your counter a priori (which is what I was suggesting), then all the tags of that counter are already decided (at construction). If I misunderstood you, could you elaborate? By unique tag names I mean, for example, that uses would never associate a request uuid with increment of a counter - while it's certainly possible to build a system to handle that, I fail to see the value in such counter. To get more concrete, a pseudo-code example

```
var okCounter = metricsFactory.newCounter("requests", map[string]string { "status": "ok" })
var errCounter = metricsFactory.newCounter("requests", map[string]string { "status": "err" })
```

Good:
```
func handle(r Request) error {
   err := reallyHandle(r)
   if err != nil {
      errCounter.Inc(1)
   } else {
      okCounter.Inc(1)
   }
   return err
}
```

Bad:
```
func handle(r Request) error {
   err := reallyHandle(r)
   if err != nil {
      errCounter.withField(Field("uuid", r.UUID)).Inc(1)
   } else {
      okCounter.withField(Field("uuid", r.UUID)).Inc(1)
   }
   return err
}
```

**Comment by peterbourgon** [comment]
@bmarini 

>  It would be pretty clunky to specify all of them as concrete fields on the struct. 

I don't find anything clunky about that at all. The minimal changes would be to add those fields to the struct:

```go
type PoolManager struct {
    Concurrency int
    Handler Handler

    messagesReceived metrics.Counter
    messagesFailed metrics.Counter
    messagesSucceeded metrics.Counter
    processingDuration metrics.TimeHistogram
}
```

All of those metrics should be constructed in your func main and passed as dependencies to the PoolManager constructor or struct init.

```go
func main() {
    var (
        messagesReceived = dogstatsd.NewCounter(...)
        messagesFailed = dogstatsd.NewCounter(...)
        // ...
    )
    pm := PoolManager{
        // ...
        messagesReceived: messagesReceived,
        messagesFailed: messagesFailed,
        // ...
    }
}
```

**Comment by peterbourgon** [comment]
@yurishkuro The metrics themselves and tag _names_ can be known apriori at construction, but the tag _values_ likely are not. So

```go
okCounter := newCounter("requests", map[string]string{"status": "ok"})
errCounter := newCounter("requests", map[string]string{"status": "failed"})

if ok {
    okCounter.Inc(1)
} else {
    errCounter.Inc(1)
}
```

is probably better expressed as

```go
counter = newCounter("requests")

if ok {
    counter.With("status", "ok").Inc(1)
} else {
    counter.With("status", "failed").Inc(1)
}
```

To understand why, think about a slightly more general case:

```go
duration := newTimeHistogram("request_duration")

duration.With("method", r.Method).With("path", r.URL.Path).With("status_code", code).Observe(time.Since(begin))
```

One cannot precompute all possible permutations of those dimensions at construction time.

**Comment by bmarini** [comment]
Ok, I'm coming around on this one. I thought initially it would be cumbersome to do this for an application that will probably end up with  25-50 metrics or more. Now I'm thinking it will be really nice to see all the metrics defined in one place, rather than scattered throughout the codebase. Thanks for the help @peterbourgon

**Comment by peterbourgon** [comment]
Yay!

It would be much cleaner if [dog]statsd metrics supported fields, e.g.

```go
messages = dogstatsd.NewCounter("messages", "phase")

messages.With("phase", "received").Inc(1)
messages.With("phase", "succeeded").Inc(1)
messages.With("phase", "failed").Inc(1)
```

This is hinted at [in this pkg comment](https://github.com/go-kit/kit/blob/e82fca6ef3304f43c54f07b53d20324ab646b7c4/metrics/statsd/statsd.go#L3-L11); I think it should be straightforward and a PR would be happily accepted :)

**Comment by peterbourgon** [comment]
Filed #263 for those enhancements. Closing this ticket now; please feel free to reopen if you have unanswered questions :)

**Comment by yurishkuro** [comment]
@peterbourgon 
> `duration.With("method", r.Method).With("path", r.URL.Path).With("status_code", code).Observe(time.Since(begin))`

Whether or not this is an example of _unique_ tag names depends on the cardinality of `r.URL.Path` value space. If it's a small set of URL values, then I have no problem with that example. If URL includes things like object IDs, then the metric becomes pretty useless, since each metric has a unique name and they cannot be aggregated without `path=*` condition.

**Comment by bmarini** [comment]
Yeah, noticed that with expvar as well. Should be straight forward. Also I noticed that kit/dogstatsd doesn't aggregate counters (perhaps because it is harder?) So if I counter.Add() multiple times, it will flush a count stat for every `Add()` instead of just one with the sum.

**Comment by peterbourgon** [comment]
@yurishkuro Yes of course the dimensionality of paths must be bounded :)

@bmarini I agree aggregation would be a fine optimization for that package.

**Comment by peterbourgon** [comment]
After some long and patient conversation with @jprobinson I was convinced of the utility of a kit/metrics/provider package for middleware and framework developers. Here is my strawman code, directly inspired by @bmarini (thank you for the conversation and patience as well) —

```go
package provider

// Provider represents a union set of constructors and lifecycle management
// functions for each supported metrics backend. It should be used by those
// who need to easily swap out implementations, e.g. dynamically, or at a 
// single point in an intermediating framework.
type Provider interface {
    Counter(name string) metrics.Counter
    Gauge(name string) metrics.Gauge
    Histogram(name string) metrics.Histogram
    Stop()
}

func NewGraphiteProvider(...) Provider { ... } 
func NewPrometheusProvider(...) Provider { ... } // Stop is a no-op
/// etc.
```

**Comment by jprobinson** [comment]
As I get deeper into this, I'm debating on extracting out the new `manager` type from the `metrics/graphite` PR to the new `metrics/provider` package so the `statsdProvider` can also use it. This means the new `graphite.Emitter` would need to live in this new `provider` package, making the Counter/Gauge/Histogram implementations in `metrics/graphite` pretty minimal.

Any thoughts?

**Comment by peterbourgon** [comment]
Why would that imply the graphite.Emitter needs to move to package provider?

**Comment by jprobinson** [comment]
If the `manager` type moves to `metrics/providers` and `metrics/graphite` attempts to use it, there would be a cyclic reference as `metrics/providers` would need some way of accessing graphite-specific implementations to access current metric values.

**Comment by jprobinson** [comment]
Another way might be to add "getter" methods to the base metrics interfaces, but not sure if thats something we're trying to avoid.

**Comment by peterbourgon** [comment]
Ah, of course. Since manager is general-purpose, can we move it to e.g. kit/util/conn.Manager?

**Comment by peterbourgon** [comment]
We've got this now! 🙌
