### ISSUE TITLE
metrics: support fields and sampling in [dog]statsd implementations

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#263]
[As described in this doc comment](https://github.com/go-kit/kit/blob/e82fca6ef3304f43c54f07b53d20324ab646b7c4/metrics/statsd/statsd.go#L3-L11). See also [this comment from issue #262](https://github.com/go-kit/kit/issues/262#issuecomment-219301811).

**Comment by ifraixedes** [comment]
I stopped in this issue as it's marked as "newbie friendly", but after reading the thread on #262 and see the changes which #268 I'm wondering if this proposed enhancement still valid.

**Comment by peterbourgon** [comment]
Definitely still want this functionality. It may conflict with changes underway in those two PRs, but I hope not too badly.

**Comment by peterbourgon** [comment]
As part of this ticket, we should extract the histogram in metrics/expvar and metrics/graphite to its own package, probably metrics/internal/histogram.

**Comment by xmattstrongx** [comment]
Is this issue still active and seeking help?

**Comment by peterbourgon** [comment]
Very much yes :)

**Comment by xmattstrongx** [comment]
Cool. Ill begin looking at this very soon then.

**Comment by peterbourgon** [comment]
Thank you very much. Let me know if you have any design or implementation questions.

**Comment by xmattstrongx** [comment]
Will do, and I am sure I will some design questions for this one. Probably wont be able get started on this until the weekend.

**Comment by peterbourgon** [comment]
Yeah, this will be resolved by #313.

**Comment by peterbourgon** [comment]
Oh! This was fixed :)
