### ISSUE TITLE
grpc.NewClient hard-codes proto buf package to "pb"

### ISSUE THREAD

**Issue by waigani** [go-kit/kit#281]
https://github.com/go-kit/kit/blob/master/transport/grpc/client.go#L40 

This tripped me up when testing with https://github.com/grpc/grpc-go/tree/master/examples/helloworld which names the package "helloworld". This will be a common entry point for new users and, more to the point, hard-coding to "pb" prohibits using any other package name.

Either serviceName needs to include the package ("pb.Add") or NewClient needs to take a package parameter. Happy to make a PR for the one that makes most sense.

**Comment by basvanbeek** [comment]
backward compatible fix has been merged into master
