### ISSUE TITLE
Add sd.Registrar for etcd

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#284]
Take a look at the [sd.Registrar](https://godoc.org/github.com/go-kit/kit/sd#Registrar) type, and the [implementation for Consul](https://godoc.org/github.com/go-kit/kit/sd/consul#Registrar).

- [ ] implement sd/etcd.Registrar
- [x] implement sd/zk.Registrar

**Comment by basvanbeek** [comment]
i'll handle the zookeeper one

**Comment by xmattstrongx** [comment]
Id like to take a crack at implement sd/etcd.Registrar

**Comment by xmattstrongx** [comment]
Pretty new to committing to open source projects but I started implementing the register/deregister functions for etcd.

[https://github.com/xmattstrongx/kit/commit/850dc91faf9815b081d8eb384108c3d3b054dc9c](url)

**Comment by peterbourgon** [comment]
@xmattstrongx yeah, looks like a good start! If you want, you can open a pull request, even though you're not finished. We can have an easier discussion and code review through the PR.

**Comment by xmattstrongx** [comment]
Anything else needed to close this?

**Comment by peterbourgon** [comment]
Nope! Many thanks.
