### ISSUE TITLE
[Feature Request] Rpc call uuid's?

### ISSUE THREAD

**Issue by hardcoar** [go-kit/kit#286]
This is particularly on transports. Currently we implement this on application level and i think it would be awesome to be included in the library.

Say i have svc1 implementing client.endpoint for svc2. I really want to id the whole rpc call from svc1 to svc2 for logging and metrics purposes. I want to id the http request and its rpc call from another service - where both would have the same uuid to be used as reference for logging and so. It would be awesome if there's a function that enables to auto generate uuid's per endpoint calls which you can retrieve from both ends through context. I want it to just call from go-kit transport package instead implementing my own.  

cheers for an awesome library (:

**Comment by basvanbeek** [comment]
I advise to use the OpenTracing package which gives you all this and so much more...

Look at the addsvc for implementation details.

**Comment by hardcoar** [comment]
i see. im trying something more simpler. the package is much more richer. thanks btw. im closing this now.
