### ISSUE TITLE
After ClientOption

### ISSUE THREAD

**Issue by geoffberger** [go-kit/kit#290]
We're looking for a way to obtain the `http.Response` when `httptransport.NewClient` has been called independent of `http.DecodeResponseFunc`. More specifically, once the request has been completed. Here's the motivation for this:

- To do logging that requires various response information such as the status code, URL, and HTTP Headers. This, in combination with either a service or middleware endpoint, would accomplish this result.
- Ability to add values to `context.Context` for the decode function. For example, a response could send back a HTTP Header and by adding the header to `context.Context`, it creates a unified way of accessing values.

**Comment by geoffberger** [comment]
Addressed in #289

**Comment by peterbourgon** [comment]
Merged.
