### ISSUE TITLE
[Question] Deployment, Discovery, Orchestration

### ISSUE THREAD

**Issue by hardcoar** [go-kit/kit#294]
I know this is not part of go-kit's goal but i just want to get the idea on how to implement this.
The package itself includes loadbalancing and service discovery.

Currently im using consul for service discovery (based on given examples). How would i deploy the app? like i know, orchestration is not part of the main goals for this framework, and also everyone is headed for production. 

Are there any suggestion on how to deploy, orchestrate the services like in kubernetes or nomad any orchestration tool. How should i loadbalance my services once they're inside docker containers and are managed by kuberentes/nomad?

Please do share your thoughts and suggestions to this. Help me I dont see the big picture xD

Any help is greatly appreciated!

PS: go-kit is awesome.

**Comment by peterbourgon** [comment]
I think GitHub issues are probably not the correct forum for this discussion. Please drop by the [Gophers Slack](https://invite.slack.golangbridge.org/), channel #go-kit, if you'd like to talk a little bit about this :)
