### ISSUE TITLE
[Question] Are there any plans to have a testing package?

### ISSUE THREAD

**Issue by hardcoar** [go-kit/kit#302]
I'm just curious if go-kit have some plans implementing a package for testing.

**Comment by xmattstrongx** [comment]
@hardcoar Do you mean a package for testing as in a testing framework?

**Comment by hardcoar** [comment]
imean testing solely for go-kit

**Comment by peterbourgon** [comment]
I don't understand the question. Can you give an example of what you'd expect to find in that package?

**Comment by peterbourgon** [comment]
Please re-open if and when you can clarify :) Thank you!
