### ISSUE TITLE
How to use kitgen commands in kitgen branch?

### ISSUE THREAD

**Issue by kumaranvpl** [go-kit/kit#310]

**Comment by kumaranvpl** [comment]
@peterbourgon

**Comment by peterbourgon** [comment]
Don't. It's entirely experimental code.

**Comment by kumaranvpl** [comment]
Ohhh ok... @peterbourgon Is this one useful https://github.com/Ayiga/go-kit-middlewarer
I am new to golang and using template generator will help me to focus only in business logics.
