### ISSUE TITLE
docs: example addsvc & grpc

### ISSUE THREAD

**Issue by hardcoar** [go-kit/kit#312]
can you please provide an example using transport grpc having context from client used in server side? like client puts something inside context.Context, parsed in server for some info and then puts a context back for client to parse again. I cant get it right with package's grpc metedata.

Any help and feedback is much appreciated. thanks!

**Comment by peterbourgon** [comment]
It's not possible for a client to pass a context to a server over a process boundary, have the server populate information in the context, and get that information back in the client. Contexts propagate information "downward" only; if you want to get information out in the other direction, functions need to return a (modified) context object, which I guess gRPC doesn't provide for.

**Comment by peterbourgon** [comment]
Hope that answers the question! Please re-open if I've misunderstood :)
