### ISSUE TITLE
Rotating file logger

### ISSUE THREAD

**Issue by kumaranvpl** [go-kit/kit#320]
How to implement rotating file logger using go-kit log

**Comment by peterbourgon** [comment]
Your service should have no concept of files, or rotating them. This is the responsibility of your runtime platform, not your code. See also http://gokit.io/faq/#how-should-i-aggregate-my-logs

**Comment by peterbourgon** [comment]
And to be a bit more helpful, look in to third-party tools like [svlogd](http://smarden.org/runit/svlogd.8.html).

**Comment by ChrisHines** [comment]
Or you can use gopkg.in/natefinch/lumberjack.v2.
