### ISSUE TITLE
Support fasthttp transport

### ISSUE THREAD

**Issue by thnt** [go-kit/kit#321]
Any plan to support [fasthttp](https://github.com/valyala/fasthttp)?

**Comment by peterbourgon** [comment]
Based on the author's comments and described development methodology [in this Reddit thread](https://www.reddit.com/r/golang/comments/3ty5uy/fast_http_package_for_go/?st=iqnnt2ea&sh=15fce64c) I'm not really interested in adding support, no. But if someone wanted to make a PR, I would certainly give it a look and try it out!

**Comment by peterbourgon** [comment]
Closing, as I guess I answered the question.
