### ISSUE TITLE
kit/log/levels: Support checking if a log level is enabled

### ISSUE THREAD

**Issue by hnakamur** [go-kit/kit#324]
I read #250 and #269 and thought maybe a simpler approach should be enough.

I think it's important to avoid the execution cost of debug prints when a log level is disabled.
To achieve that, it is best to surround log printing statement with `if`.
For example, the following code

```
logger := levels.New(log.NewJSONFormatter(os.Stdout))
logger.Debug().Log("msg", "some debug stuff")
```

should be written as something like pseudo code

```
logger := levels.New(log.NewJSONFormatter(os.Stdout))
if the_debug_level_is_enabled() {
    logger.Debug().Log("msg", "some debug stuff")
}
```

I sent #322 to achieve this.

**Comment by peterbourgon** [comment]
Closed with #322
