### ISSUE TITLE
kig/log: Add package for structured errors

### ISSUE THREAD

**Issue by hnakamur** [go-kit/kit#325]
I think the ideal way to log an error is logging just once and logging the error message as well as key value pairs to help debugging.
So here goes "structured errors" which wraps the original error and attach key value pairs to it with the following functions.

* `With(err error, keyvals ...interface{}) error`
* `WithPrefix (err error, keyvals ...interface{}) error`

I sent #323.
Please see examples at https://github.com/hnakamur/kit/blob/88b8fe3a1290632b134f1b703c05c31ff2abea02/log/sterrors/sterrors_test.go

**Comment by peterbourgon** [comment]
As noted in the PR, https://github.com/pkg/errors already solves this problem much better than I can possibly hope to, and is totally composable with Go kit services. Thanks for your thought and attention!
