### ISSUE TITLE
streams example

### ISSUE THREAD

**Issue by waigani** [go-kit/kit#326]
Can go-kit grpc endpoints support streams? I've tried a few different approaches without success.  For example, what would an implementation that supports the following look like:

rpc ListFeatures(Rectangle) returns (stream Feature) {}
(from here: https://github.com/grpc/grpc-go/blob/master/examples/gotutorial.md)

An stream example in the repo would be very useful. Until then, any tips?

**Comment by peterbourgon** [comment]
Yep, it's happening (slowly) in #295 (issue) and #298 (PR).

**Comment by walmav** [comment]
Looking around in the examples I could not find an example of grpc streams. Can you please point me to the example link here. Much appreciated.

**Comment by peterbourgon** [comment]
gRPC streams have no direct Go kit support.

**Comment by IvalisEXE** [comment]
I have the same problem, implementing gokit with grpc stream?

**Comment by peterbourgon** [comment]
gRPC streams are not supported by Go kit.

**Comment by IvalisEXE** [comment]
> gRPC streams are not supported by Go kit.

do you have good references like gookit problems with streams
