### ISSUE TITLE
Value binding outside of log.With.

### ISSUE THREAD

**Issue by ChrisHines** [go-kit/kit#33]
##### The Problem
```go
logger.Log("caller", log.DefaultCaller, "foo", "bar")
```
does not work the same as
```go
logger = log.With(logger, "caller", log.DefaultCaller)
...
logger.Log("foo, "bar")
```
##### Detailed Explantion
The current log package supports dynamic values in log contexts by passing a `Valuer` to `With`. A `Valuer` is a function that `withLogger` calls and replaces with the return value when its `Log` method is invoked. For example:
```go
logger := log.With(baseLogger, "caller", log.DefaultCaller)
...
logger = log.With(logger, "req", reqID) // pretend reqID == 10
...
logger.Log("foo", "bar")
```
Which would result in the `withLogger` essentially performing:
```go
baseLogger.Log("caller", stack.Caller(3), "req", 10, "foo", "bar)
```
Unfortunately the similarity in how we pass key/value arguments to `With` and `Log` leads to the expectation that the following should work. 
```go
baseLogger.Log("caller", log.DefaultLogger, "req", 10, "foo", "bar)
```
Expanding `DefaultLogger` we see that the result is a function value, not a call site value.
```go
baseLogger.Log("caller", func() interface{} { return stack.Caller(3) }, "req", 10, "foo", "bar)
```
##### The Challenge
There is a subtle bit of magic in the current implementation. No matter how many layers of context are built up `DefaultCaller` is always three stack frames below the call to `withLogger.Log`. This holds because `With` and `withLogger` take care to flatten the stored log context and copy the base logger into a new `withLogger` rather than creating a new layer each time.

Unfortunately not all calls to `Log` go through `withLogger`, which is why value binding is currently only supported on arguments to `With`.

The challenge is to support logging a `stack.Call` referring to the top level call to `Logger.Log` regardless of whether it is stored in a log context created by `log.With` or provided directly to `Logger.Log`. The solution must be convenient for application code to use and not change the `Logger` interface.
##### Counter Argument
Value binding is not strictly needed when calling `Log` as the application could simply provide the bound value directly. Why wrap it in a late binding mechanism only to immediately perform the binding? Could better package documentation be the solution?

**Comment by peterbourgon** [comment]
I think we've decided to punt on this problem, and say that the DefaultCaller will only ever work in With, and that users are expected to manage their own call stack depth with log.Caller(n) outside of With. @ChrisHines, if you agree, I think we can close this issue.

**Comment by ChrisHines** [comment]
@peterbourgon I agree, although remember that this issue is about all `log.Valuer`s, not just `log.Caller`.

Nonetheless, I think when we replaced `log.With` with `log.Context` it became easier to understand the scoping of `Valuer`s. Let's make sure the docs clearly indicate that connection and then we can close this issue.
