### ISSUE TITLE
transport/http: Need some way to read from context

### ISSUE THREAD

**Issue by yookoala** [go-kit/kit#334]
Contextural information (e.g. request id) can be crucial for tracing issue. It is reasonable to expect provide a mechanism for logger to learn the session context before any error logging.

In [server.go](https://github.com/go-kit/kit/blob/7054e06d3aafd68591cd13e628618294f1f45d95/transport/http/server.go) of "transport/http", [Server.ServeHTTP](https://github.com/go-kit/kit/blob/7054e06d3aafd68591cd13e628618294f1f45d95/transport/http/server.go#L78) provides no information to the logger about the context.

There should be a ServerOption that can spawn a logger with information in context. This new option should run before decode but after the `BeforeFunc`s:

```go

// ServeHTTP implements http.Handler.
func (s Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := s.ctx

	for _, f := range s.before {
		ctx = f(ctx, r)
	}

	// add this
	logger := s.contextLogger(s.logger)

	request, err := s.dec(ctx, r)
	if err != nil {
		logger.Log("err", err) // use logger instead of s.logger
		s.errorEncoder(ctx, Error{Domain: DomainDecode, Err: err}, w)
		return
	}

	response, err := s.e(ctx, request)
	if err != nil {
		logger.Log("err", err) // use logger instead of s.logger
		s.errorEncoder(ctx, Error{Domain: DomainDo, Err: err}, w)
		return
	}

	for _, f := range s.after {
		ctx = f(ctx, w)
	}

	if err := s.enc(ctx, w, response); err != nil {
		logger.Log("err", err) // use logger instead of s.logger
		s.errorEncoder(ctx, Error{Domain: DomainEncode, Err: err}, w)
		return
	}
}

```

**Comment by yookoala** [comment]
Alternatively, the logger can be passed from BeforeFunc so it can be used in the entire Server session.

```go

// ServeHTTP implements http.Handler.
func (s Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
    ctx := s.ctx

    for _, f := range s.before {
        ctx = f(ctx, r)
    }

    logger := s.contextLogger(s.logger) // spawn logger
    ctx = WithLogger(ctx, s.logger) // set logger to context
    // can use `logger := GetLogger(ctx)` to retrieve the logger

    request, err := s.dec(ctx, r)
    if err != nil {
        logger.Log("err", err) // use logger instead of s.logger
        s.errorEncoder(ctx, Error{Domain: DomainDecode, Err: err}, w)
        return
    }

    response, err := s.e(ctx, request)
    if err != nil {
        logger.Log("err", err) // use logger instead of s.logger
        s.errorEncoder(ctx, Error{Domain: DomainDo, Err: err}, w)
        return
    }

    for _, f := range s.after {
        ctx = f(ctx, w)
    }

    if err := s.enc(ctx, w, response); err != nil {
        logger.Log("err", err) // use logger instead of s.logger
        s.errorEncoder(ctx, Error{Domain: DomainEncode, Err: err}, w)
        return
    }
}

```

**Comment by peterbourgon** [comment]
What is `s.contextLogger`? What about users who don't want or need a context-scoped logger?

**Comment by basvanbeek** [comment]
Sounds like you really want to use a `ServerBefore` function...

**Comment by yookoala** [comment]
> What is `s.contextLogger`?

Just a proposed function value that provide logger with any context information.
The implementation is up to the user (probably with another `ServerOption` setter)


> What about users who don't want or need a context-scoped logger?

There can be a default `s.contextLogger` that only pass the logger through.
Or we can have a nil test to skip it if contextLogger is not set.


> And what about other transports?

I have not study other transports.

**Comment by peterbourgon** [comment]
@basvanbeek I think the user wants the errors logged in the Server.ServeHTTP method directly ([e.g. this one](https://github.com/go-kit/kit/blob/803166ff08662870111f3420944200203a06629e/transport/http/server.go#L87)) to use a logger extracted from the context, so that they may be decorated with request-scoped values. 

I can understand the desire and the potential value, but it marks a big shift in how Go kit components themselves engage with their operating environment. Concretely, if we make this change, it would need to be mirrored in other transports. And then, shouldn't every component that exists in the request path do a similar thing whenever it needs a logger? Where do you draw the line? We set ourselves up for a lot of frustrating inconsistency. It's just not clear to me that all of that inconsistency, or even all of those changes, are worth the value that this provides.

@yookoala Can you point me to some code which would benefit from this change, or (maybe better) describe to me in as much detail the concrete problem that caused you to file this issue?

**Comment by basvanbeek** [comment]
Isn't it possible to achieve just that by having the http transport utilize a `NopLogger` and handling the contextual logging of errors in the decode, endpoint, encode and ErrorEncoder steps?

**Comment by peterbourgon** [comment]
Yes, I think that's a much more workable solution/rule:

> As a rule, Go kit component loggers don't interact with the context(s) that flow through them. If you want request-scoped values in your log output, pass NopLoggers to Go kit components, and perform your own logging in your encode, decode, before, and/or after functions.

**Comment by peterbourgon** [comment]
@yookoala I hope that's satisfactory for you?

**Comment by peterbourgon** [comment]
I hope that works. Please re-open if that's insufficient, or if you have further questions!
