### ISSUE TITLE
circuitbreaker: single implementation?

### ISSUE THREAD

**Issue by teepark** [go-kit/kit#337]
Please correct my understanding, but it seems like things like `metrics` and `sd` need to implement multiple back-ends because they actually interface with external systems. Other packages like `log` and `ratelimit` that don't suffer from that constraint just have a single implementation.

Doesn't `circuitbreaker` fit more into the latter camp? I'm not sure what we get from three separate wrappers -- nobody needs any particular implementation due to existing infrastructure. Should we pick and promote one of them like `ratelimit`, or implement our own like `log`?

**Comment by peterbourgon** [comment]
How shall we decide which implementation should be blessed? There are subtle differences between them, and at least I'm personally unqualified to take a position...

**Comment by teepark** [comment]
So am I. I came to this because I expected `kit/circuitbreaker` to have made an informed decision for me. Having 3 options actually increased the barrier to adoption, and it left me wondering why.

I can spend some time looking into the 3 and write up a comparison.

**Comment by teepark** [comment]
`sony/gobreaker` looks pretty strong.

It's a very direct implementation of the pattern as explained in a paper published by Microsoft.

- about as simple and small an implementation as possible
- interface for executing a function under the breaker is a simple `func() (interface{}, error)`
- flexibility from a callback-based open state trigger: `func(gobreaker.Counts) bool`
- no goroutines or channels are ever created by gobreaker
    - but the `CircuitBreaker` type is safe for concurrent use
- no commits of substance to the core code really since the initial commit
- well tested, 99% coverage
- sane behavior for the zero-value `Settings` struct:
    - 5 consecutive failures opens the circuit
    - circuit stays open for 60 seconds
    - next single request after the 60 seconds determines back to open (new 60 seconds) or closed (counters reset) state
- godoc on all public API, straightforward README, and an example in the repo

**Comment by peterbourgon** [comment]
Ah, my mistake: I think you may have misinterpreted my rhetorical question for a literal one :) There are multiple implementations there because when I wrote the package up initially, I went looking for a suitable circuit breaker implementation, and found those 3 in relatively common use; Package ratelimit, in contrast, I found only 2 common token bucket implementations, with one having since been abandoned.

In keeping with Go kit's design goal of light opinionation, I wouldn't remove the existing alternatives to bless one as the best. But, I would be happy to amend the package documentation to guide new users to sony/gobreaker. Would that solve your problem?

**Comment by teepark** [comment]
That sounds totally reasonable, I can understand not wanting to needlessly break backwards compatibility.

I don't quite follow the logic of "few opinions, lightly held" leading to 3 implementations of an algorithm though -- I can't really see anybody coming to gokit needing hysterix, they'll just need a circuitbreaker. Also FWIW there only appears to be one public use of [gokit's gobreaker support](https://sourcegraph.com/github.com/go-kit/kit/-/info/GoPackage/github.com/go-kit/kit/circuitbreaker/-/Gobreaker), the [other](https://sourcegraph.com/github.com/go-kit/kit/-/info/GoPackage/github.com/go-kit/kit/circuitbreaker/-/HandyBreaker) [two](https://sourcegraph.com/github.com/go-kit/kit/-/info/GoPackage/github.com/go-kit/kit/circuitbreaker/-/Hystrix) haven't had any.

But as far as coming to the package as a new user, having guidance in the docs like "unless you have a good reason, just use X" is the next best thing.

My previous comment wasn't meant to strictly advocate for `gobreaker`, I intended to follow up with deep dives on the other two but haven't had a chance yet. Let me know if that would still be useful.

**Comment by peterbourgon** [comment]
All fair points. I'll update the docs now.

**Comment by teepark** [comment]
Sorry this is only just now occurring to me: what about breaking these up into 3 sub-packages? As it is the package pretty much forces 2 unused dependencies on users.

That would also be backwards-incompatible of course.

**Comment by peterbourgon** [comment]
There is a tension when breaking out a package that satisfies a single common interface with multiple concrete implementations. Packages like circuitbreaker and log provide all implementations in the base package; packages like metrics and sd provide implementations in subpackages. I'm not sure there's a one-size-fits-all solution, so I defer to the size/complexity of the implementation, in a totally subjective feint toward usability. If the implementations are small, then they stay in the same package; if they're large they go to a new package.

Totally open to new strategies, of course, but that's been the logic so far.

**Comment by teepark** [comment]
That seems like sensible criteria. Thanks for the clarification!
