### ISSUE TITLE
log.PrefixLogger should become logfmt compliant

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#34]
[logfmt](https://godoc.org/github.com/kr/logfmt)

**Comment by ChrisHines** [comment]
+1

**Comment by peterbourgon** [comment]
Might also involve a rename.

**Comment by ChrisHines** [comment]
I agree a rename is warranted. I was going to raise this exact issue with PrefixLogger today if you hadn't. My apps currently use logfmt via the log15 implementation, and I've used the package linked above for parsing the logs.

I've been considering whether it would be worth it to write an encoding/json or encoding/xml style package that supports marshaling and unmarshaling logfmt data. Thoughts on that idea?

**Comment by peterbourgon** [comment]
Does that imply logfmt would become the common denominator format/encoding for gokit/log? If so, do you believe it's mature enough for that?

**Comment by ChrisHines** [comment]
The RFC says:
- Log SHALL be format agnostic by providing an interface for log formatting.
- Log MAY provide some built in formatters such as RFC3164, JSON, etc.

So I don't think it has to take on that role but I would like it to be one of the choices.

The logfmt package I was postulating would be standalone and gokit could chose to import it or not. It would be awesome if someone has already written such a package, but I haven't found one yet.

Regarding maturity, the best link I can find that speaks to that is: https://brandur.org/logfmt

**Comment by peterbourgon** [comment]
Ah, so your "an encoding/json or encoding/xml style package that supports marshaling and unmarshaling logfmt data" would be external to gokit/log?

**Comment by ChrisHines** [comment]
That was the idea, yes. It would hopefully be general enough for use in other logging packages or standalone, as well as providing the parsing side. It should also support [encoding.TextMarshaler](http://golang.org/pkg/encoding/#TextMarshaler) and [encoding.TextUnmarshaler](http://golang.org/pkg/encoding/#TextUnmarshaler) interfaces.

**Comment by peterbourgon** [comment]
:+1: to the idea!

**Comment by ChrisHines** [comment]
Status update: I [checked](https://github.com/kr/logfmt/issues/5) that the authors of https://github.com/kr/logfmt are OK with me creating a new Go project for logfmt. I have created [the project](https://github.com/go-logfmt/logfmt) and started implementing a `MarshalKeyvals` function built on top of a lower level `Encoder`.

The package is still unstable, tests are incomplete, and some tests still fail, but for logging basic data types from well behaved sources the `MarshalKeyvals` function will get the job done.

**Comment by peterbourgon** [comment]
Thanks, this looks great. Curious, why an org? Do you anticipate more repos, or just more collaborators? :)

**Comment by ChrisHines** [comment]
@peterbourgon 

>Curious, why an org? Do you anticipate more repos, or just more collaborators?

More collaborators would be welcome of course, but the primary reason for an org is to take advantage of the shorter import string [gopkg.in](http://labix.org/gopkg.in#SupportedURLs) provides when the org/repo name matches the pattern `go-pkg/pkg`:

    gopkg.in/logfmt.v1      → github.com/go-logfmt/logfmt (branch/tag v1, v1.N, or v1.N.M)

**Comment by peterbourgon** [comment]
Ah, I didn't know about that. (sigh) Some random convention invented by some random developer 3 years ago echoes through eternity...
