### ISSUE TITLE
SD - registration doesn't expire ?

### ISSUE THREAD

**Issue by pdaures** [go-kit/kit#343]
Hi, 
A stupid question : I checked the sd/etcd client and if I understood correctly, the registration doesn't expire. So, if the machine goes down violently, we won't run Deregister() and the service will still be registered.

Wouldn't it be better to have a TTL on the registration, and call it regularly ? So if the service goes down and cannot call Deregister, etcd will remove the service by itself and it won't appear anymore to the other services.

**Comment by peterbourgon** [comment]
Yes, your observation is correct. TTL is typically implemented by the service discovery system itself, in the form of regular health checks to registered services. If you think about it, this is strictly superior to heartbeating: less work overall, and a more accurate result.

Of course it's totally possible to do what you suggest. The right way, I think, would be to provide another implementation of Registrar for the systems you want to support, which performs this heartbeating under the hood. Which SD system do you have in mind? Would you be up for making a PR for that?

**Comment by pdaures** [comment]
Thx for answering quickly.
I had in mind etcd.

I don't think etcd has any type of built-in service health checks. 
I know we can register health check endpoints to Consul, but I haven't seen it in go-kit.

So, I guess for ETCD we would have to create a Registrar that calls ETCD every X duration.
For Consul, I don't know what would be the correct way of doing this, providing an endpoint ?

I don't have time this week to do this, but I can probably find some time next week.

**Comment by peterbourgon** [comment]
For etcd, I guess you will create a special registrar implementation that creates a key with a short TTL, and regularly refreshes the lease with a goroutine. For Consul, there's no single answer. Probably the best way would be to mount a /health endpoint into your service and configure Consul to ping it; that's more about configuring Consul than adding things to Go kit, though, I think.
