### ISSUE TITLE
Example of ToHttpRequest tracing.

### ISSUE THREAD

**Issue by cam-stitt** [go-kit/kit#347]
Hi there,

I'm looking for an example of ToHttpRequest usage. Currently, I have a similar setup to the addsvc that includes to seperate services communicating through a client. Within zipkin, I can see the spans for sending service and the client (which has the sending service name) but I can't see anything for the receiving service. I can't work out if it's something I'm missing, or if this is how it is supposed to work. Currently on phone, but can add screenshots of zipkin or anything else that may help.

Thanks,

Cameron

**Comment by cam-stitt** [comment]
I should note that I tried adding ToHttpRequest as a ClientBefore func, but it didn't help.

**Comment by peterbourgon** [comment]
Can you provide a minimal example which demonstrates the problem?

**Comment by cam-stitt** [comment]
Right, that makes sense. The link you supplied for ToHTTPRequest is using FromHTTPRequest, though. I'll make that change and see if it fixes it.

**Comment by peterbourgon** [comment]
Ha! You're right. D'oh.

**Comment by cam-stitt** [comment]
That certainly seemed to tidy up some of the tracing. The only thing I can see now is that the client send/receive seems to not be quite right. I assume this is because the other service isn't picking up the sent trace?

<img width="577" alt="screen shot 2016-08-23 at 8 33 55 pm" src="https://cloud.githubusercontent.com/assets/186643/17888937/f5943470-6970-11e6-8d75-9c98340bad40.png">

**Comment by cam-stitt** [comment]
Nvm. that was my own stupidity.

**Comment by cam-stitt** [comment]
Btw, thanks for your help!
