### ISSUE TITLE
Where to set CORS headers? 

### ISSUE THREAD

**Issue by bgyss** [go-kit/kit#364]
Is there a recommended place to set CORS headers for every response in go-kit? My initial inclination would be to fork and set them inside the ServeHTTP function in transport/http/server.go with some changes that resemble the following:

```
func (s *MyServer) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
    if origin := req.Header.Get("Origin"); origin != "" {
        rw.Header().Set("Access-Control-Allow-Origin", origin)
        rw.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS, PUT, DELETE")
        rw.Header().Set("Access-Control-Allow-Headers",
            "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
    }
    // Stop here if its Preflighted OPTIONS request
    if req.Method == "OPTIONS" {
        return
    }
    // Lets Gorilla work
    s.r.ServeHTTP(rw, req)
}
```

I would prefer to avoid having to determine the origin separately in every decode request, but I can't really seem to find a way to access the http request earlier in the request/response chain. Also, I'm not sure if there's an appropriate way to do this via middleware.

If anyone else needs code that does this in the ServeHTTP function I can submit a pull request as well.

**Comment by groob** [comment]
```
// cors headers
func accessControl(h http.Handler) http.Handler {
       	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
       		w.Header().Set("Access-Control-Allow-Origin", "*")
       		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
       		w.Header().Set("Access-Control-Allow-Headers", "Origin, Content-Type")

       		if r.Method == "OPTIONS" {
       			return
       		}

       		h.ServeHTTP(w, r)
       	})
}```

Use a decorator.

**Comment by peterbourgon** [comment]
@bgyss Does that answer your question?

**Comment by bgyss** [comment]
@peterbourgon Yes, I was able to implement the headers yesterday.

@groob Thanks!
