### ISSUE TITLE
Is there a way to abort from a before handler func with a custom status code and message? 

### ISSUE THREAD

**Issue by jesselurie** [go-kit/kit#377]

**Comment by basvanbeek** [comment]
Strictly speaking no. The before handler functions allow you to inspect the request payload, headers, etc. and annotate items into context based on this raw data. The first spot where you can abort the operation will then be the decode request function of the individual service method. 

You could build a before func that stores the need to abort the operation into context and then have the decode function return an error based on finding such context variable.

By creating a custom ErrorEncoder you can return the required custom status code and message.

**Comment by peterbourgon** [comment]
Just echoing @basvanbeek, the before and after funcs are meant to be used purely to move information from one domain to another. In the case of a before RequestFunc in a server, moving information from the http.Request to the context. You should perform your validation, including erroring out if necessary, in the Decode stage via the decodeRequestFunc, or in the business logic itself.
