### ISSUE TITLE
Is it possible to have a factory abstraction for metrics?

### ISSUE THREAD

**Issue by yurishkuro** [go-kit/kit#378]
Currently go-kit only defines interfaces for stats objects like Counter/Gauge/etc. The creation of those objects seems to be delegated to concrete implementations, with the only exception being the `Provider` interface, which only allows a single string name for stats.

Is it possible to define a generic tag-based factory, e.g. like this one:

``` go
// Factory creates new metrics
type Factory interface {
    CreateCounter(name string, tags map[string]string) Counter
    CreateTimer(name string, tags map[string]string) Timer
    CreateGauge(name string, tags map[string]string) Gauge
}
```

?

The reason for this is that our tracing library https://github.com/uber/jaeger-client-go defines a [whole set of metrics](https://github.com/uber/jaeger-client-go/blob/master/metrics.go#L31), and it would be quite cumbersome for a user of this library to construct all these metrics manually when binding to a particular metrics implementation. On the other hand, if the user simply needed to provide the above factory interface, our library would create all the metrics it needs.

I realize that not all backends support tags, but many good ones do, and those that don't (e.g. statsd) can still come up with a unique metric name given a `name+tags` combination.

**Comment by peterbourgon** [comment]
The existing provider implementation is a bit of a one off, and I wouldn't like to see it enshrined as a best practice or duplicated in another form. Indeed, I hope to delete it in the long term, as it's only consumer (Gizmo) will hopefully move to a different model. 

 What do you think about turning the problem on inside, and having your framework except metric references to which a record things? That is, not creating the metrics, but treating them as dependencies, which I think is the right model anyway. Does this work? If not, can you say a bit more about your architecture?

**Comment by yurishkuro** [comment]
Injecting individual metrics into the framework is currently the only way with go-kit. I would not say that it's any more valid IOC approach than injecting an [abstract factory](https://en.wikipedia.org/wiki/Abstract_factory_pattern). There are two problems with injecting individual metrics:
  1. As I mentioned above, our library uses a whole set of metrics, specifically 17 of them. That is a lot of overhead and boilerplate code that the user of the library needs to write just to wire up the library (it's an OpenTracing tracer, the wiring is meant to be just a few lines of code). With a factory approach, wiring the metrics is one line.
    * Furthermore, we're interested in using go-kit not just in the client-facing library, but in our server side components as well, and those have a lot more metrics than 17.
  1. If the user of the library is responsible for creating and injecting individual metrics, it's the user who must give the names to those metrics. Now imagine the same thing needs to be done in 100s of microservices in different programming languages (as is the case at Uber). This creates massive opportunity for metric names getting completely out of whack across services & languages, making standardized dashboards impossible. In contrast, with the factory approach it's the library's business how to name the metrics, and the library implementor takes care of those names being consistent with similar libraries in other languages.
  1. There are situations where the metric name is not known ahead of time. For example, in case of a distributed tracing collector, I may want to emit a metric with service name as one of the tags, to monitor how much traffic I am getting per service. In this case the abstract factory is practically the only way to make the collector independent of the concrete metrics backend, because it would need to determine the final metric name+tags at runtime.

I am curious if the objection to the abstract factory pattern is philosophical or if there are practical difficulties implementing the factory for the supported backends, due to limitations in their capabilities. I can certainly see how such factory can be implemented for stats, even though it requires a not so pretty concatenations of the tags into a path-based string.

I can also see an argument that we could implement the factory pattern ourselves outside of go-kit (which we may end up doing anyway), but it seems like a useful abstraction to have directly in the go-kit. I am willing to do a PR for that.

**Comment by peterbourgon** [comment]
The objection is both philosophical and practical. Philosophically I am opposed to anything other than so-called declarative composition as a means of construction. Components or patterns that introduce indirection to object creation make codebases harder to understand as a rule, and it's very important to me that Go kit do the opposite.

Still, I'm not completely unpersuadable; if something important for Go kit can only be solved with indirection, then I'm open to it. And I think your use case is absolutely important. But that brings us to the practical objection: while we can reasonably abstract [usage patterns](https://github.com/go-kit/kit/blob/18eaaed6e45c7296fa93dad20ffbcc306146cd98/metrics/metrics.go) over pretty much any instrumentation system, we can't reasonably abstract construction. You propose name + tags, but Prometheus (for example) has additional hard per-metric requirements for namespace, subsystem, and help text. Can you think of a way to structure the Factory to accommodate that sort of variance?

**Comment by peterbourgon** [comment]
And to respond to your points specifically, which may shed more light on the philosophical issues at play here...

> As I mentioned above, our library uses a whole set of metrics, specifically 17 of them. That is a lot of overhead and boilerplate code that the user of the library needs to write just to wire up the library.

I just want to acknowledge that it is indeed more work, and I'm keen to make it easier — to a point :) It is a first-order design goal of Go kit to make constructing and wiring up the object graph of a service an explicit and manual process, in the func main (or equivalent) of the service executable. Just like an imported library doesn't have the right to register its own flags in the flagset of a binary, neither does it have the right to register its own metrics in the metricset of a binary. Rather, the owner of the func main should construct those {flags, metrics} and pass them, as dependencies, to the components that need them. — At least, this is the Go kit philosophy.

> If the user of the library is responsible for creating and injecting individual metrics, it's the user who must give the names to those metrics. Now imagine the same thing needs to be done in 100s of microservices in different programming languages (as is the case at Uber). This creates massive opportunity for metric names getting completely out of whack across services & languages, making standardized dashboards impossible.

The idea is and has always been for e.g. Uber to create an Uber kit, wrapping Go kit, and declaring and wiring up the common metrics, specifically bound to the metrics system(s) in use at Uber. Then, Uber's microservices shall import and use Uber kit. No factory necessary.

> There are situations where the metric name is not known ahead of time. For example, in case of a distributed tracing collector, I may want to emit a metric with service name as one of the tags, to monitor how much traffic I am getting per service.

I cannot see how this is anything other than a bad idea. Instrumentation (at least as I understand it) is a part of the contract of a service, as important as the business logic. How can you test for and validate instrumentation if it's being generated dynamically?

**Comment by yurishkuro** [comment]
Thanks for the feedback.

I don't know yet which factory API is appropriate to deal with the practical concerns. I'd need to investigate Prometheus API a bit more. On the surface, it seems to make unnecessary assumptions about the structure of the user system by requiring "namespace" and "subsystem" - the user may not even have such concepts, and those users who do have them could easily express them as tags. But again, I'd need to read more no Prometheus for the reasons of this design.

The dumb approach for the factory is to have a superset of parameters required by all implementations, which is meh. Possibly some parameters could be the parameters to the constructor of the factory object itself.

I think I'll end up defining factories in our own shared library, with bindings for the metrics backend that go-kit supports. Then I will have a better answer about the factory API.

We do seem to have a philosophical differences about the granularity of the dependencies. Forcing the users of a library to construct 17 metrics objects seems completely excessive to me. Reminds me of the common Java flaw where I had to write about 200 lines of code just to implement a dumbest http server, because everything was configurable and _had_ to be configured. We've seen over and over that frameworks that require less configurations always win. Doesn't mean they cannot be configured, just that they don't _have_ to be. Go itself, as a language, or at least as manifested by its std lib, follows the principle that the minimal default configuration should "just work". I want to keep our libs & components just as simple to use - give them am empty Config struct and they'd still work.

On the last point of dynamic metric names, bad idea or not, it's certainly a reality in a number of Uber infra systems. For example, we have various routing components that emit metrics where the name of the caller and the server are tags in a counter. The router does not know upfront the names of the callers/servers, so it creates those counters at runtime as needed. Another example is our distributed tracing system Jaeger, which emits metrics about the number of tracing spans received from each microservice, creating counters dynamically. This does present a small risk of unbounded cardinality for a tag when players misbehave, but our metrics system itself has defenses against that. That risk is well worth the benefits for observability where we can quickly identify which services are creating excessive traffic. And in practice the risk is negligible because the service names are finite.

I will try defining the factories in our own repo and post an update here.

**Comment by yurishkuro** [comment]
fwiw, in [Prometheus API](https://github.com/prometheus/client_golang/blob/8aae34f3ffc9a93c75efeaad87bb192aa7750900/prometheus/metric.go#L62) only the "name" of the metric seems to be required
```go
type Opts struct {
	// Namespace, Subsystem, and Name are components of the fully-qualified
	// name of the Metric (created by joining these components with
	// "_"). Only Name is mandatory, the others merely help structuring the
	// name. Note that the fully-qualified name of the metric must be a
	// valid Prometheus metric name.
	Namespace string
	Subsystem string
	Name      string
```

**Comment by peterbourgon** [comment]
Thanks for the comments, I've been thinking about them for the past few days. One point of clarification:

> On the last point of dynamic metric names, bad idea or not, it's certainly a reality in a number of Uber infra systems. For example, we have various routing components that emit metrics where the name of the caller and the server are tags in a counter. The router does not know upfront the names of the callers/servers, so it creates those counters at runtime as needed. Another example is our distributed tracing system Jaeger, which emits metrics about the number of tracing spans received from each microservice, creating counters dynamically. This does present a small risk of unbounded cardinality for a tag when players misbehave, but our metrics system itself has defenses against that. 

I want to draw a distinction between _metrics_ e.g. http_request_duration and the (using Prometheus terminology) _labelset_ of those metrics e.g. method, path, status_code. In Go kit world we want the user to statically define the former, while leaving the code to dynamically set the latter, with some bounded cardinality. A unique combination of metric and labelset constitutes an independent timeseries.

So my thought would be to have an e.g. tracing framework to take a small number of metrics as dependencies e.g. trace_duration, trace_errors – with some predefined label keys e.g. service, method. And then the framework would record observations with the relevant label values. Each unique combination e.g. trace_duration{service=foosvc, method=update_foo} is not a unique _counter_ per se, but does resolve to a unique timeseries.

Does this help shape the design?

**Comment by yurishkuro** [comment]
Do you mean using `With(labelValues ...string)` methods to pass the labels? I actually tend to consider those as different counters == metrics == time series. But yes, that works fine for my use case 3 "~~metric~~ time series name is not known ahead of time".

**Comment by peterbourgon** [comment]
Yes; for me metric is the concrete metrics.{Counter, Gauge, Histogram}.

**Comment by willfaught** [comment]
FWIW, I've hit this issue as well when making middleware that creates metrics for each endpoint. I've had to restort to passing in stuff like `func(endpointName string) metrics.Counter` for the middleware to use.

**Comment by peterbourgon** [comment]
That's fair. I've also hit some speedbumps when instrumenting certain types of services. I'd be curious to see a more fully-fleshed out proposal for a registry.

**Comment by yurishkuro** [comment]
@peterbourgon my original Factory proposal still seems to be a reasonable approach. There's always going to be a compromise between going for lower common denominator (stats), or the most elaborate construction (prometheus with is subsystem, namespace, and what not) for the factory method signatures. My factory had something in between, name + tags, which I think is the most that the end user code can provide. That is, the additional dimensions like subsystem/namespace can be provided to the factory constructor.

```
// Factory creates new metrics
type Factory interface {
	Counter(name string, tags map[string]string) Counter
	Gauge(name string, tags map[string]string) Gauge
	Histogram(name string, tags map[string]string) Histogram

	// Namespace returns a nested metrics factory.
	Namespace(name string, tags map[string]string) Factory
}
```

## Implementation considerations

### statsd

The factory can be configured with a parameter on how to deal with tags:
  * it can drop/ignore the tags (acceptable depending on usage)
  * it can encode the tags as a segment, e.g. 
    * `tags.sort(_.key).map(t => "${t.key}:${t.val}").join("-")`

The `Namespace()` function is natural for statsd, just append the name to the current metric/factory name.

### prometheus

The subsystem has to be fixed for a given instance of the factory, given as constructor arg.

**Comment by willfaught** [comment]
While making something basic like my factory func above is simple and fine, it gets to be a lot when needing to make several kinds of metrics at once:

```go
func MyMiddleware(c func(string) metrics.Counter, h func(string) metrics.Histogram, g func(string) metrics.Gauge) endpoint.Middleware {
    // ...
}
```

After typing that a lot, you're probably going to end up writing something like @yurishkuro's Factory for your own use, although maybe it would just be a struct instead of an interface.

Even if go-kit didn't impl Factory for every backing service, maybe it's worthwhile to include just the interface as a convenience for impl yourself, and as guidance for what to do.

**Comment by yurishkuro** [comment]
@willfaught the reason it's an interface is because, in your example, `MyMiddleware` doesn't care which backend implements the metrics, it just needs a simple way of creating them with name (+tags). If you're developing an actual application, you know the backend and can do with a struct, but when you write a shared library (like this middleware example seems to be), you want it to work with many metrics backends. 

This repo has something similar, in the [provider](https://github.com/go-kit/kit/blob/master/metrics/provider/provider.go#L37) package, but it doesn't support tags.

**Comment by willfaught** [comment]
Right. I just meant that if you were doing it yourself, you'd know the backing service, there would be no need for an interface; but an interface would be needed for a general-purpose abstraction.

**Comment by peterbourgon** [comment]
We basically have this now.
