### ISSUE TITLE
Re-evaluate transport contexts

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#381]
gRPC and now HTTP bring contexts along with each request. So it may not be necessary to construct the respective transports with a single parent context. Look in to refactoring those packages. Also, audit the other transports for the same work.

**Comment by peterbourgon** [comment]
It may be good to provide two implementations of the HTTP transport for pre- and post-1.7.

**Comment by basvanbeek** [comment]
Since we landed at 1.7 as our minimum supported version I have taken the liberty to update the HTTP Transport to use the per request context. See #480.

gRPC since today also used its own per request context and does not provide a server wide context anymore

**Comment by basvanbeek** [comment]
closed by updates in #480
