### ISSUE TITLE
can go get github.com/go-kit/kit work?

### ISSUE THREAD

**Issue by skeleton1231** [go-kit/kit#382]
I am first time to learn go and use go-kit, such a complicated tool.  can use go get github.com/go-kit/kit  to install and run the example??  @peterbourgon

**Comment by peterbourgon** [comment]
Please see [the stringsvc example](http://gokit.io/examples/stringsvc.html) to get started. Then, move on to the e.g. addsvc example: `go get github.com/go-kit/kit/examples/addsvc/cmd/addsvc`. Hope this helps!
