### ISSUE TITLE
addsvcpb no longer builds due to breaking change in grpc

### ISSUE THREAD

**Issue by hasAdamr** [go-kit/kit#386]
```
$ go build ./examples/addsvc/...
# github.com/go-kit/kit/examples/addsvc/pb
examples/addsvc/pb/addsvc.pb.go:96: undefined: grpc.SupportPackageIsVersion3
```

Lightstep is also broken but I see an issue already created there. https://github.com/lightstep/lightstep-tracer-go/issues/57

**Comment by peterbourgon** [comment]
Should be fixed now. Please feel free to re-open if it's not.
