### ISSUE TITLE
run stringsvc2 go run main.go but show errors, someone can help?

### ISSUE THREAD

**Issue by skeleton1231** [go-kit/kit#390]
➜  stringsvc2 git:(master) ✗ ls -l
total 40
-rw-r--r--  1 huanghaitao  staff   944 10 28 22:15 instrumenting.go
-rw-r--r--  1 huanghaitao  staff   679 10 28 22:15 logging.go
-rw-r--r--  1 huanghaitao  staff  1764 10 28 22:15 main.go
-rw-r--r--  1 huanghaitao  staff   504 10 28 22:15 service.go
-rw-r--r--  1 huanghaitao  staff  1515 10 28 22:15 transport.go
➜  stringsvc2 git:(master) ✗ go run main.go 
# command-line-arguments
./main.go:39: undefined: StringService
./main.go:40: undefined: stringService
./main.go:41: undefined: loggingMiddleware
./main.go:42: undefined: instrumentingMiddleware
./main.go:46: undefined: makeUppercaseEndpoint
./main.go:47: undefined: decodeUppercaseRequest
./main.go:48: undefined: encodeResponse
./main.go:53: undefined: makeCountEndpoint
./main.go:54: undefined: decodeCountRequest
./main.go:55: undefined: encodeResponse
./main.go:55: too many errors
➜  stringsvc2 git:(master) ✗ 

@peterbourgon

**Comment by basvanbeek** [comment]
that is correct. since those items are defined outside of `main.go`

please try:
```
go build
./stringsvc2
```

**Comment by skeleton1231** [comment]
thanks a lot!

**Comment by noelzubin** [comment]
`go run .`
