### ISSUE TITLE
Reset bold font

### ISSUE THREAD

**Issue by serge-v** [go-kit/kit#397]
https://github.com/go-kit/kit/blob/master/log/term/colorlogger.go#L45 needs code 22 also to reset bold font `resetColorBytes = []byte("\x1b[39;49;22m")`

**Comment by ChrisHines** [comment]
Thanks for the suggestion. The color logger (as currently written) doesn't have any code to enable bold font. Do you still think code 22 is necessary? Do you have example code that shows when this addition is needed?

**Comment by serge-v** [comment]
Actually this loop https://github.com/go-kit/kit/blob/master/log/term/colorlogger.go#L61 enables bold attribute for fonts (";1m"). So it should be reset.

**Comment by ChrisHines** [comment]
OK. Thanks for clarifying. Would you like to submit a PR for this fix?
