### ISSUE TITLE
Create a gokit channel under Gophers' slack community

### ISSUE THREAD

**Issue by waitingkuo** [go-kit/kit#40]
There're lots of go discussion/channels in [gophers' slack community](http://gophers.slack.com)
Should we create a gokit there?

**Comment by dgryski** [comment]
Given that there's already an official IRC channel on freenode, it makes sense to not fragment the discussions.

**Comment by peterbourgon** [comment]
Thanks for the note, @waitingkuo. +1 to not fragmenting, but also +1 to actually having discussion :) The freenode channel is basically dead. Let me hang out on Slack for awhile and see how it feels.

**Comment by harlow** [comment]
+1 to gophers slack channel

**Comment by ChrisHines** [comment]
+1 to slack. I don't use it often, but I at least have an account that works and I would go there more given a good reason. With IRC I can never figure out how to get a non-guest freenode account setup.

**Comment by peterbourgon** [comment]
I've created #go-kit on http://gophers.slack.com, we'll see how it goes for the next few days...

**Comment by ChrisHines** [comment]
This seems successful to me.

**Comment by peterbourgon** [comment]
Yep. Updated topic in Freenode #go-nuts; will change README in a second...

**Comment by peterbourgon** [comment]
And done.
