### ISSUE TITLE
Request method specific handlers

### ISSUE THREAD

**Issue by bndw** [go-kit/kit#402]
After following the [stringsvc tutorial](https://gokit.io/examples/stringsvc.html), it's unclear how to define distinct handlers for different verbs on the same resource. Specifically, I want to handle both `GET` and `POST` requests in different handlers but am unsure of how to idiomatically achieve this.

```go
uppercaseHandler := httptransport.NewServer(
	ctx,
	makeUppercaseEndpoint(svc),
	decodeUppercaseRequest,
	encodeResponse,
)

http.Handle("/uppercase", uppercaseHandler)
```
Given the above example code, one approach could use the `request.Method` in `decodeUppercaseRequest` to decode the correct request type. `makeUppercaseEndpoint` could switch on a type assertion, returning the correct handler, but I'm curious if there is a better approach.

**Comment by xla** [comment]
You would want a a muxer to address that concern a commonly used piece of software for that is [gorilla/mux](https://github.com/gorilla/mux). With the help of that you'd create two distinct handlers for the `GET` and `POST` verbs.

**Comment by peterbourgon** [comment]
For an example, see [profilesvc transport.go](https://github.com/go-kit/kit/blob/c369f674159e02f22ca276d8503027af2bc27246/examples/profilesvc/transport.go#L47-L53). 

Hopefully this answers the question; please re-open if you have more inquiries! :)

**Comment by bndw** [comment]
That's exactly what I'm after, thank you kindly @xla  @peterbourgon

**Comment by amonaco** [comment]
So you need to use another library (gorilla/mux) for this? Awesome!
