### ISSUE TITLE
Counter/Gauge/Histogram.With not documented clearly

### ISSUE THREAD

**Issue by willfaught** [go-kit/kit#411]
Coming to this documentation with no metrics exposure before this, it's not clear what label values are. They kinda seemed like a namespace prefix at first, but that turns out not to be correct. One or two lines would save newbies a lot of time.

**Comment by peterbourgon** [comment]
Can you suggest something? Would it be appropriate to place it in the package-level documentation for package metrics?

**Comment by willfaught** [comment]
I'm not sure I understand it even now. They're some kind of tags that combine with the metric name into a set that identifies a unique timeseries, but only for some impls like Prometheus? Is that right?

Any doc at all would be an improvement. I suppose if you doc the With methods you should doc the Add/Set/Observe methods too, so package doc would be less work.

**Comment by willfaught** [comment]
It also isn't clear from the doc that some With impls aren't meaningful, like for statsd. Does it make sense to separate With into its own interface that you can check for with type assertions that the impls can opt into?

**Comment by peterbourgon** [comment]
Thanks. This feedback is already very helpful. I'll take it from here.
