### ISSUE TITLE
log: often feeling a need for log.Fatal

### ISSUE THREAD

**Issue by ahmetalpbalkan** [go-kit/kit#412]
When I use go-kit logger to write small applications/micro-services that have structured logging, I often find myself writing this:

```go
	if err != nil {
		log.Log("msg", "failed to read config file", "error", err)
		os.Exit(1)
	}
```

This is often when I want to fail-fast, such as a wrong configuration value or a fatal failure that I'd rather exit the process with a non-zero exit code right away.

If there was a `log.Fatal(keyvals ...interface{})`  in addition to `log.Log(keyvals ...interface{})` I wouldn't worry about writing `os.Exit(1)`.

Also, having a `log.Fatal` would also __reduce the programmer-errors__: When I start writing `log.Log(...`, I can easily forget adding the `os.Exit(1)` part (this happened me once IRL).

**Comment by ChrisHines** [comment]
Thanks for the feedback. We are very happy with and committed to the `log.Logger` interface only having a single `Log` method. We feel that it provides the most general and composable interface for structured logging. I don't see us adding a Fatal method to the API.

Writing a helper function that logs some keyvals and then call os.Exit seems like a fine solution to me if your application calls for it.

**Comment by ahmetalpbalkan** [comment]
Understood. Thank you.
