### ISSUE TITLE
add a concurrent example to go-kit/log to avoid confusion in the documentation

### ISSUE THREAD

**Issue by hydroflame** [go-kit/kit#415]

**Comment by peterbourgon** [comment]
I don't understand. Can you clarify?

**Comment by ChrisHines** [comment]
@peterbourgon I got this one. @hydroflame pointed out to me on Slack that when you read the package docs in godoc the last section is about concurrent safety. That is followed immediately by the package level examples, none of which demonstrate using the concurrent safety feature just discussed. The request is to add an example that shows the use of the concurrent safety features. I asked @hydroflame to file an issue to remind me about it.

**Comment by ChrisHines** [comment]
Addressed by #429.
