### ISSUE TITLE
log: Log does not play well with errcheck

### ISSUE THREAD

**Issue by ahmetalpbalkan** [go-kit/kit#418]
The popular [`errcheck`](https://github.com/kisielk/errcheck) utility shows the go-kit Log() lines as errors as the Log function actually returns an error.

```
type Logger interface {
	Log(keyvals ...interface{}) error
}
```

Is this planned to change? I wonder the motive behind returning an error here. I am guessing nobody actually takes action on these errors returned from Log() calls either.

**Comment by ChrisHines** [comment]
@ahmetalpbalkan We do not plan to change the Logger interface. We had a lengthy discussion on this topic in #164. I plan to document this more explicitly (hopefully soon), which is #346.

**Comment by peterbourgon** [comment]
Hopefully that answers the question! :)
