### ISSUE TITLE
access logging vs error logging

### ISSUE THREAD

**Issue by xh3b4sd** [go-kit/kit#419]
Here I want to ask a question to get a more clear picture about certain logging approaches. What we currently have is the ability to emit access logs and error logs separately. I would like to question why that is. I think that what I want to do can be accomplished right now, but it would be unnecessarily complicated and would not make code any better. 

When some microservice is running and receives traffic, it does its job and emits a log line for each accessed endpoint. In case an error happens, an additional log line is emitted for the error. I wonder why there is no way to enrich the access log line with the actual error to only have one log line. It somehow feels wrong to have the information about the request and its resulting error separated. 

Thinking back it made probably sense to separate error logs and access logs. As I see it today, especially with structured logging approaches and certain logging infrastructure tools, I think it might make more sense to have access logs and error information combined. What I want to do is writing well structured logs to stdout and let something like an ELK stack do the magic. I do not want to have different files to write logs to. I want to have a direct connection between request URLs, response status codes and eventual error information. Having access logs eventually enriched with error information would also result in some sort of performance optimization. That is, less disk space, less CPU time, less latency and more semantic connections between requests and resulting errors out o the box. 

I would like to hear opinions on this topic. Thanks for listening.

**Comment by peterbourgon** [comment]
> When some microservice is running and receives traffic, it does its job and emits a log line for each accessed endpoint.

I would elide this; it is probably better served by instrumentation.

> In case an error happens, an additional log line is emitted for the error.

If the error is actionable, this is fine. If the error is not really actionable, it's also better served by instrumentation.

In general, your services should log as little as possible. Logging each request or error, i.e. logging stuff proportional to load, is probably a bad idea. See [Logging v instrumentation](https://peter.bourgon.org/blog/2016/02/07/logging-v-instrumentation.html) and [Instrumentation v. log aggregation](http://gokit.io/blog/).

**Comment by xh3b4sd** [comment]
So you say that one should not emit one log line per request, is that right? I understand you suggest to rather emit an increment on some metrics counter. The question is then how these access and error events can be combined to increment a labeled metric. Or what kind of labels do you suggest to emit in case of access and error? Do I need to deal with two different counters here? Then I would like to have one counter which contains labels about the response status code, about the error domain in case an error was emitted, about the HTTP method in case of HTTP transport and about the endpoint name. Here the question would be how to organize the code, because in case of an error not all information are available. In the place where other information are available the error is missing in case there is one. So it would be cool to have a counter labeled like the following code shows, to create dashboards that shows me which endpoint has a certain error rate. 

```go
var endpointTotal = prometheus.NewCounterVec(
	prometheus.CounterOpts{
		Name: "endpoint_total",
		Help: "Number of times we have execute the HTTP handler of an endpoint",
	},
	[]string{"code", "error_domain", "method", "name"},
)
```

So I would like to be able to answer the question of how stable certain endpoints are during encoding requests, for instance. Currently I only see to fiddle with the context and emit different metrics on different places, which makes the aggregation rather complicated.

**Comment by peterbourgon** [comment]
> So you say that one should not emit one log line per request, is that right?

In general, yes.

> The question is then how these access and error events can be combined to increment a labeled metric. Or what kind of labels do you suggest to emit in case of access and error? Do I need to deal with two different counters here?

If you're using Prometheus, I think a good default practice is to have something like the following example:

```go
requestDuration := prometheus.NewHistogramVec(prometheus.HistogramOpts{
    Name:    "request_duration_seconds",
    Help:    "Request duration, by method, path, and status code.",
    Buckets: prometheus.DefBuckets,
}, []string{"method", "path", "status_code"})

func instrumentingMiddleware(next http.Handler) http.Handler {
    return http.HandlerFunc(func (w http.ResponseWriter, r *http.Request) {

        iw := interceptingWriter{w, http.StatusOK}
        defer func(begin time.Time) {
            requestDuration.WithLabelValues(
                r.Method,
                r.URL.Path,
                strconv.Itoa(iw.statusCode),
            ).Observe(time.Since(begin).Seconds())
        }(time.Now())
        next(iw, r)

    })
}
```

The histogram automatically provides a _count metric, so you can do all of your rate calculation from that alone. And you can deduce class/domain/type of error based on status_code. For example, decode errors should be 4xx.

You can adapt this example to be a service middleware, if you like. You just have to get transport-domain information into the context at the transport stage, and extract it again once it's in the service-domain. You can do that with e.g. [transport/http.PopulateRequestContext](https://godoc.org/github.com/go-kit/kit/transport/http#PopulateRequestContext), or you could write your own helper of course.

**Comment by xh3b4sd** [comment]
Is there documentation about the recommendation of not having access logs? I already hear lots of people complaining to not see incoming requests when locking at the logs.

**Comment by peterbourgon** [comment]
I've linked two blog articles about the rationale in the previous comment. But no doubt it will take some institutional adjustment, for those who are used to verbose access logs.

**Comment by peterbourgon** [comment]
Hopefully that answers the question! :)
