### ISSUE TITLE
log: default StdlibAdapter file key should be "caller"

### ISSUE THREAD

**Issue by willfaught** [go-kit/kit#432]
Not "file". To match the naming of DefaultCaller/UTC.

Open to a PR?

**Comment by peterbourgon** [comment]
Hmm, on a first pass, I don't agree. File is considerably less ambiguous; caller could imply a lot of things. But I'm open to being persuaded. @ChrisHines, any opinion?

**Comment by willfaught** [comment]
Seems to me like the nomenclature should match since they both produce "file:line", whatever the term is. I'm fine with DefaultFile/UTC too.

**Comment by willfaught** [comment]
Although it's not just the file, it's also the line, so DefaultFile/UTC might be unclear; at least DefualtCaller/UTC implies as much info as file/line.

**Comment by ChrisHines** [comment]
I would like to note that only StdlibAdapter actually encodes the key string (and provides a default of "file"). The key of "caller" only appears in examples and tests. I don't think it is a big deal, but if forced to choose I would go with consistency and would agree with @willfaught.

**Comment by peterbourgon** [comment]
Oh, I see now. Yes, let's be consistent. I'm down with "caller".
