### ISSUE TITLE
EncodeJSONResponse does not account for http.StatusNoContent

### ISSUE THREAD

**Issue by groob** [go-kit/kit#435]
The [current](https://github.com/go-kit/kit/blob/44df43eae441b8197be13e2004ccdf535e24b277/transport/http/server.go#L149-L154) implementation of `EncodeJSONResponse` always writes an HTTP response body. 
When the status should be `http.StatusNoContent`, there shouldn't be any response body. 

In my own code I've done a check like this:

```
    if e, ok := response.(statusCoder); ok {
        w.WriteHeader(e.status())
        if e.status() == http.StatusNoContent {
            return nil
        }
    }
```

Should the [EncodeJSONResponse](https://github.com/go-kit/kit/blob/44df43eae441b8197be13e2004ccdf535e24b277/transport/http/server.go#L142) have a check for 204 responses? I can send a PR but wanted to make sure it's wanted first.

**Comment by basvanbeek** [comment]
I personally would expect it to play nice with expectations so +1 from me

**Comment by peterbourgon** [comment]
SGTM!
