### ISSUE TITLE
invalid url for gRPC in docs

### ISSUE THREAD

**Issue by kingishb** [go-kit/kit#445]
(Cross post from GoKit's docs project -- see: PR https://github.com/go-kit/go-kit.github.io/pull/2)

Hi there!

When I followed https://grpc.io from the docs there was a name mismatch error [1].
It appears the new url is http://www.grpc.io [2].

[1]
<img width="997" alt="cd964f56-dfdd-11e6-9b47-3adf6ffa76d6" src="https://cloud.githubusercontent.com/assets/3827393/22176842/965ee978-dfe0-11e6-9def-2b5c8842801d.png">

[2] https://github.com/grpc/

**Comment by peterbourgon** [comment]
Whoa, that's crazy! Okay. Thanks.

**Comment by peterbourgon** [comment]
Fixed.
