### ISSUE TITLE
transport/grpc.NewClient assumes service name has prefix "pb"

### ISSUE THREAD

**Issue by willfaught** [go-kit/kit#447]
It's possible for a proto file to have something like this:

```proto
option go_package = "pb";

package github_com.mycompany.myrepo.myservice.pb;
```

in which case the Go package is pb but the GRPC namespace is github_com.mycompany.myrepo.myservice.pb.

There should at least be an option to override the pb default.

**Comment by basvanbeek** [comment]
The default in Go kit is for the GRPC namespace to be pb. However it is perfectly fine to alter the namespace and do something like:

```
kitgrpc.NewClient(
    conn, 
    "github_com.mycompany.myrepo.myservice.pb.MyService",
    "MyMethod",
     ...,
)
```

**Comment by willfaught** [comment]
You're right, my bad! I missed the period condition. Thanks.

**Comment by terinjokes** [comment]
If you don't provide a "package" in your protobuf file, your endpoints won't pre prefixed at all. Enforcing a default of "pb" in the grpc transport that I can't opt out of means I now can't call this service.

**Comment by terinjokes** [comment]
In my fork, I've added a ClientOption to revert the auto-prefixing. Happy to send a PR, but I think removing, or modifying, the prefixing functionality makes more sense.

**Comment by terinjokes** [comment]
To wrap up the discussion here: with #524 merged, go-kit will no longer autoprefix the "pb" package name. Of course `github_com.mycompany.myrepo.myservice.pb.MyService` is still a valid input.
