### ISSUE TITLE
is OSGi on the agenda?

### ISSUE THREAD

**Issue by vimalk78** [go-kit/kit#452]
i find the idea of go-kit to be very interesting. i hope to be able to contribute to it in the future.

i have a question, not sure if this is the right place to ask, os is a right question.

is implementing something like OSGi  on your agenda?

able to define a component, with a defined interface and  be able to import other such components in a component. 

start/stop a component at runtime without restart. (go 1.8 supports plugins.)

do you have any thoughts on this.

thanks,

**Comment by ChrisHines** [comment]
Based on the non-goals stated in the README, this seems out of scope to me. It seems to fall under the last non-goal:

#### Non-goals

- Supporting messaging patterns other than RPC (for now) — e.g. MPI, pub/sub, CQRS, etc.
- Re-implementing functionality that can be provided by adapting existing software
- Having opinions on operational concerns: deployment, configuration, process supervision, orchestration, etc.

**Comment by peterbourgon** [comment]
Definitely not :)
