### ISSUE TITLE
generic.Counter.With() loses the Name

### ISSUE THREAD

**Issue by yurishkuro** [go-kit/kit#455]
The With() method returns a new counter with blank name, is that intentional? The behavior was counter-intuitive to me.

```
// With implements Counter.
func (c *Counter) With(labelValues ...string) metrics.Counter {
	return &Counter{
		bits: atomic.LoadUint64(&c.bits),
		lvs:  c.lvs.With(labelValues...),
	}
}
```

**Comment by groob** [comment]
Are you passing a `name` key/value  to `With` or just calling `With()` with no args?

**Comment by yurishkuro** [comment]
I am calling With() with *other* tags, which are not part of the metric name but are additional dimensions for aggregations.

**Comment by peterbourgon** [comment]
Yep, on first glance this is probably a bug with all 3 generic.Metrics.
