### ISSUE TITLE
Are there plans to integrate middleware like gRPC REST gateway into go-kit?

### ISSUE THREAD

**Issue by mohanraj-r** [go-kit/kit#462]
Cool project here!

I am looking to offer both gRPC and REST/JSON support from the same code base and was looking to go-kit for that. I like the abstractions offered by go-kit. But it looks like support for each transport has to be written and maintained separately. It would be cool if go-kit could allowed me to define a service abstraction and then allowed to support multiple transports from the same code base with minimal code duplication. 

* In that regard are there any plans to integrate efforts like [grpc-ecosystem/grpc-gateway: gRPC to JSON proxy generator](https://github.com/grpc-ecosystem/grpc-gateway) into go-kit? 

* How possible is it in the current code base? How much of an effort would it be?

**Comment by peterbourgon** [comment]
Go kit already allows you to define a service abstraction and support multiple transports with almost no code duplication. You just have to wire up each transport to your service, with a single transport.Server component per transport, which Go kit provides. What, specifically, are you looking for?

Also, I don't understand what integration of grpc-gateway would look like. Can you say more?

**Comment by peterbourgon** [comment]
@mohanraj-r ping?
