### ISSUE TITLE
http: serveHTTP has asymmetrical `before` and `after` calls.

### ISSUE THREAD

**Issue by posener** [go-kit/kit#464]
In the [ServeHTTP function](https://github.com/go-kit/kit/blob/master/transport/http/server.go#L87), the `before` stack is called before the the decoding of the request and the `after` stack 
 is called *before* the encoding of the response.
This is not intuitive, am I missing anything here? I guess that fixing it will cause breaking of a lot of code.
Anyway, wanted to bring this up.
Thanks

**Comment by groob** [comment]
```
// ServerBefore functions are executed on the HTTP request object before the
// request is decoded.
func ServerBefore(before ...RequestFunc) ServerOption {
	return func(s *Server) { s.before = before }
}
```
I think the comment is pretty clear for how you might use a `ServerBefore` function. I typically use this option with a function that adds information to a context which will be used in handling of the request. 

Similarly, the comment on ServerAfter clarifies when the function will be called. 
```
// ServerAfter functions are executed on the HTTP response writer after the
// endpoint is invoked, but before anything is written to the client.
func ServerAfter(after ...ServerResponseFunc) ServerOption {
	return func(s *Server) { s.after = after }
}
```
Is there a specific problem you're trying to solve?

**Comment by posener** [comment]
Hi, thanks,
There is no specific problem, just a thought.

**Comment by peterbourgon** [comment]
It's _After_ the endpoint is invoked, but before sending the response to the client. There wouldn't be much point running user code after the response is sent! What could it do? (And we have the finalizer for that.)

**Comment by peterbourgon** [comment]
@posener Does that answer the question?

**Comment by posener** [comment]
@peterbourgon , thanks,
One might ask himself then why the before is called *before* the decode phase.
The only thing that triggered me to open this issue is that you need to read this function in order to understand how your hooks will work.
Thanks for the reply and the patience, and sorry for this ticket :-)

**Comment by peterbourgon** [comment]
Before and After are relative to invoking the endpoint, and agnostic to decoding the request and encoding the response.
