### ISSUE TITLE
Replace log.Context with log.With/WithPrefix?

### ISSUE THREAD

**Issue by willfaught** [go-kit/kit#474]
Given the stdlib discussion, is there any interest in replacing log.Context with log.With/WithPrefix?

**Comment by ChrisHines** [comment]
I plan to post a PR to do it very soon. That will let us evaluate the overall impact. It will probably break a lot of code, but the migration is pretty straight forward. Also, if we're going to do it, now is the time, before we publish v1.0.0.

**Comment by peterbourgon** [comment]
For the record I think this is a straightforward change and should probably make it into 1.0.0, barring any unforeseen weirdness.

**Comment by ChrisHines** [comment]
Agreed. My only concern is that unexporting `Context` somehow cripples a use case that needed to  store a `*Context`, but I don't think we will find that to be the case. I also think that the benefits of this change will turn out to be rather significant from a simplicity point of view. I'll document the pros and cons in the PR which I hope to have up tonight, or by the end of the weekend at the latest.

**Comment by willfaught** [comment]
Without knowing more about that particular use case for Context, I'm
guessing you could still make your own context type if you need one?

**Comment by ereOn** [comment]
I was reading at the various issues to try and find some tasks I could contribute to, I wonder why this task isn't closed.

It seems that #481 - which was merged - is all that is required for it and from the [comments](https://github.com/go-kit/kit/issues/427#issuecomment-284224104), #427 depends on this to be closed.

Is there anything left to do in that regard ? If so, what can we do to help ?

**Comment by ChrisHines** [comment]
Nope, just forgot to close it. Thanks for the ping.

**Comment by ereOn** [comment]
@ChrisHines I just deleted my comment as I realized a release was planned for tomorrow and thought this would be solved at that moment. You are welcome !
