### ISSUE TITLE
Allow multiple calls of http.ClientBefore() and http.ClientAfter() (for server as well)

### ISSUE THREAD

**Issue by gaplyk** [go-kit/kit#477]
Right now we are limited to one last call to set Before and After handlers.
It would be good to have ability to call them multiple times.

Changes are small and won't affect anyone logic.

**Comment by peterbourgon** [comment]
This already [happens in server](https://github.com/go-kit/kit/commit/c647984391f7d85a5d370767aed12dcba92653b1), I'm happy to take a PR for it to be the same way in client.

**Comment by basvanbeek** [comment]
already on that Peter :) as I'm working in transports anyway

**Comment by gaplyk** [comment]
Awesome
