### ISSUE TITLE
IsTerminal does not account for SyncLogger-encapsulated loggers

### ISSUE THREAD

**Issue by ereOn** [go-kit/kit#483]
The current implementation of IsTerminal does not properly work when stdout or stderr are used through a SyncLogger.

I came up with a really simple PR that addresses the problem in an elegant, 100% backwards-compatible manner. See #482.

**Comment by ChrisHines** [comment]
Good catch. Thanks for the issue and the PR. I'll try to review the PR soon.

**Comment by ereOn** [comment]
For what it's worth, I also manually tested **successfully** this PR and #484 **together** on both Windows (MSYS and `cmd.exe`) and OSX.
