### ISSUE TITLE
IsTerminal does not properly detect MSYS2 terminals on Windows.

### ISSUE THREAD

**Issue by ereOn** [go-kit/kit#484]
The current implementation of `IsTerminal` for Windows does only detect when a Go program is running in `cmd.exe` but not when it is running in `MSYS2` (that includes Git bash for Windows).

Adding support for such a terminal detection can easily be done ([see this C implementation](https://fossies.org/linux/vim/src/iscygpty.c)) and I am willing to do a PR for this if desired.

The change would be 100%-backward compatible and self-contained.

What do you think ?

**Comment by ereOn** [comment]
I added a PR (#485) that allows MSYS/Cygwin terminal detection, using the same strategy followed by Vim (the text editor).

Let me know what you think.

**Comment by ereOn** [comment]
@peterbourgon ping ?

**Comment by peterbourgon** [comment]
I have no Windows exposure or experience. @ChrisHines?

**Comment by ChrisHines** [comment]
I do have Windows here. I've been too busy the last couple of weeks to put time into this. I haven't forgotten and will get to it when I have time. Also, I want to sort out #482 first.

**Comment by ChrisHines** [comment]
Fixed by #501.

**Comment by ereOn** [comment]
@ChrisHines Isn't there a mistake ? I don't think this was addresses by #501 which only deals with passing through the file descriptor when a `SyncWriter` is used.

**Comment by ChrisHines** [comment]
Yeah, my mistake.

**Comment by ChrisHines** [comment]
Implemented in #485.
