### ISSUE TITLE
CloudWatch metrics package

### ISSUE THREAD

**Issue by cam-stitt** [go-kit/kit#489]
It would be nice to have a metrics implementation for CloudWatch. Ideally, we could utilise [aws-sdk-go](https://docs.aws.amazon.com/sdk-for-go/api/service/cloudwatch/). We should be able to just use `PutMetricData` as it creates the metric if it doesn't yet exist. I need to spend some more time looking into how to map `Counter`, `Gauge` and `Histogram` into CloudWatch metrics data types.

**Comment by peterbourgon** [comment]
Oh hell yeah, I'm all about this. +1000.

**Comment by cam-stitt** [comment]
I made a start to this. Happy to open a WIP pr to get some feedback on the direction that I am taking. You can see the direction I'm taking here: https://github.com/cam-stitt/kit/blob/cloudwatch-metrics/metrics/cloudwatch/cloudwatch.go

**Comment by basvanbeek** [comment]
closed by #495
