### ISSUE TITLE
JWT: Removing opinionated usage of Claims

### ISSUE THREAD

**Issue by cam-stitt** [go-kit/kit#490]
I created a PR to introduce support for additional claim objects in #488. After doing some thinking I came to a conclusion that some more work needs to be done on the jwt package.

- Remove the ambiguous `Claims` object
- Enforce the Sign/Parse methods to accept a `jwt.Claims` parameter

The current implementation leans towards only using `MapClaims` and I'm not sure what value the go-kit `Claims` object is providing.

**Comment by vgheri** [comment]
Agree, I'm not using the go-kit jwt middleware for this exact same reason.

**Comment by cam-stitt** [comment]
I ended up just modifying #488 to completely remove the ambiguous Claims type.

The other major change is that this is a backwards incompatible change.

**Comment by basvanbeek** [comment]
#488 has been merged and closes this issue
