### ISSUE TITLE
Request to move from prometheus http (deprecated) to the new one

### ISSUE THREAD

**Issue by sergiosarmentosilva** [go-kit/kit#491]
As it stands on the `http.go` file in the `prometheus/client_golang` repository, that file has been deprecated and moved to `prom/http` directory, with some changes. Quoted from `http.go` comment section:
```
It is a partial mirror of promhttp/http.go (to avoid circular import chains) where 
everything HTTP related should live. The functions here are just for avoiding breakage. 
Everything is deprecated.
``` 
For this reason, would it be possible to update the prometheus metrics in go-kit to use the new one?

**Comment by kavirajk** [comment]
Can I work on this?
