### ISSUE TITLE
Provide warning before API breaking change

### ISSUE THREAD

**Issue by ChristopherRabotin** [go-kit/kit#496]
It would be outstanding if you could provide some warning before making API breaking changes. A way to do this would be to warn the user of the library prior if they were to use a function which is deprecated.

Thanks, back to my code now where I have to fix many of my calls to this library...

**Comment by groob** [comment]
This is probably not the answer you're looking for but that's why dependencies have to be vendored with a tool like glide(or dep) instead of fetching code with `go get`. 

The release is tagged to prevent breaking a build.

**Comment by ChristopherRabotin** [comment]
I will look into glide. I had mostly terrible experience trying to deploy
code with godeps so I stopped using entirely over a year ago.

**Comment by groob** [comment]
Yes, unfortunately dependency management is an issue with Go in general. glide is the best stable tool out there for pinning dependencies today(IMO) and it looks like there's a light at the end of this dark tunnel too: github.com/golang/dep 

BTW the release notes for 0.4.0 do mention the breaking fix. 
I am curious about your suggestion to warn the library users:

>  A way to do this would be to warn the user of the library prior if they were to use a function which is deprecated.

Is there a way you had in mind beside the release notes and git tag(which obviously failed your use case here)? 
This [paper](http://breakingapis.org/) does a good job of discussing this tricky situation.

**Comment by ChristopherRabotin** [comment]
IIRC, Python has a `warnings` package which can be used to notify a user on import of a library. So mimicking that behavior, I suspect it ought to be possible to do something as follows (which is somewhat ugly):
```go
// Somewhere in an important file of the library
var userWasWarned = false

func(...) NewContext(...){
    if!userWasWarned{
        fmt.Println("yo, imma let you finish but things are gonna break real soon -- _Kanye_")
        userWasWarned = true
    }
}
```

**Comment by peterbourgon** [comment]
Sorry for the trouble! I'll echo what @groob already mentioned: if you're using Go kit, you should definitely be pinning to a version in your own code. The semantic version prefix `0.x.x` implies unstable; every version bump can (and, to be clear for Go kit: will) involve some degree of breaking change. In the a future, post-1.0.0 world, breaking changes will be accompanied by a major (1.x.x ☞ 2.x.x) version bump.

> I suspect it ought to be possible to do something as follows

Yo, that's fuckin' crazy. Ain't never gonna do that.
