### ISSUE TITLE
Caching support?

### ISSUE THREAD

**Issue by queirozfcom** [go-kit/kit#499]
Hi.

Shouldn't caching solutions be a major part of the kit? Has it been left out on purpose or will it be added in the future?

Thanks

**Comment by peterbourgon** [comment]
> Shouldn't caching solutions be a major part of the kit?

What does "caching solutions" mean? What would Go kit integration look like, at a high level?

**Comment by queirozfcom** [comment]
I'm not too sure, maybe a default implementation of caching, like you have for servcie discovery, circuit breaking, etc

**Comment by peterbourgon** [comment]
But caching of what? Requests and responses? Assets? Should it be in-memory, or an adapter layer to memcache/Redis/etc.?

**Comment by nashtsai** [comment]
I think @queirozfcom is asking about caching middleware for the endpoints. Implementation should be quite straightforward.

**Comment by peterbourgon** [comment]
Caching of _what_?

**Comment by basvanbeek** [comment]
this question has been silent for over a year and is not really in scope of the project, so closing it.
