### ISSUE TITLE
Quic network transport

### ISSUE THREAD

**Issue by joeblew99** [go-kit/kit#506]
https://github.com/lucas-clemente/quic-go

It's pretty stable and very fast.
Can use pure UDP or h2 :)

**Comment by basvanbeek** [comment]
Seems there is no need for a specific Quick network transport. You can use the wrappers from the h2quic package of this library and just use our HTTP Transport.

```go
// use h2quic instead of net/http's ListenAndServe
http.Handle("/", http.FileServer(http.Dir(wwwDir)))
h2quic.ListenAndServeQUIC("localhost:4242", "/path/to/cert/chain.pem", "/path/to/privkey.pem", nil)

// use h2quic transport for client
http.Client{
  Transport: &h2quic.QuicRoundTripper{},
}
```

**Comment by joeblew99** [comment]
@basvanbeek 
true, but what if you want to use UDP and NAT punch through for things that are more Peer 2 peer ? This is where QUIC helps . Correct me if i am wrong..
