### ISSUE TITLE
auth/session Transport/Middleware

### ISSUE THREAD

**Issue by ngurajeka** [go-kit/kit#511]
Hi,

I'm new in Go-Kit, and now are migrating my app to use Go-Kit. Since i was using session to authenticate my user, i need to know is there any workaround to implement this on Go-Kit?

What i've been trying before i opened this issue:
- Distribute store (session adapter) throught context, but i found it really hard to get the current request and response writer since the session itself need both of them
- I was trying to use gorilla/context to create new struct with attribute store, request and response. but still, in the end i need the httpresponse writer from the services.
- I was doing the same thing with point /2 but instead of using gorilla/context, i use the pattern of auth/jwt in go-kit package. I took the request and store it to context with creating a new ServeBeforeFunc transport options. And the problem is still the same which is how i can get the http.ResponseWriter from context, i know i can use ServerAfter in transport to store it again to context. But the problem is, using **ServerAfter** means my service has been executed which in my case i need the ResponseWriter to save session inside Service.

Thank You

**Comment by basvanbeek** [comment]
ServerAfter is executed before sending the response of the service method call back to the client and it also includes access to the ResponseWriter so you can set the appropriate headers (ex. new cookie or new JWT Authorization header).

Can you explain better why this doesn't work for you as I'm not sure I follow your last point?

**Comment by ngurajeka** [comment]
Sorry, maybe my bad english make you hard to understand my point.

![flow](https://cloud.githubusercontent.com/assets/3364191/24797139/1e917274-1bba-11e7-847b-16c3b5ac138e.png)

Above picture is explained how do i placed my code.
The problem is:
- I need http.ResponseWriter inside the Service. Its happened because calling session.Save command need http.Request and http.ResponseWriter as parameter.

**Comment by basvanbeek** [comment]
It's strange that the http.Request is needed as parameter for session.Save and I briefly checked the Gorilla code and it actually doesn't use the Request (not in the CookieStore, not in the FilesystemStore) as far as I can tell. Since the parameter is a pointer to the request you could try feeding it nil when utilizing session.Save in a ServerAfter function.

Another option (ugly but will work) would be to in a ServerBefore function store the Request in context and pull it out when needing it in the ServerAfter function.

**Comment by ngurajeka** [comment]
Ok, thanks.

Now it works:
- I use http.ServerBefore to store request and create session.
- I use http.ServerAfter to tell my session to save the current changes before the request end
