### ISSUE TITLE
Accept header available in context?

### ISSUE THREAD

**Issue by JeanMertz** [go-kit/kit#515]
I noticed that the `PopulateRequestContext` function does not transfer the `Accept` header from the request object to the context.

I'm using a custom `ServerBefore` function to add this header, but I was somewhat surprised, as the Accept header is something you use a lot when working with APIs that support multiple response formats.

**Comment by peterbourgon** [comment]
Does #516 do what you'd expect?

**Comment by JeanMertz** [comment]
It does, thank you for doing the work. I would've added it myself, but I didn't want to put in the "work" before I got some form of acknowledgement that this would be a good addition.

Either way, thank you, and keep up the good work with this project 👍
