### ISSUE TITLE
in memory generic metrics aren't shared across `With`

### ISSUE THREAD

**Issue by terinjokes** [go-kit/kit#525]
A common pattern is to use `metrics.*.With` in an endpoint middleware to created derived metrics:

```go
func (s *instrumentingService) Lookup(ctx context.Context) (bool, error) {
	defer func(begin time.Time) {
		s.requestCount.With("method", "lookup").Add(1)
	}(time.Now())

	return s.Service.Lookup(ctx)
}
```

If you're using the generic metrics, there's no way to retrieve these metrics; the in memory metrics aren't shared across calls to `With`.

```go
func TestCounter(t *testing.T) {
	var counter metrics.Counter
	counter = generic.NewCounter("requestCount")

	var svc Service
	svc = NewService()
	svc = instrumentingService{requestCount: counter, Service: svc}

	svc.Lookup(context.Background())

	if count := counter.With("method", "lookup").(*generic.Counter).Value(); count != float64(1) {
		t.Fatalf("expected '%d', got '%d'", float64(1), count)
	}
}

// expected '1', got '0'
```

**Comment by peterbourgon** [comment]
This is by design. Generic metrics aren't really meant to be used outside of a test context.

**Comment by terinjokes** [comment]
@peterbourgon I'm trying to use them in test, I don't see how they're useful there either, as the example shows. I think the design needs to be tweaked just a little bit.

**Comment by peterbourgon** [comment]
I'd happily accept a PR.

**Comment by peterbourgon** [comment]
I am no longer happy to accept a PR here, see #570. Sorry folks :(
