### ISSUE TITLE
Cloudwatch metrics does not limit nr. of MetricDatums to 20 per call

### ISSUE THREAD

**Issue by feliksik** [go-kit/kit#529]
According to the [AWS Docs](http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_limits.html), a max of 20 metricdatums can be sent in an API request. 

So this [code should](https://github.com/go-kit/kit/blob/master/metrics/cloudwatch/cloudwatch.go#L136) respect that. 

I might get to fixing this myself, but not today...

**Comment by cam-stitt** [comment]
Good find. Thanks for this.

**Comment by alpeb** [comment]
Would it suffice if I add checks for that in `NewCounter`, `NewGauge` and `NewHistogram` that would panic if that limit is reached?

**Comment by cam-stitt** [comment]
I'm not sure if a panic would be ideal in this situation. We should be able to split it into a max of 20 datums and spread it to multiple api requests.

**Comment by alpeb** [comment]
Sounds good. Can I have the honor of submitting a PR for this, or you prefer to tackle it yourself? :)
I was thinking we could do it in batches of concurrent API requests, say up to 4 concurrent requests per batch. Let me know what you think.

**Comment by cam-stitt** [comment]
Go for it! Happy to share. I would suggest making an option `NumConcurrentRequests` to specify how many requests can be sent per batch.

**Comment by cam-stitt** [comment]
@peterbourgon I believe we can probably close this off now?

**Comment by peterbourgon** [comment]
Jawohl.
