### ISSUE TITLE
how to Convert http.HandleFunc to *mux.Router

### ISSUE THREAD

**Issue by kamal-github** [go-kit/kit#530]
I am using [nrgorilla](https://github.com/newrelic/go-agent/blob/master/_integrations/nrgorilla/v1/nrgorilla.go) and [gokit](https://github.com/go-kit/kit)(having **mux** as router) heavily. how to Convert http.HandleFunc to *mux.Router?

So to instrument all routes I need to pass `*mux.Router` to `InstrumentRoutes` function, but I have http.Handler which I want to assert to `*mux.Router` to make it run. 

```
func InstrumentRoutes(r *mux.Router, app newrelic.Application) *mux.Router {
	r.Walk(func(route *mux.Route, router *mux.Router, ancestors []*mux.Route) error {
		h := instrumentRoute(route.GetHandler(), app, routeName(route))
		route.Handler(h)
		return nil
	})
	if nil != r.NotFoundHandler {
		r.NotFoundHandler = instrumentRoute(r.NotFoundHandler, app, "NotFoundHandler")
	}
	return r
}
```

Any help would be appreciated. Thanks!

**Comment by peterbourgon** [comment]
You (obviously) can't type-assert a HandlerFunc to a *mux.Router. If you want to use router.Walk, you need to register all your handlers in the router. You can register regular HandlerFuncs in a mux.Router just fine. I hope this helps.
