### ISSUE TITLE
Use http.Handle instead of mux Router while maintainig transport file

### ISSUE THREAD

**Issue by kamal-github** [go-kit/kit#531]
How to use `http.Handle` instead of `mux` Router without compromising transport layer and putting all handlers in `main.go`?

**Comment by peterbourgon** [comment]
I'm sorry, I don't understand the question. Can you say more?

**Comment by kamal-github** [comment]
@peterbourgon Thanks! my issue got resolved. 👍

**Comment by peterbourgon** [comment]
:100:
