### ISSUE TITLE
Serving file on Transportation Layer

### ISSUE THREAD

**Issue by ngurajeka** [go-kit/kit#541]
Hi,

I want to ask is there any workaround to serve file in the API Gateway?
I've tried to create a simple response encoder like this,

```
// EncodeFileResponse encoding path, filename as downloadable fie to responsewriter
func EncodeFileResponse(ctx context.Context, w http.ResponseWriter, resp interface{}) error {
	if e, ok := resp.(Errorer); ok && e.Error() != nil {
		EncodeError(ctx, e.Error(), w)
		return nil
	}
	file, _ := resp.(FileInfo)
	w.Header().Set("Content-Description", "File Transfer")
	w.Header().Set("Content-Transfer-Encoding", "binary")
	w.Header().Set(
		"Content-Disposition",
		fmt.Sprintf("attachment; filename=%s", file.Name),
	)
	w.Header().Set("Content-Type", file.Type)
}
```

But, to serve a file i need to do this

```
http.ServeFile(writer, request, filepath
```

Which currently like this:

```
http.ServeFile(w, ?, file.Path)
```

Is the pointer to the request available in the encoder context Value? or is there any workaround so i can serve a file in the API Gateway?

Thanks

**Comment by peterbourgon** [comment]
You can always wire up another route in the transport layer that doesn't go to any endpoint, and instead to an http.ServeFile handler.

**Comment by ngurajeka** [comment]
Thank you @peterbourgon
