### ISSUE TITLE
sd/eureka: test failures

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#542]
```
# github.com/go-kit/kit/sd/eureka
.../eureka/integration_test.go:59: instancer.State undefined (type *Instancer has no field or method State)
.../eureka/integration_test.go:77: instancer.State undefined (type *Instancer has no field or method State)
.../eureka/integration_test.go:92: undefined: endpoints
.../eureka/integration_test.go:92: undefined: err
.../eureka/integration_test.go:92: undefined: endpointer in endpointer.Endpoints
.../eureka/integration_test.go:93: undefined: err
.../eureka/integration_test.go:94: undefined: err
.../eureka/integration_test.go:96: undefined: endpoints
```

https://circleci.com/gh/go-kit/kit/1216

@yurishkuro I reckon this is related to the thing I just merged. Can you knock this one out quickly? I'll look into why Circle isn't running on PRs...

**Comment by peterbourgon** [comment]
> **Build forked pull requests**
> 
> Run builds for pull requests from forks. CircleCI will automatically update the commit status shown on GitHub's pull request page.

This is now turned on.

**Comment by yurishkuro** [comment]
looking

**Comment by yurishkuro** [comment]
@peterbourgon an aside question - do you find CircleCI to be better for integration tests than Travis? I'm wondering if we should consider it for Jaeger.

**Comment by peterbourgon** [comment]
I'm not sure why we decided to run integration tests on Circle rather than Travis. Maybe it was because it had a nicer (read: easier to use) Docker environment?
