### ISSUE TITLE
A problem about the use of Middleware

### ISSUE THREAD

**Issue by GrantZheng** [go-kit/kit#543]
Hi:
According to your example/stringsvc2, if I define a middleware and want to use it in global, I have to implement all functions of the service  in my defined middleware., such as , in the instrumenting.go file, it implement Uppercase and Count function. But is there another simple way to only need to write a middleware function which can use for all service, such as the use of middleware in the gin web framework:
`r := gin.New()
	r.Use(gin.Logger())
	r.Use(gin.Recovery())
	r.Use(func(c *gin.Context) {
		_caller := c.Query("_caller")
		var getResNil struct{}

	       if _caller == "" {
			c.JSON(200, gin.H{
				"errno":  common.INVALID_PARAMS,
				"errmsg": common.RespMsg[common.INVALID_PARAMS] + ": _caller empty",
				"data":   getResNil})
			c.Abort()
		}
	})
	r.GET("/project/qps/lists", listProjectQps)     
	r.POST("/project/qps/update", updateProjectQps) 
	r.GET("/api/qps/lists", listApiQps) 
	r.POST("/api/qps/update", updateApiQps) `

The middleware written once in r.USE function can be used in global.

**Comment by peterbourgon** [comment]
Given

```go
type MyService interface {
    Foo(context.Context) string
    Bar(context.Context) int
}
```

then, by definition, _service_-level (or _business domain_) middlewares must implement (or delegate) the entire method set, because they must satisfy the MyService interface.

```go
type loggingMiddleware struct {
    logger log.Logger
    next   MyService
}

func (m loggingMiddleware) Foo(ctx context.Context) string {
    m.logger.Log("Foo")
    return m.next.Foo(ctx)
}

func (m loggingMiddleware) Bar(ctx context.Context) int {
    m.logger.Log("Foo")
    return m.next.Bar(ctx)
}
```

If you only want to affect a single method from the method set, you can embed the next MyService instead of treating it as a regular struct field.


```go
type someMiddleware struct {
    MyService
}

func (m someMiddleware) Foo(ctx context.Context) string {
    println("hello from the middleware")
    return m.MyService.Foo(ctx)
}

// No need to define Bar; it's picked up automatically from MyService
```

If your middleware is agnostic to the business-domain types and values, it can be implemented as a so-called endpoint middleware, and used on any endpoint.

```go
type EndpointMiddleware func(endpoint.Endpoint) endpoint.Endpoint

func myMiddleware(next endpoint.Endpoint) endpoint.Endpoint {
    return func(ctx context.Context, request interface{}) (response interface{}, err error) {
        // In this block we have access to the context and the un-typed request.
        // We could provide more state in an additional closure, if we wanted.
        return next(ctx, request)
    }
}
```
