### ISSUE TITLE
Change repo setting to "Allow squash merging"?

### ISSUE THREAD

**Issue by yurishkuro** [go-kit/kit#546]
@peterbourgon I just noticed that when you merged my main discovery PR it picked up all the commits. Have you considered changing the settings on the repository to "Allow squash merging" only? We use this on all Jaeger repo so that we don't have to keep asking contributors to squash manually. It makes for a much nicer commit history. The only problem is that it only preserves the authorship on Github itself, e.g. a commit in Jaeger repo might look like "**yurishkuro** committed with **black-adder** 4 days ago", but in the actual git history just lists the final committer.

![image](https://cloud.githubusercontent.com/assets/3523016/26835145/92b4fa12-4aa5-11e7-8cfb-5b7e8533aecf.png)

**Comment by peterbourgon** [comment]
I don't particularly like squash merging; I like my commit histories to reflect reality, dirty and messy :)

**Comment by yurishkuro** [comment]
ok then :-)
