### ISSUE TITLE
Catch panics in http Server

### ISSUE THREAD

**Issue by esenac** [go-kit/kit#551]
Hi, 
it could be useful to recover from panic in `transport/http.Server.ServeHTTP`. Panic could be caused by errors in encoding or decoding functions or in general in the code of the underlying service. Recover would allow to return a proper HTTP status code (i.e. a 500) instead of dropping the connection.
This is mostly useful for debugging purposes, in the current situation you won't get evidence of the occurred panic in the logs.

**Comment by esenac** [comment]
A possible example could be the following:
```
// ServeHTTP implements http.Handler.
func (s Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	if s.finalizer != nil {
		iw := &interceptingWriter{w, http.StatusOK, 0}
		defer func() {
			ctx = context.WithValue(ctx, ContextKeyResponseHeaders, iw.Header())
			ctx = context.WithValue(ctx, ContextKeyResponseSize, iw.written)
			s.finalizer(ctx, iw.code, r)
		}()
		w = iw
	}

	defer func() {
		if r := recover(); r != nil {
			ctx = context.WithValue(ctx, ContextKeyRecoveredFromPanic, r)
		}
	}()
....
```
In this way the error put in the context could be accessed and handled in the _finalizer_ without changing the current behaviour.

**Comment by peterbourgon** [comment]
Why should we give special treatment to ServeHTTP? Why shouldn't we do the same recovery dance before descending into any call stack?

**Comment by ChrisHines** [comment]
What to do with panics is a _policy_ choice that the main application should be allowed to make, which means that at the very least is would have to be configurable. I wonder if a standalone panic handler isn't a better approach. See the top answer to this SO question for an example: https://stackoverflow.com/questions/28745648/global-recover-handler-for-golang-http-panic

**Comment by esenac** [comment]
@peterbourgon we are trying to introduce gokit as a standard for microservices in our company and we are fully based on REST over HTTP, so we have knowledge on that part and we focused just on `ServeHTTP`. Sure it would be a better option to have a common approach to panic handling for all transports.

@ChrisHines we actually developed a solution like the one you propose in our microservices, but we think that it could be useful that the framework would provide a common solution for this problem. The one we proposed would let the choice of what to do with panics to the main application by checking the key in the context.
We came to this proposal because the current behaviour of the gokit framework is just to silence all the panics, making it hard to discover the misbehaviour of the applications.

**Comment by ChrisHines** [comment]
Just to be clear, Go kit is not involved with handling panics. It is the Go standard library that handles the panics in `net/http.Server` as seen here: https://golang.org/src/net/http/server.go?s=79791:79837#L1714

There was a proposal to the Go project (https://github.com/golang/go/issues/16542) to allow applications to disable this behavior of `net/http.Server`. The proposal was rejected, but a workaround was provided in the discussion along similar lines to what I suggested above.

Having said that, I didn't fully appreciate your proposed solution on my first read. I'm still concerned that the proposed solution silently overrides the `net/http.Server` behavior, but the idea of allowing the finalizer to inspect the panic value is nice. Maybe this feature should be enabled with a `ServerOption`. Maybe it makes more sense to only recover from panics at this level if `s.finalizer != nil`.

**Comment by esenac** [comment]
@ChrisHines yes, the idea of letting the finalizer inspect the panic value is intended at least to log the error. In our scenario, logs are structured and parsed by a centralized log system. This leads to the loss of standard logs printed in `net/http.Server` function that you referenced. Having the panic message available in finalizer could help to make it visible in such a logging scenario.

**Comment by ChrisHines** [comment]
I agree this would improve the logging of panics. I have been using `log.NewStdlibAdapter` to redirect log events from `net/http.Server` into a structured logger, but we cannot parse panics correctly as identified by #233. So a solution that intercepts the panics sooner and handles them in a more Go kit compatible way is attractive.

I would want to make sure, however, that a default `kit/transport/http.Server` does not recover panics without logging them.

Also, as @peterbourgon suggested, the behavior and capabilities of the `kit/transport/grpc.Server` should be comparable.

**Comment by esenac** [comment]
Hi @ChrisHines and @peterbourgon , I prepared a PR with a possible implementation of what we discussed above. Please feel free to review and comment the changes. Thanks!

**Comment by peterbourgon** [comment]
Sorry for the delay—GopherCon and all that. After a fair bit of thought I think the best course of action here is no action: I think if you want to do panic recovery on a per-transport basis, you can use per-transport middlewares pretty effectively. I've [added an entry to the gokit.io FAQ](http://gokit.io/faq/#panics-mdash-how-should-my-service-handle-panics) to that end. I hope this suits. Thanks for your patience and hard work on the PR!
