### ISSUE TITLE
Using kit/log makes it impossible to debug applications on some OS X installations.

### ISSUE THREAD

**Issue by dkushner** [go-kit/kit#555]
Since kit/log makes use of go-stack/stack to grab the current stack trace for file and line annotations, it suffers from the problem mentioned in [this issue](https://github.com/derekparker/delve/issues/852). I have submitted a PR on go-stack/stack [here](https://github.com/go-stack/stack/pull/12) that should address this problem, pending approval by @ChrisHines.

**Comment by lockwobr** [comment]
+1

**Comment by ChrisHines** [comment]
This should be fixed as of the latest release of go-stack/stack: https://github.com/go-stack/stack/releases/tag/v1.5.4
