### ISSUE TITLE
transport/http: Strange phrase in NewServer documentation.

### ISSUE THREAD

**Issue by shurcooL** [go-kit/kit#560]
[http.NewServer](https://godoc.org/github.com/go-kit/kit/transport/http#NewServer) documentation says:

```Go
// NewServer constructs a new server, which implements http.Server and wraps
// the provided endpoint.
```

I don't understand what it means by "implements http.Server". [`http.Server`](https://godoc.org/net/http#Server) is a struct. Is there a typo in the documentation?

**Comment by groob** [comment]
It implements the Handler interface. I agree this looks like an oversight.

**Comment by shurcooL** [comment]
Thanks for resolving this issue @peterbourgon! Now it makes sense to me.
