### ISSUE TITLE
Why not update oldcontext to new context?

### ISSUE THREAD

**Issue by GrantZheng** [go-kit/kit#563]
Hi,
   When I use the go-kit, I find some package use the "golang.org/x/net/context",  so that I have to depend and manage the "golang.org/x/net/context" in my code, otherwise it can generate error, why not update it?
thx

**Comment by basvanbeek** [comment]
We can't as long as gRPC still relies on it. See https://github.com/grpc/grpc-go/issues/711 for "context" :)
