### ISSUE TITLE
Thoughts on adding a more verbose log level, 'trace' to level/level.go etc?

### ISSUE THREAD

**Issue by chmorgan** [go-kit/kit#584]
From my days with log4cxx trace would be used for the most verbose levels, debug for informative but only useful to developers, and info higher level info about more major operations.

I'm finding that I have some low level output that I'd like to optionally output but that it is too verbose/frequent for debug and debug statements are too verbose for info. Adding trace could be a good place for things that you may need in some occasions but that are simply too verbose/frequent for the debug level.

Clearly someone could come along and suggest some SuperTrace in the future. Imo log4cxx and log4j are examples of having 'trace' without going too far and having yet another level below it.

If this is an ok idea I'll submit a PR.

**Comment by peterbourgon** [comment]
log4xxx libraries reify _tons_ of antipatterns, and a proliferation of log levels is chief among them. Even the current 4 levels encoded in package log/level are already [about 2 too many](https://dave.cheney.net/2015/11/05/lets-talk-about-logging), for my tastes—they're there only to act as a sort of bridge of compassion to developers coming from other environments. So a strong -1 from me on this, sorry! Debug is what you're looking for. Happy to leave the issue open for a little while for discussion, though.

**Comment by chmorgan** [comment]
@peterbourgon read that link and thinking about it. Appreciate you leaving the issue open for discussion at least for a little while.

**Comment by peterbourgon** [comment]
I'll close this in the next day or two unless someone has some revelations.
