### ISSUE TITLE
Include a unit for Gauge/Histogram values? 

### ISSUE THREAD

**Issue by feliksik** [go-kit/kit#595]
Would there be any sensible way to include a unit with gauges/histograms? Related to #569, but separate issue to keep the topic focused. 

I think this would be part of the metric instantiation, e.g. provider.NewGauge("theName", gokit_units.Celcius)

I don't know about the other backends, but [Cloudwatch supports](http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDatum.html)  the following units: 

```
Valid Values: Seconds | Microseconds | Milliseconds | Bytes | Kilobytes | Megabytes |
Gigabytes | Terabytes | Bits | Kilobits | Megabits | Gigabits | Terabits | Percent | Count |
Bytes/Second | Kilobytes/Second | Megabytes/Second | Gigabytes/Second | 
Terabytes/Second | Bits/Second | Kilobits/Second | Megabits/Second | Gigabits/Second | 
Terabits/Second | Count/Second | None 
```

Will it be tricky to do this uniformly? (note that to point out the pain-point quickly, I picked gokit_units.Celcius, which is already not in the AWS set!)

**Comment by peterbourgon** [comment]
Units should be part of the name string. Per-implementation support for units is out of scope for the Go kit metrics package, unless there is some coherent way to layer it in.

**Comment by feliksik** [comment]
Yes indeed that's the difficult thing, and maybe making that coherent/generic would make everything too difficult.

The unit as part of the metric name wouldn't further complicate the generic gokit API part.

To use the metric semantics in the relevant backend, a specific provider (e.g. cloudwatch) could have a special interpretation for a gauge called "throughput:Kilobytes/Second", in that it would actually recognize the unit and pass it as the relevant unit in the Cloudwatch API. Then it's up to the provider.

That would keep the gokit API simpler and consistent, and at least the unit is not be considered for the package design.

Is there anyone that thinks the unit functionality is useful at all?

**Comment by nlowe** [comment]
I could see this being extremely useful. I haven't found a way to assign a unit to a metric at graph time. This means I have to do mental math to put the scale of my metric values into picture. For example:

![image](https://user-images.githubusercontent.com/794251/62058105-d8d9dc80-b1ee-11e9-8be1-4c15a15189a8.png)

The left Y axis is in seconds, and the values are currently in the range of tens of milliseconds. If I were able to assign a unit to this metric, CloudWatch should do this conversion for me.

What about having the CloudWatch integration look for a special label to set the unit? This is what the CloudPosee scraper does:

https://github.com/cloudposse/prometheus-to-cloudwatch/blob/2087b3a047463cbeead0607f1832c4b3ad23e11c/prometheus_to_cloudwatch.go#L412-L417

**Comment by peterbourgon** [comment]
```diff
+       // The label whose value signifies the CloudWatch unit name to use
+       UnitLabel = "__cw_unit"
```

```diff
+           if labelValues[i] != UnitLabel {
```

Woof 👎

**Comment by peterbourgon** [comment]
Sorry, I think this is a pass.
