### ISSUE TITLE
Issues accessing JWT claims on context

### ISSUE THREAD

**Issue by chuej** [go-kit/kit#607]
I'm using the JWT middleware to parse JWT claims and assign them to the request context.
```go
type Claims struct {
	User  string `json:"user,omitempty"`
	stdjwt.StandardClaims
}
func (c Claims) Valid() error {
	return nil
}

func JWTParse(ep endpoint.Endpoint) endpoint.Endpoint {
	kf := func(token *stdjwt.Token) (interface{}, error) { return []byte("SigningString"), nil }
	ep = jwt.NewParser(kf, stdjwt.SigningMethodHS256, &Claims{})(ep)

	return ep
}
```
 That seems to be working, but when I try to access the JWT claims in an endpoint, the value is always `nil`:
```go
return func(ctx context.Context, request interface{}) (response interface{}, err error) {
  fmt.Printf("context::::::%v\n", ctx.(context.Context))

  custCl := ctx.(context.Context).Value("JWTClaims")
  // custCl is `nil`

  custCl, ok := ctx.(context.Context).Value("JWTClaims").(*Claims)
  // custCl is `nil`

  if !ok {

    err := fmt.Errorf("Claims were not passed into context correctly: %v\n", ok)
    panic(err)
  }

  req := request.(getJobsRequest)
  js, e := s.List(ctx, req.Options)
  return js, e
}
```

When I print the context (line 2), I see the `JWTClaims` key being set:

    .WithValue("JWTClaims", &job.Claims{User:"jrocket@example.com", StandardClaims:jwt.StandardClaims{Audience:"www.example.com", ExpiresAt:1536478382, Id:"", IssuedAt:1504942382, Issuer:"Online JWT Builder", NotBefore:0, Subject:"jrocket@example.com"}})

I'm trying to emulate what's in  [this test](https://github.com/go-kit/kit/blob/master/auth/jwt/middleware_test.go#L192).

**Comment by ChrisHines** [comment]
I think you want to retrieve the claims with a line like this:
```go
custCl := ctx.Value(jwt.JWTClaimsContextKey)
```
That's the key that `jwt.NewParser` uses to put the claims in the context, as seen here: https://github.com/go-kit/kit/blob/f7593d19082ad15f6376f12c746d71d680aa1666/auth/jwt/middleware.go#L138

**Comment by chuej** [comment]
Works! Thanks for the speedy response!
