### ISSUE TITLE
Time unit mismatch in statsd metrics Observe()

### ISSUE THREAD

**Issue by esenac** [go-kit/kit#608]
Hi @peterbourgon!
We are using statsd for metrics, and it seems we found a mismatch in time units between `metrics/statsd.Timing`and  `metrics.Timer`.
Timer's `ObserveDuration` method calculate the elapsed time [in seconds](https://github.com/go-kit/kit/blob/f7593d19082ad15f6376f12c746d71d680aa1666/metrics/timer.go#L23) and passes it to the underlying Histogram's `Observe` method, that in case of `statsd.Timing` requires the parameter [in milliseconds](https://github.com/go-kit/kit/blob/f7593d19082ad15f6376f12c746d71d680aa1666/metrics/statsd/statsd.go#L236).
It would be nice to have the chance to specify the time unit measure for `ObserveDuration` in Timer constructor or at least to be compliant with the underlying method.

**Comment by peterbourgon** [comment]
metrics.Timer was not built to be compatible with statsd.Timing! But I would be happy to accept a PR that changed the unit on a metrics.Timer. I guess it should be implemented as a new method on the Timer struct, e.g. Unit(time.Duration), with an implied default of time.Second.

**Comment by esenac** [comment]
Opened PR #610!

**Comment by nicolaiskogheim** [comment]
This should be closed, right? :)

**Comment by esenac** [comment]
@nicolaiskogheim yep, thanks.
