### ISSUE TITLE
Do not always override operation name when tracing endpoints

### ISSUE THREAD

**Issue by embs** [go-kit/kit#615]
I'd like the operation name not to get overwritten in a server span when it's already set by the client who is calling the endpoint -- which is the case when using same span for client/server, like here: https://github.com/microservices-demo/user/pull/53

I guess this behavior could be achieved by modifying https://github.com/go-kit/kit/blob/0d313fb5fb3a94d87d61e6434785264e87a5d740/tracing/opentracing/endpoint.go#L25

Maybe we could add some conditional logic to set operation name only if the span isn't being shared between client/server? (I'm afraid this could be Zipkin-specific though)

Does that make sense? I would gladly try fixing up a PR if it does.

**Comment by basvanbeek** [comment]
it is Zipkin specific and Zipkin standard behavior

**Comment by yurishkuro** [comment]
it is illegal to start a span via OpenTracing API without an operation name. Also it is generally a bad idea trusting the client to name your server endpoint, the server is the authority.

btw, Jaeger (http://github.com/uber/jaeger), recently accepted to CNCF, does not mix client/server spans, if you want to try it out.

**Comment by embs** [comment]
Thank you for your kind suggestions and explanations.

I'll try moving towards using single-host spans, then.
