### ISSUE TITLE
Allow for errors before decoding (e.g. serverbefore)

### ISSUE THREAD

**Issue by denniszl** [go-kit/kit#616]
I want to add some validation for JWT tokens in a function like ServerBefore but I'm unable to do so because I can't error in this function (outside of putting it in the context). I think this is a logical place to allow for validation since it makes sense to return here if something goes wrong.

As a workaround I'm planning on wrapping the decoder but I think I'd still prefer to do it in somewhere like ServerBefore.

**Comment by ChrisHines** [comment]
The current suggested approach is to use ServerBefore to add the JWT to the context, then use endpoint middleware to validate the JWT and return errors. The rationale is that the ServerBefore is transport specific, while endpoint middleware applies to all requests regardless of which transport it arrived on.

**Comment by denniszl** [comment]
So the problem we're running into the issue that since at the moment we're decoding before the middleware is run we're going to throw an error from decoding even if the JWT was invalid, and we'd like to do it the other way around.

**Comment by peterbourgon** [comment]
> [_Because_] we're decoding [_the request_] before the middleware is run, we're going to throw an error from decoding even if the JWT was invalid, and we'd like to do it the other way around.

Why?

**Comment by denniszl** [comment]
I think if the JWT is invalid we want to check the JWT first for security (we don't want to decode a bunch of arbitrary bodies from someone with an invalid JWT). We also just want to return a 403 here, which can't happen if we run the JWT code in middleware, which runs after the decoder.

**Comment by peterbourgon** [comment]
There are three stages of request decoding/parsing:

1. Collecting information from the transport domain
2. Confirming the request is syntactically valid
3. Confirming the request is semantically valid

The HTTP transport adapter enforces decoding/parsing in this order. BeforeFuncs perform (some of) the work of stage 1. DecodeRequestFuncs do the work of stage 2. Endpoint middlewares and the service layer are responsible for stage 3. This demarcation of work emerged quite organically but in retrospect I think it's the right one. It's straightforward, it's easy to understand, and it makes sense. The interfaces we've implemented—i.e. those WhateverFuncs, and more specifically their function signatures—clearly communicate that separation of work, and reinforce the staged model of processing.

You're asking for a way to do part of stage 3 prior to doing any of stage 2. If that is a true use case I agree it's not possible in Go kit currently. But I'm not convinced that generalizing the clear interfaces (function signatures) and, in consequence, weakening the processing model I've outline above, is a fair price to pay.

So,

> we don't want to decode a bunch of arbitrary bodies from someone with an invalid JWT

The only real risk here that I can think up is one of resource denial-of-service. That's easily mitigated by wrapping an io.LimitReader around the http.Request.Body before performing the json.Decode. Are there other concerns?

**Comment by peterbourgon** [comment]
Friendly ping:

> Are there other concerns?

**Comment by denniszl** [comment]
No, we ended up just wrapping the decoder. Sorry, forgot to close.
