### ISSUE TITLE
how to use go-kit to process the file upload of download handler

### ISSUE THREAD

**Issue by kingeasternsun** [go-kit/kit#625]
I suppose if go-kit endpoint can be used to process the file upload or download request, so the file upload or download count and latency can be logged

**Comment by peterbourgon** [comment]
Yes, it is possible. Can you please clarify your question?

**Comment by kingeasternsun** [comment]
for example, for the case of upload file,how to write the **Decoder** of decodeUploadFileRequest especially for the big file. for the case of download file, how to write the "Encoder" of decodeDownloadFileResponse,expecially for the big file .

for the small file ,I think i can write the Decoder use the method of read the full data of formfile one -off,like this:
```
func decodeUploadFileRequest(_ context.Context, r *http.Request) (interface{}, error) {
	file, handle, err := r.FormFile("file")
	if err != nil {
		return nil,err
	}
	defer file.Close()
        data,err :=ioutil.readAll(file)
        if err !=nil{
                  return nil,err
        }
       return data,err
}
```
but for the giant file, read the file data one-off can cost too many memory ,so this is a bad idea,I think there must be some method to get the data piece by piece instead of get all one-off.

as to the file download, I think there must be some method to response the data piece by piece .
without go-kit, i can use a buffered reader to write file data the responseWriter
```
func ServerFile(w http.ResponseWriter, req *http.Request) {
    path := "/home/kingeasternsun/dovsvn/BOOKS.zip"
    f, err := os.Open(path)
    if err == nil {
        bufferedReader := bufio.NewReader(f)
        w.Header().Add("Countent Type", "text/plain")
        bufferedReader.WriteTo(w)
    } else {
        w.WriteHeader(404)
        w.Write([]byte("404"))
    }
}
```

is go-kit has similar method?

**Comment by peterbourgon** [comment]
You can construct the various fooRequest and fooResponse types to contain io.Readers, attach them to the request and/or response bodies, and stream from them.

```go
type LargeFileUploadRequest struct {
    remoteFile io.Reader
}

func decodeLargeFileUploadRequest(...) {
    // ...
    request.remoteFile = req.Body
    // ...
}

func (myService) HandleLargeFileUpload(req LargeFileUploadRequest) {
    // process req.Body
}
```

**Comment by kingeasternsun** [comment]
Thanks  very  much for the code,but how  can i convert from formfile to r.Body

**Comment by peterbourgon** [comment]
I think this is a question that's out-of-scope for the Go kit project! :)

**Comment by groob** [comment]
I did write a file upload decode/encode function in a project. 

https://github.com/micromdm/micromdm/blob/d8b044fe1b6bf9ce67e9e6896038e7382e72fd5f/core/apply/transport_http.go#L99-L118

`http.Request.FormFile` is what you're looking for.

**Comment by peterbourgon** [comment]
Oh nice! Thanks @groob. Hopefully that's useful as an example.
