### ISSUE TITLE
Question: Where to do authorization for a certain service methods?

### ISSUE THREAD

**Issue by falmar** [go-kit/kit#629]
Hello, I'm fairly new to go-kit and micro-service architecture as well.

I have a doubts on how to properly use go-kit for the following problem

I have a JWT that contains the authenticated user's id as a claim, and per each service's method I want to check if the user actually have permission to update its own **client** record, but it seems that wherever I put it, it feels wrong. What are the best practices to doing something like this?

```go
// client.go
type Client struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	// ...
}

type ClientDataLayer interface {
	Load(db *sql.DB, id string) *Client
	Update(db *sql.DB, cl *Client) *Client
	// ... more CRUD methods
}
```

Doing it within a service middleware I would have to call another service's method which seems to break the purpose of the architecture, is it?

```go
// service.go
type Service interface {
	UpdateClient(ctx context.Context, cl *Client) (*Client, error)
	// ... more methods
}

func NewClientService(db *sql.DB, cdl ClientDataLayer) {
	// ....
}

type service struct {
	db  *sql.DB
	cdl ClientDataLayer
}

func (svc *service) UpdateClient(ctx context.Context, id string) (*Client, error) {
	return nil, nil
}

// service middleware
type accessControl struct {
	svc Service
}

func (ac *accessControl) UpdateClient(ctx context.Context, cl *Client) (*Client, error) {
	// ... get token and claims from context
	// scopes := jwt.Claims().Get("scopes")

	// Here I don't have the client's user_id, 
       // and it does not feel right to call another service's method
	if !strings.Contains(scopes, "client:write") || cl.UserID != userID {
		return nil, errors.New("forbidden")
	}

	// ...
	return nil, nil
}
```

Doing it on the endpoint its pretty much the same
```go
// transport.go
func makeUpdateClientEndpoint(svc Service) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (interface{}, error) {
		// type cast request
		// ... get token and claims from context
		// scopes := jwt.Claims().Get("scopes")

		// Same problem as before, I don't have the client's user_id

		if !strings.Contains(scopes, "client:write") || cl.UserID != userID {
			return nil, errors.New("forbidden")
		}

		cl, _ := svc.UpdateClient(ctx, request.ClientID)

		// ...

		return nil, nil
	}
}
```

I probably could get away by using the ClientDataLayer to retrieve the client and checking the user's id. As a way to avoid messing with another service method to load the client because it may have middlewares for logging or metrics too. 

How could achieve this without so much hassle where I feel like breaking the patterns

**Comment by peterbourgon** [comment]
The general categorization rules are

- transport/[DecodeRequestFunc](https://godoc.org/github.com/go-kit/kit/transport/http#DecodeRequestFunc) — pure syntax validation, e.g. reject malformed JSON
- endpoint.Middleware — validation that should be transport-independent, but without introspecting on your domain objects, e.g. reject more than 100 reqs/sec from some IP
- Your service implementation — all remaining validation that needs to inspect business logic, e.g. malformed user IDs, broken business rules

IMO, Authorization belongs in your service implementation. But I could be convinced it may make sense as an endpoint.Middleware. You would need to populate relevant information e.g. user IDs, tokens, etc. into the context.Context in a [ServerBefore RequestFunc](https://godoc.org/github.com/go-kit/kit/transport/http#RequestFunc), and consume that information out of the context in the middleware.

That assumes you can authorize a request purely within your service, without making another RPC. If that's not true—if you need to query an e.g. authsvc to authorize each request—then this is business logic, by definition, and this work needs to be done in your service implementation. But if every request to any service requires a RPC to an authsvc, this gets quickly into the realm of microservice antipatterns—much better to build this as an embeddable library or local cache, IMO.

Does it help?

**Comment by falmar** [comment]
Yes it does help thanks,

It broke it in parts as follow:

- ServerBefore - Extract token string from request
- endpoint.Endpoint middleware - Verify JWT is valid (sign/expiration/subject) - Authentication
- Service middleware - Verify user's JWT contains necessary scopes/roles - Authorization 
- Service implementation - Verify if user is the owner of the resource - Authorization

This way it make more sense to me, however using API Gateway pattern pretty much the only entry point, all this within Docker Swarm networks secured by default and also another layer of physical private network.

It seems like a overkill to authorize/authenticate each service inside the private network but we never know what could happen, to me with GoKit implementing this level of security seems just as easy plug and play :)

Thanks again @peterbourgon

**Comment by peterbourgon** [comment]
🎉

**Comment by dreamer-nitj** [comment]
@falmar If you had to implement the expiration logic for auth tokens based on the how long the token has been idle, wouldn't it be tricky to implement it as a library compared to if the authentication was handled using a service?

**Comment by falmar** [comment]
Hey @dreamer-nitj, this is actually the authentication service :D. Other services may not check validity of the JWT, but authorization alone like scopes/roles or resource owner within themselves
