### ISSUE TITLE
Can't use context values are defined in middleware in ServerFinalizer

### ISSUE THREAD

**Issue by izaurio** [go-kit/kit#632]
If you look at the code, you can see how to pass the value of the context.
https://github.com/go-kit/kit/blob/9917269ff0e9fc93df46474b411ea1716195a61b/transport/http/server.go#L108

Schematically:
- ctx init
- ctx1 server before
- ctx1.1 middleware1
- ctx1.2 middleware2
- ctx1.3 endpoint
- ctx2 server after
- ctx2 server finalizer

If you set the value of the context in middleware, it will not be available in the finalizer.

If you use the middleware kitjwt.NewParser (https://godoc.org/github.com/go-kit/kit/auth/jwt#NewParser), you will not be able to use the values in the logger running in the finalizer (as you recommended earlier).

For example, the signature endpoint of this type would solve the problem.
```go
type Endpoint func(context.Context, interface{}) (context.Context, interface{}, error)
```
I understand that it is not possible so easy to do.

What do you recommend for detailed logging, where you want to use the context values are defined in the middleware? The data logger on the middleware does not have access to the response code (if I'm not mistaken).

**Comment by peterbourgon** [comment]
If a middleware (like jwt.NewParser) wants to inject information into the context, it may do so.

```go
func myInjectingMiddleware(k, v string) endpoint.Middleware {
    return func(next endpoint.Endpoint) endpoint.Endpoint {
        return func(ctx context.Context, request interface{}) (response interface{}, err error) {
            
            nextctx := context.WithValue(ctx, k, v)
            response, err := next(nextctx, request)
            return response, err
            
        }
    }
}
```

The (k, v) pair injected is available in the context of any subsequent middleware, as well as in the service layer. You can log the (k, v) in any of those places. In general, if you have advanced logging needs, you should be logging at the service layer, either in the concrete service implementation itself, or via a service middleware.

Does this answer the question? Did you intend something else?

**Comment by izaurio** [comment]
Unfortunately, this is not the answer. 

I want to add data to the context middleware, as you showed in the example. But to use the data I want here: https://godoc.org/github.com/go-kit/kit/transport/http#ServerFinalizer. Now I can't do that. In finalizer not passed a context value that has been changed in middleware. And it's not obvious behavior.

**Comment by peterbourgon** [comment]
What specifically do you want to do?

**Comment by izaurio** [comment]
The web application receives the request. The token is passed in the request header. Use jwt.NewParser as middleware. Get access TokenClaims. In particular TokenClaims.UserID. After processing the http request to produce logging (kithttp.ServerFinalizer(logRequest(logger)). 
```go
func logRequest(logger log.Logger) kithttp.ServerFinalizerFunc {
	return func(ctx context.Context, code int, r *http.Request) {
		logger.Log(
			"method", r.Method,
			"host", r.Host,
			"uri", r.RequestURI,
			"status", code,
			//"editor_id", token_claims.UserID
		)
	}
}
```
I want to get the value of the user id when logging http request. It is normal practice to do so?

**Comment by peterbourgon** [comment]
Don't use ServerFinalizer for this; use a service middleware that you write yourself.

**Comment by izaurio** [comment]
Then a related question. How to get status code of response? It was the only reason to use ServerFinalizer.

**Comment by peterbourgon** [comment]
You already know the status code of your response. By default it is 200 OK. If you want something else, your error and/or response types should implement [transport/http.StatusCoder](https://godoc.org/github.com/go-kit/kit/transport/http#StatusCoder), and you can log the status code in the service layer directly.

```go
type myResponse struct {
    Msg  string `json:"msg"`
    code int    `json:"-"`
}

func (r myResponse) StatusCode() int {
    return r.code
}
```

The [DefaultErrorEncoder](https://godoc.org/github.com/go-kit/kit/transport/http#DefaultErrorEncoder) and [EncodeJSONResponse](https://godoc.org/github.com/go-kit/kit/transport/http#EncodeJSONResponse) try to type-assert error and response values, respectively, to extract these status codes if they're set. If you have a custom ErrorEncoder or EncodeResponseFunc they can/should also type-assert the error and response values to do the same work.

```go
func encodeMyResponse(ctx context.Context, w http.ResponseWriter, response interface{}) error {
    // ...
    if sc, ok := response.(httptransport.StatusCoder); ok {
        w.WriteHeader(sc.StatusCode())
    }
    // ...
}
```

**Comment by izaurio** [comment]
It's clear. Thank you.

**Comment by zcgzxg** [comment]
but,how to write the signed jwt token to http response header,the signed token is in context
