### ISSUE TITLE
Question: Message Queue as a transport? 

### ISSUE THREAD

**Issue by falmar** [go-kit/kit#646]
Hello,

I understand non-rpc transports are non-goals on go-kit, but we have already implemented an email service and endpoints exposed with a HTTP transport and we would like to listen for messages on RabbitMQ using AMQP protocol.

The implementation of such transport fall on us and I'm not asking for it to be implemented on go-kit but...

Question: Is it okay to reuse the Endpoint and Service layers?

**Comment by peterbourgon** [comment]
Absolutely! I'd also be happy to look at a PR for transport/rabbit or transport/amqp, if it were sufficiently generalized.
