### ISSUE TITLE
GRPC endpoint template support for kitgen

### ISSUE THREAD

**Issue by travissalascox** [go-kit/kit#647]
wanted to start off by saying the work on kitgen so far has been awesome. having something that can create the boilerplate for go-kit is very helpful for getting off the ground quickly with go-kit.

one thing that would really help though would be the ability to generate boilerplate for more than just http endpoints. Specifically was hoping for grpc go-kit endpoint support from it.

hopefully this issue can be used as a jumping off point to figure out how to best do that, or even just to see if there is any interest in added grpc endpoint support to kitgen.

**Comment by Raffo** [comment]
I would love to get a shot at that, will do once there are answer to the questions in #639 .

**Comment by jcftang** [comment]
It would be nice to see grpc support in kitgen.

**Comment by marcosrmendezthd** [comment]
+1
