### ISSUE TITLE
can't load package when run ./update_deps.bash on ubuntu

### ISSUE THREAD

**Issue by theflycloud** [go-kit/kit#649]
I cloned the project to my local linux:
ubuntu 16
and run the command "./update_deps.bash " to try to get the dependency.
system alerts:
ubuntu@VM-0-6-ubuntu:~/go/src/github.com/go-kit/kit$ ./update_deps.bash 
can't load package: log/value.go:6:2: cannot find package "github.com/go-stack/stack" in any of:
        /usr/local/go/src/github.com/go-stack/stack (from $GOROOT)
        /home/ubuntu/go/src/github.com/go-stack/stack (from $GOPATH)
can't load package: package github.com/dgrijalva/jwt-go: cannot find package "github.com/dgrijalva/jwt-go" in any of:
        /usr/local/go/src/github.com/dgrijalva/jwt-go (from $GOROOT)
        /home/ubuntu/go/src/github.com/dgrijalva/jwt-go (from $GOPATH)
can't load package: transport/grpc/server.go:4:2: cannot find package "golang.org/x/net/context" in any of:
        /usr/local/go/src/golang.org/x/net/context (from $GOROOT)
        /home/ubuntu/go/src/golang.org/x/net/context (from $GOPATH)

I debug this shell and found it caused by 
“
 go list -f '{{join .Deps "\n"}}' ./... | xargs go list -f '{{if not .Standard}}{{.ImportPath}}{{end}}'

”,but I don't know why, would anybody like to help?

**Comment by peterbourgon** [comment]
update_deps.bash is a script for Go kit developers, not users. There's no reason you should ever need to run it.

**Comment by theflycloud** [comment]
@peterbourgon oh,yes,I tried the shipping example and it only need source code of the dependencies to make application build that is very different from java or .net.
