### ISSUE TITLE
[Question] Is there a easier way to wrap functions?

### ISSUE THREAD

**Issue by dinfer** [go-kit/kit#651]
`gokit` is awesome, but I have to write so many `encode...`, `decode..`, make...Endpoint` and so on. If I Only use GRPC, is there a better way to wrap it as endpoint or something other without coding so much wrapper?

**Comment by dinfer** [comment]
But, there must be a field(like message ID or url)tells the server which type the payload is. why not use it?

**Comment by peterbourgon** [comment]
No, there isn't always such a field.

**Comment by dinfer** [comment]
If there is not such filed, how a decoder tell with message the payload is?

**Comment by peterbourgon** [comment]
The code that receives requests on e.g. `/api/v1/create` knows to decode a `CreateRequest`; the code that receives requests on e.g. `/api/v1/modify` knows to decode a `ModifyRequest`, etc.

**Comment by kanupriya-hub** [comment]
Adding wrappers allows us to listen for Telemetry, errors, and logs in your code, without you needing to call our API explicitly. You may want to wrap a function to add instrumentation or temporary debugging logic. You can also change the behavior of an external library without needing to modify the source.
