### ISSUE TITLE
opentracing.FromHTTPRequest Not Found

### ISSUE THREAD

**Issue by sherwoodzern** [go-kit/kit#652]
The code will not compile because the opentracing.FromHTTPRequest reference is not found.  Is there a newer release of the code where this is fixed?

**Comment by basvanbeek** [comment]
Which code are you trying to compile?

In Go kit the tracing middleware functions changed names. The`FromHTTPRequest` you mention has been changed to `HTTPToContext`

See: https://github.com/go-kit/kit/commit/0ecbed2b93b47b650e1ae75c9e1107f98718c813
