### ISSUE TITLE
FromHTTPRequest function missing

### ISSUE THREAD

**Issue by sherwoodzern** [go-kit/kit#654]
What happened to the FromHTTPRequest function?  Is there a new function that should be used versus the FromHTTPRequest?

**Comment by basvanbeek** [comment]
Please see the answer to your same question at #652.
Click on the link there to see all name changes to the tracing package

**Comment by sherwoodzern** [comment]
Thank You.  I was unable to find the 652 issue I had reported earlier.  It was missing from the issues.  Thank you again.
