### ISSUE TITLE
can offer some examples to show how to add OpenTracing Tracer implementation for Zipkin in Go in go kit

### ISSUE THREAD

**Issue by kingeasternsun** [go-kit/kit#655]

**Comment by basvanbeek** [comment]
Example of wiring tracing can be found in `examples\addsv`

Another option is to use the native zipkin-go tracer. We're still working on the Go kit unit tests for this new middleware before sending the PR but you can already give it a testrun. 

See: https://github.com/basvanbeek/kit/tree/master/tracing/zipkin

This newer native tracer implementation uses the Zipkin V2 API (the OpenTracing one uses V1). It has no dependency on thrift and middleware is easier to plug in.

**Comment by kingeasternsun** [comment]
Thanks
