### ISSUE TITLE
'InsecureSkipVerify' in Client | https requests

### ISSUE THREAD

**Issue by elideveloper** [go-kit/kit#661]
Hi,
how to enable 'InsecureSkipVerify' in http.Transport of go-kit's http client? Or how to make http client to request HTTP Secure in other way?
Problem is that go-kit's Client does not allow using any other http client than http.DefaultClient. Why?

**Comment by basvanbeek** [comment]
You can add a custom configured *http.Client if using the SetClient() functional option.

```go
httpClient := &http.Client{....}
client := kithttp.NewClient(method, target, encoder, decoder, kithttp.SetClient(httpClient))
```

**Comment by elideveloper** [comment]
ok, thanks!
