### ISSUE TITLE
Context threading (between services)

### ISSUE THREAD

**Issue by seonixx** [go-kit/kit#667]
Could be a very stupid question, but I noticed in the stringsvc example documentation that context threading is not covered...

I understand context threading between functions and middlewares etc, however assuming context is used for distributed tracing, and passing user context between microservices (over HTTP) in gokit, how does one actually pass context between services over HTTP?

Apologies if I'm missing something obvious...

**Comment by yurishkuro** [comment]
that's where tracing instrumentation comes in. In go-kit the RPC API requires you to provide the context, and if you dutifully propagated that context from inbound to outbound call in your app, the tracing instrumentation built into RPC will take care of encoding the context into wire representation, and then decoding it on the receiving side.

**Comment by seonixx** [comment]
Thanks @yurishkuro - appreciate your fast reply. Could you provide or point me in the direction of an example of context being received by a gokit microservice?

A scenario I'm trying to get my head around is if I have an "API gateway" that attaches the user object to a context.Context, and then I'm making an RPC request to a gokit service, how would I pass that context to the gokit service?

**Comment by seonixx** [comment]
Also, the link to the client library on the addsvc example is broken: https://gokit.io/examples/stringsvc.html#creating-a-client-package

**Comment by peterbourgon** [comment]
Thanks, I fixed the link, it should be updated soon.

**Comment by seonixx** [comment]
Apologies - finally got my head around how to properly structure a client library (with passed in context etc).
