### ISSUE TITLE
grpc load balancing demo

### ISSUE THREAD

**Issue by kafrax** [go-kit/kit#676]
```
var testService = etcdv3.Service{
	Key:   "/addsvc/sum",
	Value: "192.168.102.130:8083",
	TTL:   nil,
}
```
i use this to register a grpc endpoint to etcd,and use apigateway ask it successful in my project.i need a grpc load balancing demo.

**Comment by peterbourgon** [comment]
The apigateway example is not meant to be a runnable demo.

**Comment by kafrax** [comment]
i wanna achieve a grpc load balancing,can you give some suggestion?
