### ISSUE TITLE
examples/addsvc/thrift/gen-go/addsvc does not build

### ISSUE THREAD

**Issue by h8liu** [go-kit/kit#677]
```
src/github.com/go-kit/kit/examples/addsvc/thrift/gen-go/addsvc/addsvc.go:376:14: not enough arguments in call to oprot.Flush
	have ()
	want (context.Context)
```

see https://smallrepo.com/builds/20180313-030859-0f1d869f for more details

probably because not using the latest thrift.

**Comment by peterbourgon** [comment]
God, I hate Thrift.

**Comment by basvanbeek** [comment]
Second that!

**Comment by sjdweb** [comment]
Hi - was having trouble with this while using dep, you'll need an override in `Gopkg.toml` like so:

```
[[override]]
  name = "github.com/apache/thrift"
  revision = "5785279e2e809f6c56dbbe0eb41d13fb17c88bdd"
```

As it seems to take the latest release of thrift which is quite old, and `zipkin-go-opentracing` expects master.

**Comment by yyt030** [comment]
@sjdweb you are right.
