### ISSUE TITLE
An etcd Publisher

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#68]
A `type etcdPublisher struct` which implements Publisher via typical etcd service discovery pattern(s).

**Comment by twanies** [comment]
Is someone already implementing this? Otherwise i can implement one and show some code next monday. We are rewriting one of our services and trying out go-kit for this. We are on a CoreOS stack and in need of an etcd publisher.

**Comment by peterbourgon** [comment]
No one's picked it up yet! Please feel free. @xla has started a Consul publisher in #100 which may serve as a starting point. Don't hesitate to bug me with questions, either on here, or in the Slack channel :)

**Comment by twanies** [comment]
@peterbourgon How you want the tests to be written? ATM i have all tests run against a real etcd instance. What i can do is make an etcdClient interface and use a mocked version of the client for the tests.

**Comment by peterbourgon** [comment]
Yep, that sounds right.

**Comment by peterbourgon** [comment]
This is done!
