### ISSUE TITLE
A Consul Publisher

### ISSUE THREAD

**Issue by peterbourgon** [go-kit/kit#69]
A `type consulPublisher struct` which implements Publisher via a (set of) Consul instance(s).

**Comment by andrewwatson** [comment]
I've just started taking a crack at this one...

**Comment by peterbourgon** [comment]
:+1:

**Comment by kris-runzer** [comment]
Is there any in progress work for this issue?  We're looking into this exact problem and would rather contribute to a solution than create our own.

**Comment by peterbourgon** [comment]
Yes, please see #100, and don't feel bad about bugging @xla about it :)

**Comment by xla** [comment]
#100 is merged, so maybe a good time to close this one?

**Comment by peterbourgon** [comment]
Whoopsie doodle.
