### ISSUE TITLE
question about use grpc

### ISSUE THREAD

**Issue by kafrax** [go-kit/kit#694]
Invoking |err":"context deadline exceeded","caller":"red_packet_biz.go:31","ts":"2018-04-01T14:15:22.417879Z   i meet this when i send a grpc request to my server.

**Comment by peterbourgon** [comment]
This is outside the scope of Go kit.

**Comment by kafrax** [comment]
@peterbourgon not yet ,i found it happen with  github.com/go-kit/kit/transport/grpc/server.go， when usiness logic return error ，Interceptor will be working and do server.go line 132  grpc.SendHeader make deadline or cancel.Is there a problem with my usage？
