### ISSUE TITLE
Log components in README.md

### ISSUE THREAD

**Issue by lucasmrod** [go-kit/kit#696]
Looks like [sirupsen/logrus](https://github.com/sirupsen/logrus), [sasbury/logging](https://github.com/sasbury/logging) and [inconshreveable/log15](https://github.com/inconshreveable/log15) are listed in the [individual components](https://github.com/go-kit/kit#individual-components) list but they are not used by go-kit.

**Comment by ChrisHines** [comment]
That list is a sublist within "Related projects" and is not intended to be a list of dependencies of go-kit. In many cases the mentioned projects are prior art that we used as inspiration or somehow influenced the design decisions made by go-kit.

**Comment by lucasmrod** [comment]
OK, makes sense. Closing, sorry for the noise :)
