### ISSUE TITLE
How to set http request timeout by using kit/transport/http/client.go

### ISSUE THREAD

**Issue by GrantZheng** [go-kit/kit#700]
Hi:
When I use the "kit/transport/http/client.go" as my http client library, I do not know how to set http request timeout.
Any ideas?
Thanks

**Comment by peterbourgon** [comment]
When calling transport/http.[NewClient](https://godoc.org/github.com/go-kit/kit/transport/http#NewClient), use the [SetClient](https://godoc.org/github.com/go-kit/kit/transport/http#SetClient) option to set a custom [http.Client](https://godoc.org/net/http#Client) with the desired request timeout.
