### ISSUE TITLE
Clarify the difference between log.With and log.WithPrefix

### ISSUE THREAD

**Issue by danderson** [go-kit/kit#702]
The log package has both `With` and `WithPrefix`. The docstrings are identical, and all references I could find mention `With` and `WithPrefix` interchangeably. However, their implementations are very different.

The documentation should clarify the difference between these two calls, or the implementations should be converged if they are truly equivalent.

I'm happy to submit a PR for this... But I'd need someone to explain to me what the difference is first, because I couldn't figure it out from a quick reading of the source code :(

**Comment by ChrisHines** [comment]
The docstrings are *not quite* identical. See below with emphasis added to highlight the difference.

>With returns a new contextual logger with keyvals prepended to those passed to calls to Log. If logger is also a contextual logger created by With or WithPrefix, keyvals is **appended** to the existing context.

>WithPrefix returns a new contextual logger with keyvals prepended to those passed to calls to Log. If logger is also a contextual logger created by With or WithPrefix, keyvals is **prepended** to the existing context.

Hopefully that—along with the function names themselves—helps to understand the difference.

**Comment by danderson** [comment]
Okay, so still prepended to the contents of the Log call, but prepended/appended to other previously added contexts. I suppose... Thanks.

**Comment by ChrisHines** [comment]
Yes, exactly. `log.With` should be used in the majority of cases. But when we implemented leveled logging we found that `WithPrefix` was useful to keep the level information near the beginning of the log record the way that most people are used to.
