### ISSUE TITLE
go get issue

### ISSUE THREAD

**Issue by gigimushroom** [go-kit/kit#704]
go get github.com/go-kit/kit/...
# github.com/go-kit/kit/examples/addsvc/thrift/gen-go/addsvc
../../../github.com/go-kit/kit/examples/addsvc/thrift/gen-go/addsvc/addsvc.go:377:14: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
../../../github.com/go-kit/kit/examples/addsvc/thrift/gen-go/addsvc/addsvc.go:394:16: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
../../../github.com/go-kit/kit/examples/addsvc/thrift/gen-go/addsvc/addsvc.go:407:16: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
../../../github.com/go-kit/kit/examples/addsvc/thrift/gen-go/addsvc/addsvc.go:421:24: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
../../../github.com/go-kit/kit/examples/addsvc/thrift/gen-go/addsvc/addsvc.go:442:16: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
../../../github.com/go-kit/kit/examples/addsvc/thrift/gen-go/addsvc/addsvc.go:455:16: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
../../../github.com/go-kit/kit/examples/addsvc/thrift/gen-go/addsvc/addsvc.go:469:24: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
# github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe
../../../github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:283:14: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
../../../github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:300:16: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
../../../github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:313:16: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
../../../github.com/openzipkin/zipkin-go-opentracing/thrift/gen-go/scribe/scribe.go:327:24: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()

**Comment by navono** [comment]
How can I update thrift with master by `dep`? related to [this](https://github.com/openzipkin-contrib/zipkin-go-opentracing/issues/103), also get error.
