### ISSUE TITLE
Please mention additional tools/resources for kit such as a CLI generator to get started

### ISSUE THREAD

**Issue by kristianmandrup** [go-kit/kit#710]
I found [kujtimiihoxha/kit](https://github.com/kujtimiihoxha/kit) which looks to be the most developed generator.

Would be nice with an `awesome-go-kit` repo or on the gokit.io page itself, which lists project, examples, tutorials, tools etc. by the community that revolves around kit. 

Many popular frameworks/libs have this kind of community hub as place to find what you need when working with the framework/lib.

**Comment by peterbourgon** [comment]
I agree. Can anyone watching provide links to other helpers/tools in this issue?

**Comment by ChrisHines** [comment]
https://github.com/nytimes/marvin

**Comment by kujtimiihoxha** [comment]
Here is also how you can use Kit https://medium.com/@kujtimii.h/creating-a-todo-app-using-gokit-cli-20f066a58e1

**Comment by vetcher** [comment]
you may also check #631

**Comment by GrantZheng** [comment]
Hi, I have updated Gokit-CLi for go module and plan to maintain it in the future. 
https://github.com/GrantZheng/kit/releases/tag/v1.0.0
