### ISSUE TITLE
Unable to set header for client request

### ISSUE THREAD

**Issue by seonixx** [go-kit/kit#714]
I'm having some trouble assigning custom headers to requests using the ClientOptions method. An example of an endpoint with a ClientBefore option attached:

```golang
var getInstitutionEndpoint endpoint.Endpoint
	{
		getInstitutionEndpoint = httptransport.NewClient(
                 "POST",
                 utils.CopyURL(u, "/get-institution"),
                 encodeHTTPGenericRequest,
                 decodeGetInstitutionResponse,
                 httptransport.ClientBefore(httptransport.SetRequestHeader("x-test", "abcde"))).Endpoint()
	}
```

The header is not being set prior to the request being sent. Am I missing something here? Any suggestions with troubleshooting also appreciated.

**Comment by seonixx** [comment]
Additional snippets for encode and decode on the endpoint:

**encodeRequest**
`func encodeHTTPGenericRequest(_ context.Context, r *http.Request, request interface{}) error {
	var buf bytes.Buffer

	if err := json.NewEncoder(&buf).Encode(request); err != nil {
		return err
	}

	r.Body = ioutil.NopCloser(&buf)
	return nil
}`

**Decode Response**
`func decodeGetInstitutionResponse(_ context.Context, r *http.Response) (interface{}, error) {
	if r.StatusCode != http.StatusOK {
		return nil, utils.ErrorDecoder(r)
	}

	var resp service.GetInstitutionResponse
	err := json.NewDecoder(r.Body).Decode(&resp)

	return resp, err
}`

**Comment by seonixx** [comment]
So... I should have used a more accurate example as this might have been detected earlier.

I was actually trying to assign a Host header for the purposes of using a transparent proxy (linkerd), which by default accepts the Host header as the service identifier e.g. Host: core...

```golang
var getInstitutionEndpoint endpoint.Endpoint
	{
		getInstitutionEndpoint = httptransport.NewClient(
                 "POST",
                 utils.CopyURL(u, "/get-institution"),
                 encodeHTTPGenericRequest,
                 decodeGetInstitutionResponse,
                 httptransport.ClientBefore(httptransport.SetRequestHeader("Host", "core"))).Endpoint()
	}
```

I dropped some debug statements around and saw the Host header was being stripped from the request before being sent. I stumbled across this that makes me think it's a net/http "issue" (https://github.com/golang/go/issues/7682)?

Anyway, I've changed the linkerd config to use a different service identifier (X-Service for now although it's purely for testing) to avoid dealing with the Host header, which I feel is probably a cleaner way of doing it regardless.

Thanks for your help @peterbourgon  - any thoughts or information about the Host header would be interesting!

**Comment by peterbourgon** [comment]
Sorry, I don't know anything about the Host header in particular!

I guess we can verify this is/isn't Go kit related by switching `Host` to `X-Something-Else`?

**Comment by seonixx** [comment]
Yes I've switched to X-Service for now and that's working fine. Appears to be related to the http package, so not specifically a go-kit issue, but worth noting anyway, especially for those who employ any kind of transparent proxy that relies on host headers.

Thanks for your help!
