### ISSUE TITLE
jsonrpc response contains null error

### ISSUE THREAD

**Issue by wangzuo** [go-kit/kit#728]
According to the [spec](https://www.jsonrpc.org/specification#response_object):

> error
> This member is REQUIRED on error.
> This member MUST NOT exist if there was no error triggered during invocation.
> The value for this member MUST be an Object as defined in section 5.1.

The example from https://github.com/go-kit/kit/blob/master/transport/http/jsonrpc/README.md also contains a null error field.

**Comment by peterbourgon** [comment]
@rossmcf
