### ISSUE TITLE
loadbalancer.NewDNSSRVPublisher is in the wrong place

### ISSUE THREAD

**Issue by rogpeppe** [go-kit/kit#73]
It doesn't seem right for the loadbalancer package to have domain-specific Publisher implementations inside it.

**Comment by peterbourgon** [comment]
We should create packages loadbalancer/{dnssrv,consul,etcd,...}, and {dnssrv,consul,etcd,...}.NewPublisher constructors. I suppose StaticPublisher may continue to live in loadbalancer.

**Comment by peterbourgon** [comment]
Closed by #90.
