### ISSUE TITLE
Can not  build examples/addsvc/cmd/addsvc

### ISSUE THREAD

**Issue by zaghitya** [go-kit/kit#732]
What I done:
1. clone the kit to my local, no modification
2. change directory to kit
3. on kit directory do: dep init
4. on kit directory do: dep ensure
5. on kit directory do: go build ./examples/addsvc/cmd/addsvc/

get error: 
github.com/zaghitya/kit/vendor/github.com/go-kit/kit/transport/grpc
vendor\github.com\go-kit\kit\transport\grpc\client.go:115:20: c.client.Invoke undefined (type *grpc.ClientConn has no field or method Invoke)
github.com/zaghitya/kit/vendor/github.com/go-kit/kit/examples/addsvc/thrift/gen-go/addsvc
vendor\github.com\go-kit\kit\examples\addsvc\thrift\gen-go\addsvc\addsvc.go:377:14: too many arguments in call to oprot.Flush
        have (context.Context)
        want ()
...
...
(Other similiar error)

Please your help, thanks in advance

**Comment by peterbourgon** [comment]
There is no reason to `dep init` in Go kit's `kit` directory. `kit` will always be a dependency of another `package main`, you should `dep init` in that other repo. (Go kit maintains best-effort compatibility with HEAD of all of its dependencies.)

If you do this, it works on my machine, as of right now:

```
git clone https://github.com/go-kit/kit
cd kit
go get -d -u -v ./...
go build ./examples/addsvc/cmd/addsvc
```

**Comment by zaghitya** [comment]
It works. I think I strayed off on the usage of dep. thank you.
