### ISSUE TITLE
nats example endpoint parameter

### ISSUE THREAD

**Issue by gorkemsari** [go-kit/kit#735]
Hi,

Im new for go-kit. So, may be im wrong but i have noticed something here. 

https://github.com/go-kit/kit/blob/3aeb4d5359ced8a82f2e56d7c1458df114264e80/examples/stringsvc4/main.go#L61

HTTP endpoints gets nc parameters and NATS endpoints gets svc parameters. Is it correct usage for nats?

**Comment by peterbourgon** [comment]
@kirooha Can you parse this question?

**Comment by kirooha** [comment]
hi @gorkemsari 
NATS endpoints define the required parameter of svc service to process strings and return modified ones like it is in the example of HTTP endpoints which you can see there http://gokit.io/examples/stringsvc.html. 
As for HTTP endpoints, they define nc parameter to proxy requests to NATS through Endpoint (a Publisher method https://github.com/go-kit/kit/blob/master/transport/nats/publisher.go#L65).
Endpoint uses go client for NATS to perform requests with a context.

**Comment by gorkemsari** [comment]
hi @kirooha 
Thank you for response. I will focus on this.
