### ISSUE TITLE
Does kit/log work with Go Modules?

### ISSUE THREAD

**Issue by variadico** [go-kit/kit#737]
Normally, I install `kit/log` this way.

```
go get github.com/go-kit/kit/log
```

So when I was playing with Go Modules I tried installing this way.

```
$ go1.11beta2 get github.com/go-kit/kit/log@v0.7.0
go: finding github.com/go-kit/kit/log v0.7.0
go: finding github.com/go-kit/kit/log latest
go: finding github.com/go-kit/kit v0.7.0
go: downloading github.com/go-kit/kit v0.7.0
go get github.com/go-kit/kit/log@v0.7.0: missing module for import: github.com/go-kit/kit@v0.7.0 provides github.com/go-kit/kit/log
```

However, this didn't update my `go.mod` file.

I tried again with

```
go1.11beta2 get github.com/go-kit/kit@v0.7.0
```

and that time `go.mod` was updated. In addition, the gokit source was downloaded to my machine.

In my code, I imported go kit this way,

```go
import (
  kitlog "mod/github.com/go-kit/kit@v0.7.0/log"
)
```

but, then I got a build error.

```
$ go1.11beta2 build
build github.com/variadico/foo: cannot find module for path mod/github.com/go-kit/kit@v0.7.0/log
```

Not sure if I'm doing something wrong or if this is a bug in `go1.11beta2`.

I checked `$GOPATH/src/mod/github.com/go-kit/kit@v0.7.0/log` and the code is definitely there.

**Comment by variadico** [comment]
Oh, wait. gofmt on save was messing me up.

The import path should be:

```go
import (
  kitlog "github.com/go-kit/kit/log"
)
```

Fixing the import path worked for `gorilla/websocket`, but `kit/log` now displays this error.

```
$ go1.11beta2 mod -sync
go: import "github.com/variadico/foo" ->
        import "github.com/go-kit/log": cannot find module providing package github.com/go-kit/log
```

**Comment by ChrisHines** [comment]
I think one of your import statements is wrong. The error message you're getting provides the clue:

```
import "github.com/go-kit/log": cannot find module providing package github.com/go-kit/log
```

The correct import path is `github.com/go-kit/kit/log`. Note the additional `kit` segment before `log`.

**Comment by variadico** [comment]
Baaahh.

You're totally right! I screwed up the import paths. I thought we had to do something special, but nope.

Thank you!
