### ISSUE TITLE
REST style URLs with HTTP Client

### ISSUE THREAD

**Issue by stampy88** [go-kit/kit#741]
I am trying to use the HTTP transport `Client` to consume an existing web service. The problem is that the URLs are REST style, i.e. they are parameterized based on what you are retrieving. An example would be `/api/bar/{id}` where the variable `id` would be filled in at request time. 

The problem is that the `httptransport.NewClient` function requires the URL be known at creation time. So my question is what is the go-kit way of handling URLs like this? Create a new `Client` every time? Modify the URL on the `http.Request` that is passed into the encode function?

Thanks!
Dave

**Comment by basvanbeek** [comment]
Yes you'd do the latter. An example of a client doing this can be seen here:

https://github.com/basvanbeek/opencensus-gokit-example/tree/master/clients/device/http

It even works if client uses Go kit service discovery. Example down here shows this with setting the baseURL from the emitted new instance:

https://github.com/basvanbeek/opencensus-gokit-example/blob/master/shared/factory/http.go#L31:6

**Comment by stampy88** [comment]
Thanks @basvanbeek
