### ISSUE TITLE
Prevent kitgen from failing on interface-type

### ISSUE THREAD

**Issue by ermik** [go-kit/kit#745]
Here's an example of a service definition that fails in kitgen:

```go
package profilesvc

import "context"

type Service interface {
	PostProfile(ctx context.Context, p Profile) error
}

type Profile struct {
	ID        string                 `json:"id"`
	Name      string                 `json:"name,omitempty"`
        // fails because of loosely typed field with interface{}
	Neighbors map[string]interface{} `json:"neighbors,omitempty"`
}

type Address struct {
	ID       string `json:"id"`
	Location string `json:"location,omitempty"`
}
```

Error message:
` examining input file "./in.go": found 7 interfaces, expecting exactly 1`

**Comment by nyarly** [comment]
Yeah, that's a pain.

I extracted a lot of the codegen that kitgen does to its own package. I'm considering depending on that and fixing this in the near future. @peterbourgon What do you think? Or the switch and the fix could be two different PRs.
