### ISSUE TITLE
examples/stringsvc3   examples\stringsvc3\main.go:48:10: undefined: StringService

### ISSUE THREAD

**Issue by zhuxiujia** [go-kit/kit#750]
# command-line-arguments
examples\stringsvc3\main.go:48:10: undefined: StringService
examples\stringsvc3\main.go:49:8: undefined: stringService
examples\stringsvc3\main.go:50:8: undefined: proxyingMiddleware
examples\stringsvc3\main.go:51:8: undefined: loggingMiddleware
examples\stringsvc3\main.go:52:8: undefined: instrumentingMiddleware
examples\stringsvc3\main.go:55:3: undefined: makeUppercaseEndpoint
examples\stringsvc3\main.go:56:3: undefined: decodeUppercaseRequest
examples\stringsvc3\main.go:57:3: undefined: encodeResponse
examples\stringsvc3\main.go:60:3: undefined: makeCountEndpoint
examples\stringsvc3\main.go:61:3: undefined: decodeCountRequest
examples\stringsvc3\main.go:61:3: too many errors

**Comment by peterbourgon** [comment]
Please provide the full set of commands you ran to get this output, and re-open the issue.

**Comment by gadieichhorn** [comment]
$ go run examples/stringsvc3/main.go 
# command-line-arguments
examples/stringsvc3/main.go:48:10: undefined: StringService
examples/stringsvc3/main.go:49:8: undefined: stringService
examples/stringsvc3/main.go:50:8: undefined: proxyingMiddleware
examples/stringsvc3/main.go:51:8: undefined: loggingMiddleware
examples/stringsvc3/main.go:52:8: undefined: instrumentingMiddleware
examples/stringsvc3/main.go:55:3: undefined: makeUppercaseEndpoint
examples/stringsvc3/main.go:56:3: undefined: decodeUppercaseRequest
examples/stringsvc3/main.go:57:3: undefined: encodeResponse
examples/stringsvc3/main.go:60:3: undefined: makeCountEndpoint
examples/stringsvc3/main.go:61:3: undefined: decodeCountRequest
examples/stringsvc3/main.go:61:3: too many errors

**Comment by peterbourgon** [comment]
Don't use `go run` for anything.

```
go build github.com/go-kit/kit/examples/stringsvc3
./stringsvc3
```

**Comment by ChrisHines** [comment]
With recent versions of Go you can use `go run examples/stringsvc3` or `go run .` if your shell working dir is `examples/stringsvc3`. Both of those forms should be the same as building the binary, running it, and deleting it after. See if either works better.
