### ISSUE TITLE
Logrus adapter for Logger

### ISSUE THREAD

**Issue by AlmogBaku** [go-kit/kit#752]
I suggest we'll provide a Logrus adapter for our log interface.

This adapter will mainly be used to support features of gokit, i.e. "gokit's http-server logging"

**Comment by AlmogBaku** [comment]
simple example:
```
type serverLogger struct {
	*logrus.Entry
}
func (l serverLogger) Log(keyvals ...interface{}) error {
	if len(keyvals)%2 == 0 {
		logger := l.Entry
		for i:=0; i<len(keyvals); i+=2 {
			logger = logger.WithField(spew.Sdump(keyvals[i]), keyvals[i+1])
		}
		logger.Error()
	} else {
		l.Error(keyvals)
	}
	return nil
}
```

**Comment by aswinmprabhu** [comment]
I am new to Golang and this is my attempt at this issue. Any feedback would be appreciated.

**Comment by AlmogBaku** [comment]
In the meanwhile, you can use the code I attached above. I'll send a PR later on

**Comment by aswinmprabhu** [comment]
Shall I write tests and make a PR?

**Comment by AlmogBaku** [comment]
In our use-case, we decided to use `logrus` organization-wide. However, we using some components of go-kit(such as `kithttp.NewServer`) which require a `kit.logger`.

I think it would make sense to provide as a part of the kit an adapter for logrus (like we have adapters for other stuff here)

**Comment by dolum** [comment]
go-kit http server only requires for a logger to implement this interface.
```
type Logger interface {
	Log(keyvals ...interface{}) error
}
```
You can use any struct you want if it has ```Log(keyvals ...interface{}) error```

**Comment by AlmogBaku** [comment]
I'm not suggesting to use Logrus, but to provide an adapter to our logger.
See the code here I attached above as a reference.

**Comment by ChrisHines** [comment]
I am willing to review a PR that adds a package with a logrus adapter. Suggestions for the package path:

* github.com/go-kit/kit/log/logrus
* github.com/go-kit/kit/log/kitlogrus

**Comment by aswinmprabhu** [comment]
I will make a PR after writing the tests

**Comment by aswinmprabhu** [comment]
#759
