### ISSUE TITLE
How to best integrate `net/http.ServeContent` with Go kit http.

### ISSUE THREAD

**Issue by homme** [go-kit/kit#766]
I'd like to use [net/http.ServeContent](https://golang.org/pkg/net/http/#ServeContent) to support HTTP Range requests in my Go kit application but can't figure out a best practice for doing this: `EncodeResponseFunc` doesn't provide access to the `*http.Request` which would otherwise make this simple. I could save the request object in the context further up the stack but _really_ don't want to do that. Any other ideas?

**Comment by peterbourgon** [comment]
Hmm, I think this may be enough of a special case that plopping the *http.Request into the context (in a [RequestFunc](https://godoc.org/github.com/go-kit/kit/transport/http#RequestFunc) provided via [ServerBefore](https://godoc.org/github.com/go-kit/kit/transport/http#ServerBefore)) is probably your best bet. Both sides of that contract are implemented in the transport layer, it feels like it makes sense to me. Do you agree?

**Comment by homme** [comment]
Thanks Peter. It would be nice to be able to interoperate seamlessly between go-kit and the standard http package and not have to rely on runtime type checking in the context, but the scoping does tie in with what [you've said before](https://peter.bourgon.org/blog/2016/07/11/context.html) so it'll do for now :)
