### ISSUE TITLE
Why not to move some circuitbreakers into sub-packages?

### ISSUE THREAD

**Issue by xgfone** [go-kit/kit#775]
When using the circuitbreaker, we maybe use one of them. So it's enough to import the corresponding third-party dependency package, not all.

For example, I want to use the `gobreaker` implementation, but I don't want to care and download the `hystrix` third-party dependency. However, If I don't control the version of the dependency packages, the app may not be compiled because of the change of APIs.

---

Update:

I think that they should be placed into their own sub-packages.

**Comment by peterbourgon** [comment]
Creating lots of subpackages reduces dependencies, but pollutes the namespace. Having all circuitbreakers in a single package creates more dependencies, but keeps a tidier namespace. In my opinion, which is subjective, the dependencies aren't very large, and it's better to optimize for a singular namespace.

With that said, we will probably be re-structuring the Go kit repo in a post-1.0 world. Keep an eye out for that.
