### ISSUE TITLE
Kitgen does not work outside of GOPATH

### ISSUE THREAD

**Issue by xkenmon** [go-kit/kit#779]
With the release of Go 1.11(module support), many projects are not in the GOPATH, kitgen should support Working outside the GOPATH.

**Comment by navono** [comment]
Is there any progress ?

**Comment by maeglindeveloper** [comment]
I would be interested as well for an update on that topic :).
Any news?

**Comment by peterbourgon** [comment]
Rest assured that if and when there are updates, they will be posted here.

**Comment by kaydxh** [comment]
> With the release of Go 1.11(module support), many projects are not in the GOPATH, kitgen should support Working outside the GOPATH.

Yea, I have the same problem. Is kitgen must run inside GOPATH?

**Comment by wshihdehx** [comment]
I also get: "ERRO[0000] The project must be in the $GOPATH/src folder for the generator to work."

Is this still being worked on? It's been 2 years already, is go-kit still in active development or is it abandoned?
