### ISSUE TITLE
how to use embed etcd with go-kit

### ISSUE THREAD

**Issue by vtolstov** [go-kit/kit#781]
As i see go-kit when use etcd expected to already have etcd instance running. But how to deal if i want to use embed etcd inside app?

**Comment by peterbourgon** [comment]
Embedding etcd inside a Go kit application is

- Probably not advisable
- Certainly beyond the scope of Go kit :)

**Comment by vtolstov** [comment]
=( as i see no go microservice packages have ability to control full aspects of app, but only standard.
