### ISSUE TITLE
Requesting New Release

### ISSUE THREAD

**Issue by Lsquared13** [go-kit/kit#791]
Hi, I was hoping you could create a new release sometime soon. Last one is ~8 months old and doesn't have [an important fix I need](https://github.com/go-kit/kit/commit/631bc1e46272a71b3fbdd253d967aa0f560c9ed3). The JSON RPC transport seems effectively broken in the last release.

Right now `master` branch works for me, but that means this dependency may change between builds. I'd greatly appreciate a new release we could depend on instead.

Thank You!

**Comment by peterbourgon** [comment]
https://github.com/go-kit/kit/releases/tag/v0.8.0
