### ISSUE TITLE
Add correlation to logs

### ISSUE THREAD

**Issue by madshov** [go-kit/kit#792]
Hi!
I would be nice to be able to add a correlation-id per request to all logs including the ones created in `ServeHTTP` method. Currently errors returned from an endpoint will not have any correlation-id:
```
response, err := s.e(ctx, request)
if err != nil {
	s.logger.Log("err", err)
	s.errorEncoder(ctx, err, w)
	return
}
```
It could just be the request-id from the context. I don't see how it's possible to add it in these cases. If it can be done, I would appreciate, if you would let me know.

**Comment by sagikazarmark** [comment]
After #863 is merged, you will be able to put correlation information into the context and use it in the error handlers.

**Comment by madshov** [comment]
This is now possible in v. 0.9.0 using a custom error log handler.
