### ISSUE TITLE
Improve span name and add route parameters as tags for traces in zipkin

### ISSUE THREAD

**Issue by jcchavezs** [go-kit/kit#794]
Some route parameters are very useful to filter traces. For example, in the route `/artists/abc123/songs` one might be able to filter all traces for artist `abc123` for the span name `/artists/{artist_id}/songs` (keeping low cardinality). This in courter part of look up for `http.path=/artists/abc123/songs`.

This is nothing new, not so long ago [zipkin released](https://github.com/openzipkin/zipkin/releases/tag/2.5.0) the tag `http.route` (disclaimer: I am not saying other tracers did not) and suggested to use the route template for span name of http requests in server side.

The outcome of this issue (if not get discarded) should be whether this is a nice to have in this library and a rough idea on where to write this. IMHO this could be perfectly a `ServerAfter` option but the way we access to the route variables depends on the router, for example if using gorilla:
```go

func RichRouteTracing(params []string) RequestFunc{
    return func(ctx context.Context, r *http.Request) context.Context {
        span := zipkin.SpanFromContext(ctx)
        if span == nil {
            return ctx
        }
        
        vars := mux.Vars(r)
        for _, key := range params {
        	if val, ok := vars[key]; ok {
                span.Tag(param, val);
            }
        }

        return ctx
    }
}
```

Ping @basvanbeek @adriancole

**Comment by basvanbeek** [comment]
Personally I find this something that is not valuable enough in a generic implementation to add as standard piece of the Go kit Zipkin middleware. I do find the type of logic very valuable but it just needs customization by the end user as different routers / api logic is used (so as a custom platform add-on middleware, allowing to filter out items that are low value or sensitive in nature). Perhaps a more elaborate Zipkin instrumented example highlighting this and a few other items makes sense as you then can focus on idiomatic Zipkin instrumentation with Go kit which people can use as a base of inspiration.
