### ISSUE TITLE
Question: Why is DefaultCaller SkipFrame 3?

### ISSUE THREAD

**Issue by mattc41190** [go-kit/kit#795]
In the profivleSvc example code (specifically in the `main` func) there is a `log.With` call which includes `caller` set to `DefaultCaller` which is just `Caller(3)` if I am not mistaken.

This is likely a "How do computers work" question more than a GoKit question, but how do you know which data frame to inspect?

Am I missing the point completely?

Source:

https://github.com/go-kit/kit/blob/master/examples/profilesvc/cmd/profilesvc/main.go#L25

**Comment by ChrisHines** [comment]
Let's write a little test program to figure this out:

#### logtest.go:
```go
package main

import (
	"os"

	"github.com/go-kit/kit/log"
)

func main() {
	logger := log.NewLogfmtLogger(os.Stdout)
	for depth := 0; depth <= 3; depth++ {
		l := log.With(logger, "caller", log.Caller(depth))
		l.Log("depth", depth) // line 13
	}
}
```

The above program produces the output shown below. I've linked the source positions to the corresponding log package code so you can click through and follow the call sequence for yourself.

>caller=[value.go:86](https://github.com/go-kit/kit/blob/master/log/value.go#L86) depth=0
>caller=[value.go:20](https://github.com/go-kit/kit/blob/master/log/value.go#L20) depth=1
>caller=[log.go:122](https://github.com/go-kit/kit/blob/master/log/value.go#L20) depth=2
>caller=logtest.go:13 depth=3

From this we can see that `depth == 3` is the depth that skips the uninteresting stack frames within the log package and lands on the line of code in the application that called the `Log` method.

There is additional explanation in [this comment](https://github.com/go-kit/kit/blob/master/log/log.go#L76) in the log package code.

Hope that helps.

**Comment by mattc41190** [comment]
<3
