### ISSUE TITLE
sd/etcdv3 keepalive channel not served

### ISSUE THREAD

**Issue by fangdingjun** [go-kit/kit#799]
https://github.com/go-kit/kit/blob/e0e1b245b9bab0ee37b2a2d4daaf15ae674c3740/sd/etcdv3/client.go#L202

the channel c.hbch not served, etcd library print a lots of log like this, every 3 seconds
>{"level":"warn","ts":1542791960.4143248,"caller":"clientv3/lease.go:524","msg":"lease keepalive response queue is full; dropping response send","queue-size":16,"queue-capacity":16}
>{"level":"warn","ts":1542791963.92008,"caller":"clientv3/lease.go:524","msg":"lease keepalive response queue is full; dropping response send","queue-size":16,"queue-capacity":16}
>{"level":"warn","ts":1542791967.4572115,"caller":"clientv3/lease.go:524","msg":"lease keepalive response queue is full; dropping response send","queue-size":16,"queue-capacity":16}

**Comment by DOVECYJ** [comment]
The KeepAlive function will return a channel and an error for you. And you should continue to receive value from the channel. Like this:
=====================================
ch, kaerr := cli.KeepAlive(context.TODO(), resp.ID)
if kaerr != nil {
    log.Fatal(kaerr)
}
go func() {
    for {
        ka := <-ch
        fmt.Println("ttl:", ka.TTL)
    }
}
=====================================

**Comment by DOVECYJ** [comment]
The KeepAlive function will return a channel and an error for you. And you should continue to receive value from the channel. Like this:
``` golang
ch, kaerr := cli.KeepAlive(context.TODO(), resp.ID)
if kaerr != nil {
    log.Fatal(kaerr)
}
go func() {
    for {
        ka := <-ch
        fmt.Println("ttl:", ka.TTL)
    }
}
