### ISSUE TITLE
Add error tag to spans on OT endpoint middleware

### ISSUE THREAD

**Issue by jlordiales** [go-kit/kit#804]
Hi!
I think it would be useful for the OpenTracing endpoint middleware (https://github.com/go-kit/kit/blob/master/tracing/opentracing/endpoint.go) to inspect the `error` returned by the next endpoint and set the `error` tag to true/false accordingly (it could also optionally set the `error.object` log field).
In addition to just inspecting the returned `error` it could also check if the `response` struct implements `endpoint.Failer` and apply the same logic.

If you think this would be useful I'd be happy to create a PR, just wanted to get your thoughts first.

**Comment by peterbourgon** [comment]
@basvanbeek?

**Comment by basvanbeek** [comment]
Makes sense to add. The OpenCensus middleware already does somethjng similar with the status object and also inspects the endpoint.Failer checks.

**Comment by jlordiales** [comment]
Great, I'll create a PR this week.
