### ISSUE TITLE
Where to set Location header for create requests

### ISSUE THREAD

**Issue by madshov** [go-kit/kit#806]
Hi All,

I'm not able to see how to set the Location header of the created resource for POST requests:
I have an response encode function for my create resource handler:
```
func encStatusCreatedResponse(ctx context.Context, w http.ResponseWriter, r interface{}) error {
	if response, ok := r.(resp); ok {
		w.WriteHeader(http.StatusCreated)
		w.Header().Set("Location", "http://xyz.com/abc")
		return json.NewEncoder(w).Encode(response)
	}
	return nil
}
```
But this won't work. Moving the set Location call to a `ServerResponseFunc()` for `ServerAfter()` I'm not able to get id of the created resource. It seems like the only option is to add the resource id to the context in the endpoint and then create a `ServerResponseFunc()` that pulls out the value and set the header. But is that even possible?

**Comment by basvanbeek** [comment]
See: https://golang.org/pkg/net/http/#ResponseWriter
```
// Header returns the header map that will be sent by
// WriteHeader. The Header map also is the mechanism with which
// Handlers can set HTTP trailers.
//
// Changing the header map after a call to WriteHeader (or
// Write) has no effect unless the modified headers are
// trailers.
```

**Comment by madshov** [comment]
Got it thanks.
