### ISSUE TITLE
Question about Logger.Log()

### ISSUE THREAD

**Issue by cameron-elliott** [go-kit/kit#816]
I came across go-kit/kit/log while looking for a logger for a project, and I really like the design.
... Surprise, surprise, here comes the ask, but it's not too bad ...

I would like to see my Log() call kv-pairs in front of the contextual kv-pairs.
So, for this code:
`	logger = log.With(logger, "instance_id", 123)
	logger.Log("msg", "starting")`

instead of generating: "instance_id=123 msg=starting"
I would like to see: "msg=starting instance_id=123"

I could not figure out a way to do this without hacking on the kit/log/log.go file.

Am I missing seeing a way to get this output?
Thank you,
Cameron

**Comment by nelz9999** [comment]
I believe what you're looking for _may_ be `log.WithPrefix(...)`: https://github.com/go-kit/kit/blob/master/log/log.go#L50

**Comment by ChrisHines** [comment]
There is no way to do what you're trying to do with the existing tools in
this package.

I am curious what the benefit of this alternate ordering of the keyvals is.

**Comment by cameron-elliott** [comment]
Okay, well, I was able to implement it by duplicating logfmt_logger.go and tweaking my own implementation.

As far as benefit, well, I do a fair bit of production dev-ops work with lots of logging, and,
I'd just like to see if seeing the message part in front of 40+ characters of contextual info
is easier to work with. Ie, the UTC-time, level, other context key-values, etc.

It may not turn out to be worth it relative to the standard format, 
but I'd just like to explore it in my operations work.

Thanks for sharing such a nice logging package.
