### ISSUE TITLE
How to deal the method decodeHTTPSumRequest error

### ISSUE THREAD

**Issue by bthl21165** [go-kit/kit#817]
In the method decodeHTTPSumRequest, if the type of your param is string, the method will return error "json: cannot unmarshal string into Go struct field SumRequest.A of type int". And in the file of "server.go" will print error message "ts=2019-01-01T08:21:22.223306Z caller=server.go:105 err="json: cannot unmarshal string into Go struct field SumRequest.A of type int"". In fact, I want to deal with the error and the file of "server.go" do not need to print  error log. How to do it?

**Comment by peterbourgon** [comment]
Modify decodeHTTPSumRequest and/or the SumRequest type to accept strings instead of ints.
