### ISSUE TITLE
Question: Using Request and Response structures for Service interface

### ISSUE THREAD

**Issue by bnlong4417** [go-kit/kit#822]
Hello,

I understand the Endpoint is defined as an abstraction RPC with Request and Response structures. At the Endpoint we pass fields of Request as parameters to Service then make a Response from the result. 

In some cases, I have Request and Response with many fields or I want to validate the Request at service layer, so I must create the same structs for mapping Request or Response.

I wonder: "Should we use `Request` as a parameter and `Response` as a result and define them at the Service layer?"

**Comment by peterbourgon** [comment]
There is no correct answer. You can certainly define request and response types in the innermost service layer, and use them directly in the transport layers. This has the benefit of requiring fewer types to be defined, but the drawback is the service layer is "polluted" with details about the transport, a violation of the clean/hexagonal architecture rule of inward-facing dependencies.
