### ISSUE TITLE
Question about grpc headers

### ISSUE THREAD

**Issue by madshov** [go-kit/kit#823]
Hi,

Is there a generic function to move grpc request metadata to context? I can only see a specific one for JWT to and from context.
thanks

**Comment by basvanbeek** [comment]
We have dedicated before/after handlers in the gRPC transport for this. See:

https://github.com/go-kit/kit/blob/master/transport/grpc/request_response_funcs.go

For examples of this being used look at for instance the Zipkin tracing packages as with tracing the trace identifiers (SpanContext) is being propagated all the way through.

**Comment by madshov** [comment]
Thanks,
I don't see any dedicated functions returning a `ServerRequestFunc`, so to go from metadata to context, I'll implement my own.
