### ISSUE TITLE
Why use go-kit over normal gRPC?

### ISSUE THREAD

**Issue by nhooyr** [go-kit/kit#824]

**Comment by peterbourgon** [comment]
Go kit provides (among other things) a set of abstractions that enable one service to be accessible over multiple transports (e.g. gRPC, Thrift, regular JSON/HTTP, etc.) simultaneously. If your service will only ever speak gRPC, and you don't care about other benefits given to you by the Go kit architecture, then I guess there's no reason to use it.

**Comment by nhooyr** [comment]
I guess my question is that if I don't care about multiple transports, what else does go-kit provide me?
