### ISSUE TITLE
Question: How is go-kit different from go-grpc-middleware?

### ISSUE THREAD

**Issue by jpaulodit** [go-kit/kit#828]
Hi, I am trying to understand how go-kit is different from go-grpc-middlware, other than the fact go-kit supports other types of transport method. It seems both uses the decorator pattern, and have similar features like logging, auth, metrics, etc.. I am using grpc for my project and having a hard time understanding the difference between the 2.

Any help is appreciated. Thank you.

**Comment by peterbourgon** [comment]
What is go-grpc-middlware?

**Comment by jpaulodit** [comment]
This is the repo I was talking about. https://github.com/grpc-ecosystem/go-grpc-middleware

**Comment by peterbourgon** [comment]
That repo presumes your service is only speaking gRPC, and that the gRPC layer is an appropriate place to wire in middlewares for all of the various concerns. Go kit allows your service to speak multiple transports, and provides hooks for middleware at a variety of layers, not just transport. If those properties aren't interesting to you, then there is no reason to use Go kit.
