### ISSUE TITLE
configurable level logrus logging

### ISSUE THREAD

**Issue by zkanda** [go-kit/kit#829]
Hi, is it possible to extend the logger to make logging with different kind of log level via logrus?

If anyone have a hint on how to do this, I would be glad to do the implementation. :)

**Comment by peterbourgon** [comment]
https://godoc.org/github.com/go-kit/kit/log/level

```go
var logger log.Logger
logger = log.NewLogfmtLogger(os.Stdout)
logger = level.NewFilter(logger, level.AllowInfo())

level.Debug(logger).Log("msg", "this will not be printed")
level.Info(logger).Log("msg", "this will be printed")
```

**Comment by spirosoik** [comment]
@peterbourgon ^ this doesn't work for the logrus package which exists under log package or I am missing something. for kitlog works without an issue the above, but logrus implementation doesn't respect this.

**Comment by peterbourgon** [comment]
The log/logrus.Logger doesn't support dynamic levels in the sense you mean. It would be tricky to solve generally, because logrus has well-defined levels (Info, Error, Debug, Warn, Trace), and Go kit's concept of levels is essentially arbitrary.
