### ISSUE TITLE
Issue on custom grpc response headers

### ISSUE THREAD

**Issue by madshov** [go-kit/kit#833]
Hi All,
I have a problem setting a response header for a grpc response. I'm getting the following error:
`panic: assignment to entry in nil map`

These are my server options:
```
func NewGRPCServer(ept oept.Endpoints, logger kitlog.Logger) pb.OptionServiceServer {
	opts := []kitgrpctransport.ServerOption{
		kitgrpctransport.ServerErrorLogger(level.Error(logger)),
		kitgrpctransport.ServerBefore(populateGRPCRequestContext()),
		kitgrpctransport.ServerAfter(SetResponseHeader("foo", "bar")),
	}
```

This suggests that the `metadata.MD` maps (header, trailer) are never initialized, only declared as in server.go:
`var mdHeader, mdTrailer metadata.MD`

Have I missed something?

**Comment by basvanbeek** [comment]
It is correct that by default mdHeader and mdTrailer are not initialized, they don't have to be. The idea is to use `metadata.Join` in each response middleware you add. Here is a small example of a Header and a Trailer middleware:

```go
func setResponseHeader(key, value string) grpctransport.ServerResponseFunc {
	return func(ctx context.Context, header *metadata.MD, _ *metadata.MD) context.Context {
		*header = metadata.Join(*header, metadata.Pairs(key, value))
		return ctx
	}
}

func setResponseTrailer(key, value string) grpctransport.ServerResponseFunc {
	return func(ctx context.Context, _ *metadata.MD, trailer *metadata.MD) context.Context {
		*trailer = metadata.Join(*trailer, metadata.Pairs(key, value))
		return ctx
	}
}
```

**Comment by madshov** [comment]
Thanks, I see now.
That was really helpful.
