### ISSUE TITLE
Context threading between services (e.g. request ID)

### ISSUE THREAD

**Issue by seonixx** [go-kit/kit#835]
>The context object is used to carry information across conceptual boundaries in the scope of a single request. In our example, we haven’t yet threaded the context through our business logic.

I noticed there doesn't appear to be any example of context threading in the documentation, and the brief mention of it in example has been removed.

Given a simple use case such as passing a request ID between services - can someone give a barebones example of how this should be achieved in go-kit, assuming using context.Context?

I was attempting to attach the context to my request on my RPC client - but can't figure out how to attach it to the request on the server endpoint...

```go
func encodeHTTPGenericRequest(ctx context.Context, r *http.Request, request interface{}) error {
	var buf bytes.Buffer

	if err := json.NewEncoder(&buf).Encode(request); err != nil {
		return err
	}

	r.Body = ioutil.NopCloser(&buf)

        // added this to pass to the server endpoint
	r = r.WithContext(ctx)

	return nil
}
```

**Comment by seonixx** [comment]
I assumed up until trying to implement it that the context used through the service definitions etc would simply be propagated across service boundaries using go-kit instrumentation but either it's not or I've done something wrong.

**Comment by basvanbeek** [comment]
So data residing in context.Context does not automatically cross service boundaries. You'll need to write middleware for extracting information from context and place in transport headers on the client side and on the server side write middleware to extract header information and place in context.
We have the ClientBefore and ServerBefore hooks to make this easy.

Luckily there is a small example of service to service propagation in the gRPC transport:
https://github.com/go-kit/kit/tree/master/transport/grpc/_grpc_test

**Comment by seonixx** [comment]
Thanks @basvanbeek - that example was helpful. Added ClientBefore and ServerBefore hooks with the httptransport methods.
