### ISSUE TITLE
Panic in log package

### ISSUE THREAD

**Issue by husio** [go-kit/kit#84]
`kit/log` package is using `panic` in several places, that are executed conditionally. While the code that is causing it (odd number of key-value pair elements) is logically invalid, `panic` is not something expected by external package, especially logging.
Odd number of elements means that there is one key with no value. My proposal is to pair such key with empty value. While it's not perfect, it does not break the code and can be detected later while looking at logs or by code analyzers. 
Similar logic is provided for example by `fmt` package - [using `XXXf` with invalid amount of parameters](http://play.golang.org/p/wq2D1_IybJ)  does not panic, but rather produce result with warning. Wrong parameters are also detected by [go vet](http://godoc.org/golang.org/x/tools/cmd/vet#hdr-Printf_family). 

* https://github.com/go-kit/kit/blob/master/log/log.go#L47
* https://github.com/go-kit/kit/blob/master/log/log.go#L61
* https://github.com/go-kit/kit/blob/master/log/log.go#L82

**Comment by peterbourgon** [comment]
@ChrisHines what do you think?

```diff
 if len(keyvals)%2 != 0 {
-    panic("bad keyvals")
+    keyvals = append(keyvals, "(MISSING)")
 }
```

**Comment by husio** [comment]
I don't have any preferences here. I think `(MISSING)` is easier to spot when browsing logs than empty string or `nil`. 
:+1:

**Comment by tsenart** [comment]
+1

**Comment by ChrisHines** [comment]
I agree that we should remove these panics.

In [logfmt.MarshalKeyvals](https://github.com/go-logfmt/logfmt/blob/master/logfmt.go#L20) I appended `nil` in this scenario. That package logs a `nil` value the same as JSON (i.e. "null").

At the slightly higher level of abstraction here in the `log` package it seems reasonable to provide a more helpful indicator. I would also like to make it easy for applications to control how a missing value is ultimately handled, so I don't like a "magic" string.

I propose adding an exported error variable that is appended and can be checked by a downstream logger if a different behavior is desired.

```go
var ErrMissingValue interface{} = errors.New("(MISSING)")
```
