### ISSUE TITLE
Async (non-RPC) AMQP transport

### ISSUE THREAD

**Issue by madshov** [go-kit/kit#841]
Hi All,

Any documentation/examples that exist around AMQP transport, subscriber/publisher?

Thanks

**Comment by madshov** [comment]
More specifically, I'm just interested in using RabbitMQ as a simple message broker. Receive a message and ACK it, if OK. I can see that the ServeDelivery() on the subscriber will respond to incoming messages, like RPC fashion. I'm not interested in the sending the response. Can I ignore it or could that cause any problems?

**Comment by peterbourgon** [comment]
[See previous discussion here](https://github.com/go-kit/kit/pull/746#issuecomment-454909761). As I understand it, it would be possible to add an option to transport/amqp to not require a response, but it's not currently implemented.

**Comment by madshov** [comment]
Thanks Peter.
So if I understand you correctly, within go-kit, you are only considering AMQP transport if it does RPC?
If I want true one-way communication, it would be something I have to build on the side. That is, if I don't choose to send back an empty response with the `EncodeNopResponse()`.

/mads

**Comment by peterbourgon** [comment]
At the moment, yes. But it sounds like it would be relatively easy to enhance the AMQP package to not require a response.

**Comment by peterbourgon** [comment]
I think #850 makes this fixed. If that's not the case, please re-open with details.

**Comment by FabianTe** [comment]
@madshov I am interested in how you handled one-way communication. I'd like to implement a Go-based worker for a legacy system that uses RabbitMQ as a worker queue. In this scenario I also don't want to send a response.

Did you sucessfully implement this?

**Comment by madshov** [comment]
Hi @FabianTe,
Yes I have successfully implemented @mattfung additions in go-kit v0.9.0 (i believe)
