### ISSUE TITLE
new project based on go-kit

### ISSUE THREAD

**Issue by meysam81** [go-kit/kit#844]
hello devs,

I have recently written a project using go-kit, and you may hear it a lot and may not look like a surprise to you.
But just to try my luck, I was wondering if you would mention [the project](https://github.com/meysam81/amadeus-go) in your examples.

Cheers,
And happy coding :smiley:

**Comment by peterbourgon** [comment]
Thanks. Please use the mailing list or Slack room for info like this in the future.
