### ISSUE TITLE
kit/metrics/cloudwatch2: fails to build

### ISSUE THREAD

**Issue by h8liu** [go-kit/kit#856]
```
# github.com/go-kit/kit/metrics/cloudwatch2
src/github.com/go-kit/kit/metrics/cloudwatch2/cloudwatch2.go:169:22: not enough arguments in call to req.Send
	have ()
	want (context.Context)
```

Break found by [gopkgs.io](https://gopkgs.io):
https://gopkgs.io/builds/20190406-041800-2e1199d6

**Comment by peterbourgon** [comment]
@nelz9999 Can you look at this one?

**Comment by eclipseo** [comment]
Related to this commit I presume: https://github.com/aws/aws-sdk-go-v2/commit/efe43a422d32d48957ab45308c7e2e3b74452e46

**Comment by nelz9999** [comment]
👀

**Comment by PaulLiang1** [comment]
Is there is release for this one? 
The current cloudwatch2 is not useable.

**Comment by peterbourgon** [comment]
It's fixed in master.
