### ISSUE TITLE
Panic when logging nil pointer to error with JSON formatter

### ISSUE THREAD

**Issue by husio** [go-kit/kit#86]
When logging, every value is checked if it implements error interface. When positive, Error method is called. This may cause panic when passed value is `nil` pointer to structure that use it's internal state to produce Error method optput.

**Comment by peterbourgon** [comment]
Does this test case capture the behavior you describe?

```go
type Foo struct { 
    msg string 
}

func (f *Foo) Error() { 
    return fmt.Errorf("%s", f.msg) 
}

func main() {
    var f *Foo // nil
    logger.Log("foo", f)
}
```

**Comment by peterbourgon** [comment]
Oh, I see the PR now. Disregard my question.

**Comment by ChrisHines** [comment]
This JSON logging code has other insidious nil panic issues. For example this test will panic as well:

```go
type stringStringer string

func (s stringStringer) String() string {
	return string(s)
}

func TestJSONLoggerNilPointers(t *testing.T) {
	buf := &bytes.Buffer{}
	logger := log.NewJSONLogger(buf)
	if err := logger.Log((*stringStringer)(nil), "v"); err != nil {
		t.Fatal(err)
	}
	if want, have := `{"null":"v"}`+"\n", buf.String(); want != have {
		t.Errorf("want %#v, have %#v", want, have)
	}
}
```

I have dealt with the same issue maintaining log15. I found that recovering the panic is the best approach. See also: https://github.com/inconshreveable/log15/issues/46.

I will add some comments regarding implementation on the PR.
