### ISSUE TITLE
package github.com/go-kit/kit: no Go files in /home/mm/go/src/github.com/go-kit/kit

### ISSUE THREAD

**Issue by MilenkoM** [go-kit/kit#864]
I have problems with install

> go get -u github.com/go-kit/kit
> package github.com/go-kit/kit: no Go files in /home/mm/go/src/github.com/go-kit/kit

Why?

**Comment by MilenkoM** [comment]
I am on Ubuntu 18.04.

> go version
> go version go1.10.4 linux/amd64

**Comment by peterbourgon** [comment]
```
go get -u github.com/go-kit/kit/...
```
