### ISSUE TITLE
ElasticSearch support for go-kit Logger

### ISSUE THREAD

**Issue by shkov** [go-kit/kit#867]
Do you want to make it possible to send logs to elastic by interval? Logrus allows you to do this through a `logger.Hooks.Add(hook)` and by helper packages like https://github.com/sohlich/elogrus

**Comment by ChrisHines** [comment]
I think it would be interesting to see some design ideas for this. Hopefully it could be implemented as a `log.Logger` wrapper or middleware. Is this something you would like to work on and contribute?

**Comment by shkov** [comment]
Yes, it's interesting for me. I will try to implement this in the near future.

**Comment by shkov** [comment]
I have some design doubts.
I am going to make a `log.Logger` wrapper, which will send logs to elastic by `BulkProcessor` https://github.com/olivere/elastic/wiki/BulkProcessor. Should it look like I pass the elastic client inside the wrapper, or should I connect to the elastic inside? I think the second option is better, since the connection loop is needed because the elastic client returns an error if elastic is not available. Maybe I should pass an interface with single method like sendBatch() inside?

**Comment by peterbourgon** [comment]
Although I'm happy to review a design doc and/or PR, I'm really dubious that this kind of functionality belongs in core Go kit. My intuition is that it's much better as a third-party adapter.
