### ISSUE TITLE
NATS publisher context

### ISSUE THREAD

**Issue by l-vitaly** [go-kit/kit#869]
Hello!

In this place https://github.com/go-kit/kit/blob/master/transport/nats/publisher.go#L67

there is a string: `ctx, cancel := context.WithTimeout(context.Background(), p.timeout)`

apparently there is an error and need:

`ctx, cancel := context.WithTimeout(ctx, p.timeout)`

?

**Comment by peterbourgon** [comment]
Probably, yep.
