### ISSUE TITLE
Error bubbling

### ISSUE THREAD

**Issue by piotrkowalczuk** [go-kit/kit#87]
Hi,

case that is covered already by `log` package is passing `log.Log` instance deeper into dependency tree. But what about bubbling error up. I would like to propose new feature called `LoggableError`.

```go
package log

type LoggableError struct {
    Err error
    Fields []interface{} // maybe a map?
}

func (le *LoggableError) Error() string {
    return le.Err.Error()
}
```

Using this struct we can wrap any error with extra fields and bubble it up so it can be logged in a single place with all gathered fields eg.:

```go
func extendLoggerWithError(logger Log, err error) logger {
    	switch e := err.(type) {
	case *pq.Error:
                return log.With(logger, "code", e.Code, "details", e.Detail, "hint", e.Hint, "table", e.Table, "constraint", e.Constraint)
	case *log.LoggableError:
		return extendLoggerWithError(log.With(logger, e.Fields...), e.Err)
	default:
		return logger
	}

	return logger
}
```

**Comment by ChrisHines** [comment]
Is the `LoggableError` type really needed?

It seems to me that an application could include a custom `Logger` that inspected error values for concrete types it cared about and added more details to the context as desired. For example (untested):

```go
func NewExpandErrorsLogger(logger log.Logger) log.Logger {
    return log.FuncLogger(func(keyvals ...interface{}) error {
        lc := log.NewContext(logger).With(keyvals...)
        for i := 1; i < len(keyvals); i += 2 {
            switch e := keyvals[i].(type) {
            case *pq.Error:
                lc = lc.With("code", e.Code, "details", e.Detail, "hint", e.Hint, "table", e.Table, "constraint", e.Constraint)
            }
        }
        return lc.Log()
    })
}
```

If such a logger were installed as middleware by the application, then logging a `*pq.Error` value from anywhere in the application would cause the additional details to get added prior to the final output of the log event.

Are there other ways to use the proposed type that cannot be solved by logging middleware? Have I missed the point entirely?

**Comment by piotrkowalczuk** [comment]
Lets say your code executes in that order (it starts from place where error occurred):

```go
pq.Row.Scan(interface{}...) error
ResourceRepository.FindOne(map[string]interface{}) (*Resource, error)
ResourceEndpoint(context.Context, interface{}) (interface{}, error)
ResourceHandler.ServeHTTP(http.ResponseWriter, *http.Request)
ResourceHandler.extendLoggerWithError(log.Log, error) log.Log
log.Log.Log(string, interface{}...) error
```

`pq.Error` returned by the driver gives some insight whats happen but just a little bit. I would like to add extra fields in repository, in that case query params and maybe entire query, or even method name where it happened. Same for next steps.

In conclusion there would be two ways to handle logging. For debugging purposes logger instance would be injected and executed in specific place. But when error occurred it would be passed back and handled in single place.

With your  approach i would need to pass logger instance up and then return it back.

**Comment by peterbourgon** [comment]
From what I understand, this really has nothing to do with `package log`, and everything to do with adding labels (read: context) to errors. I'd suggest approaching it from that angle, either by implementing your own ContextualError type, or looking into error-enhancing packages like [juju/errors](https://github.com/juju/errors) or [juju/errgo](https://github.com/juju/errgo).

**Comment by piotrkowalczuk** [comment]
@peterbourgon true, so maybe then `log/logutil` package?

**Comment by peterbourgon** [comment]
@piotrkowalczuk If anything it would be a completely separate `package errors`, but I think that's not a core concern of Go kit.

**Comment by ChrisHines** [comment]
@piotrkowalczuk, I agree with @peterbourgon that the capability you are requesting is outside the scope of `package log`.
