### ISSUE TITLE
How do u test gokit endpoint

### ISSUE THREAD

**Issue by chaudharisuresh997** [go-kit/kit#871]
Can u please post and test where u are testing an endpoint of gokit.

**Comment by peterbourgon** [comment]
An endpoint is just a function like any other, so you can create a mock service, generate endpoints for it, and test the inputs and outputs of those functions, just like any other unit test. For a more comprehensive approach, [here is an example of an end-to-end "wireup" test](https://github.com/go-kit/kit/blob/master/examples/addsvc/cmd/addsvc/wiring_test.go). 

Is there something more specific you want to test?
