### ISSUE TITLE
Can you add hprose support?

### ISSUE THREAD

**Issue by andot** [go-kit/kit#88]
https://github.com/hprose/hprose-go

Hprose is a High Performance Remote Object Service Engine.

It is a modern, lightweight, cross-language, cross-platform, object-oriented, high performance, remote dynamic communication middleware. It is not only easy to use, but powerful. You just need a little time to learn, then you can use it to easily construct cross language cross platform distributed application system.

Hprose supports many programming languages, for example:

* AAuto Quicker
* ActionScript
* ASP
* C++
* Dart
* Delphi/Free Pascal
* .NET(C#, Visual Basic...)
* Golang
* Java
* JavaScript
* Node.js
* Objective-C
* Perl
* PHP
* Python
* Ruby
* ...

Through Hprose, You can conveniently and efficiently intercommunicate between those programming languages.

**Comment by peterbourgon** [comment]
What would "support" look like?

**Comment by andot** [comment]
I means that add an example in [addsvc](https://github.com/go-kit/kit/tree/master/addsvc), such as thrift, grpc, etc.

**Comment by peterbourgon** [comment]
Ah, so it's basically just a transport? Would you be willing to make a pull request, illustrating how to use it in addsvc? If you get stuck, I'd be happy to answer questions, or provide code samples.

**Comment by andot** [comment]
OK, I will try to do it. Thank you. :smile:

**Comment by peterbourgon** [comment]
I'll close this issue pending a PR. Thanks!
