### ISSUE TITLE
grpctransport.ServerErrorHandler

### ISSUE THREAD

**Issue by dariogum** [go-kit/kit#880]
Hi!

Trying the `addsvc` example, and after doing `dep init && dep ensure` i found that the line https://github.com/go-kit/kit/blob/e75cc1ab0282c013188f87a858f066ccd6cedbf1/examples/addsvc/pkg/addtransport/grpc.go#L48 is producing an error, because the method `ServerErrorHandler` is not present in the code version v0.8.0.

Can yo check this please? Thanks!

**Comment by peterbourgon** [comment]
Please update to a more recent version of Go kit. This may require pinning to an explicit newer revision. I'll make an 0.9.0 release at some point, but not in the immediate future.
