### ISSUE TITLE
v0.9.0 introduced breaking API change in metrics package

### ISSUE THREAD

**Issue by mjneil** [go-kit/kit#890]
https://github.com/go-kit/kit/pull/837 included in the 0.9.0 release introduced breaking API changes for the metrics package, but this wasn't documented in the changelog in any way. Could you please update the release log to highlight this. I know its v0 so semver rules aren't really being broken, but it should be documented so users aren't trying to figure out why their builds a breaking.

**Comment by peterbourgon** [comment]
Apologies for that.

**Comment by peterbourgon** [comment]
I've updated [the release page](https://github.com/go-kit/kit/releases/tag/v0.9.0) with a big disclaimer. Again, very sorry.

**Comment by mjneil** [comment]
@peterbourgon Thanks for the quick update
