### ISSUE TITLE
grpc and context issue

### ISSUE THREAD

**Issue by madshov** [go-kit/kit#891]
Hi,

I have a problem with context and gRPC, which some of you might have a solution to.
I have a gRPC server with an endpoint called setup. When a request comes in, I populate the context with a request id from a request header using `ServerBefore` and a `serverRequestFunc`. This works fine: 
````
func NewGRPCServer(
	ept pept.Endpoints,
	options []kitgrpctransport.ServerOption,
	logger kitlog.Logger,
) pgpb.PaymentServiceServer {
	var (
		before = kitgrpctransport.ServerBefore(app.PopulateGRPCReqContext())
````
My request id is now available in the request decoder, response endcoder and my service.
But the problem arises in my transport handler. For example, my setup handler looks like:
````
func (s *GRPCServer) Setup(ctx context.Context, req *pgpb.SetupReq) (*pgpb.SetupResp, error) {
	_, resp, err := s.setup.ServeGRPC(ctx, req)
	switch err {
	case nil:
		return resp.(*pgpb.SetupResp), nil
	default:
		return nil, encErrorGRPCResp(ctx, err)
	}
}
````

In the case of a business logic error, I call the `encErrorGRPCResp` function. The problem here is that the context from this function seems to be a new context (ie. it doesn't contain my request id anymore). I suspect this context comes from my protobuffer file. Is there a way to get the original context or merge them somehow?

**Comment by basvanbeek** [comment]
Have you tried retrieving it from the context as returned by `newCtx, resp, err := s.setup.ServeGRPC(ctx, req)`?

**Comment by basvanbeek** [comment]
@madshov friendly ping... did you try the suggestion?

**Comment by madshov** [comment]
@basvanbeek yeah sorry I haven't replied, your suggestion was what I was looking for. Thanks.
Closing this ticket.
