### ISSUE TITLE
Is there a request params validator module?

### ISSUE THREAD

**Issue by NeoyeElf** [go-kit/kit#893]
see the topic

**Comment by peterbourgon** [comment]
No, but it should be trivial to add any one you like. If the input is an http.Request, then you'd call the validator in a ServerBefore function, or in your DecodeRequestFunc. If you want to validate your core domain types and params, you'd write a service middleware (like [any of these addsvc middlewares](https://godoc.org/github.com/go-kit/kit/examples/addsvc/pkg/addservice#Middleware)) for it.
