### ISSUE TITLE
Is there a access log?

### ISSUE THREAD

**Issue by NeoyeElf** [go-kit/kit#894]
Is there an access log logging the URI, request params&body&headers, used time and response status of requests? Thks !

**Comment by peterbourgon** [comment]
Not by default, but you can create your own by populating the relevant data into the context (see [PopulateRequestContext](https://godoc.org/github.com/go-kit/kit/transport/http#PopulateRequestContext) for an example) and writing an e.g. [ServerFinalizer](https://godoc.org/github.com/go-kit/kit/transport/http#ServerFinalizerFunc) to extract and log that information.
