### ISSUE TITLE
Log level field name

### ISSUE THREAD

**Issue by madshov** [go-kit/kit#896]
Hi All,
When using the logging package is it possible to use `severity` instead of `level` for log levels. GCP seems to only understand `severity`.

Thanks

**Comment by ChrisHines** [comment]
It is not possible to change the level key used by the `log/level` package with that package's API, but it is possible to write a `Logger` that changes the key before it gets output, which has the same overall effect. See #503 for an explanation why the `log/level` package does not allow changing the key and some example code for the suggested workaround.

**Comment by madshov** [comment]
Thanks for clarifying.
