### ISSUE TITLE
Suggestion: Continuous Fuzzing

### ISSUE THREAD

**Issue by yevgenypats** [go-kit/kit#904]
Hi, I'm Yevgeny Pats Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- [go-fuzz](https://github.com/dvyukov/go-fuzz) fuzzers (This is generic step not-connected to fuzzit)
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

**Comment by peterbourgon** [comment]
I am happy to bring fuzz testing into the project, but would like to better understand what the entrypoints would be. We don't have Parse functions, so to speak... do you have a standard strategy for fuzzing typical e.g. HTTP servers/endpoints?

**Comment by yevgenypats** [comment]
@peterbourgon thanks for the reply. I'm not yet too familiar with the code base yet. but from a quick look maybe some auth functions regarding jwt parsing. regarding http server testing we need to find specific functions as go-fuzz is an in-process coverage guided fuzzer and not a network fuzzer.

**Comment by peterbourgon** [comment]
@yevgenypats Sure. But could we launch an http.Server and have the fuzzer dump its []byte payload as a request body, for example?

**Comment by yevgenypats** [comment]
Not sure, I need to take a deeper look into this. will post here my observations ideas before implementing.

**Comment by yevgenypats** [comment]
Also, I need to mention that we have a reward program in case you have time/want to implement this yourself I would be happy to reward you as well as get unbiased feedback on how smooth the integration was. Let me know what you prefer.
