### ISSUE TITLE
gRPC.Dial() from within a factory causes goroutine leaks

### ISSUE THREAD

**Issue by ouanixi** [go-kit/kit#906]
Hi. I’ve got a goroutine leak in a new service I just implemented and I suspect it’s to do with where the `grpc.Dial()` is called (i.e inside the factory function) 
This means there's a new connection established each time the factory is called. And what I noticed is that not only the connections aren't closed but they're not reused either. Am I missing something here?

My factory is as follows:

```
func fooSrvFactory(makeEndpoint func(service.Service) kitendpoint.Endpoint, tracer opentracing.Tracer, rate int, logger log.Logger) sd.Factory {
    return func(instance string) (kitendpoint.Endpoint, io.Closer, error) {

        conn, err := grpc.Dial(instance, grpc.WithInsecure())
        if err != nil {
            return nil, nil, err
        }
        srv := tr.NewGRPCClient(conn, tracer, rate, logger)
        endpt := makeEndpoint(srv)
        return endpt, conn, nil
    }
}
```

What I see in my dashboards is an increase in the number of goroutines that never goes down.

I use the Client as a singleton in the calling application so every time `client.SomeEndpoint()` is called, there's a new grpc.Dial() call happening.

**Comment by peterbourgon** [comment]
Why do you have a factory function? Can you provide more context?

I see a lot of stuff in this example code that makes me raise my eyebrows. MakeEndpoint-style functions are meant to be called once when your program starts, not with every request. But I don't see why you need to do any of this grpc.Dial stuff in there — that's supposed to be done in the Go kit transport/grpc.Server type.

**Comment by ouanixi** [comment]
Thanks for your reply @peterbourgon . The question is now a bit irrelevant to be fair. It was my first few days learning go-kit and may have got certain things mixed up. I now expose a `New` function that returns a `client` making sure it's a singleton (using `sync.Once.Do`).

I've moved away from those factory functions and I honestly don't remember why i used them. Must have been an example that I misunderstood.
