### ISSUE TITLE
etcd func "WatchPrefix"  and  "GetEntries" only return value。can it return type、key、value？

### ISSUE THREAD

**Issue by mme1** [go-kit/kit#907]
<img width="553" alt="QQ20190830-152607@2x" src="https://user-images.githubusercontent.com/5811430/64001487-83b91f80-cb3a-11e9-94b9-4902aa58ebef.png">

this func only return value 
I need type、key、value

**Comment by peterbourgon** [comment]
package etcd is for service discovery. It assumes the address of the service represented by a key is completely within the value. Is that not true for you? What information is in type and key?

**Comment by mme1** [comment]
i use etcd for config center. 
Some sample code：
go func() {
		rch := client.GetOriClient().Watch(context.Background(), "prefix", clientv3.WithPrefix(), clientv3.WithRev(0))
		for wresp := range rch {
			for _, ev := range wresp.Events {
				switch ev.Type {
				case clientv3.EventTypePut:
					fmt.Printf("[%s] %q : %q\n", ev.Type, ev.Kv.Key, ev.Kv.Value)
					Tconfig[string(ev.Kv.Key)] = string(ev.Kv.Value)
				case clientv3.EventTypeDelete:
					fmt.Printf("[%s] %q : %q\n", ev.Type, ev.Kv.Key, ev.Kv.Value)
					delete(Tconfig,string(ev.Kv.Key))

				}
			}
		}
	}()

 ev.Type, ev.Kv.Key, ev.Kv.Value , this is what i need

**Comment by peterbourgon** [comment]
Go kit's package etcd and etcdv3 are not general-purpose etcd client libraries, they are explicitly only for service discovery.

**Comment by mme1** [comment]
ok,i know . thank you !
