### ISSUE TITLE
kitgen enhancement: generation of logging and metrics middlewares

### ISSUE THREAD

**Issue by shkov** [go-kit/kit#910]
I maintain a large enough project and i spend a lot of time when i write middlewares for collecting metrics or logs. I mean middlewares like this: 
```
https://github.com/go-kit/kit/blob/master/examples/stringsvc3/instrumenting.go#L10
```
or
```
https://github.com/go-kit/kit/blob/master/examples/stringsvc3/logging.go#L9
```
It may not necessarily be a wrapper over a service. Also I would like to be able to wrap various objects like storage or something else. 
Do you want to make it possible to generate some kinds of middlewares by kitgen? If you find this useful i would like to work on it and contribute.

**Comment by peterbourgon** [comment]
If you want to try I would happily review the PR, but I think kitgen is basically abandonware at this point, I'm not sure it's worth investing in.

**Comment by xescugc** [comment]
If it's not plan to work on kitgen, maybe would be good to remove/deprecate it from go-kit and also link on the README the possible solutions (some linked here https://github.com/go-kit/kit/issues/70).

WDYT?

**Comment by peterbourgon** [comment]
Probably a good idea.
