### ISSUE TITLE
 /log/level log processing question

### ISSUE THREAD

**Issue by JohnheCrypro** [go-kit/kit#911]
@flowchartsman  is the level of the /log/level log only four (Info, Debug, Error, Warn), normal our log level should be Print, Notice, Trace, Info, Debug, Warn, Error, Fatal, Panic, Critical, you are currently The original intention of this design is because of what.

**Comment by peterbourgon** [comment]
The current design of the log package, including the level sub-package, is relatively opinionated. I believe that too many log levels are actively harmful—even the existing 4 is a compromise, IMO [you should have only two](https://dave.cheney.net/2015/11/05/lets-talk-about-logging)!

With that said, you are free to implement your own `package level` with whatever levels your organization finds important. The package is relatively small, and composes with `package log` in a way that makes alternate implementations very easy to wire in.
