### ISSUE TITLE
Change log level in code?

### ISSUE THREAD

**Issue by hshorter** [go-kit/kit#918]
When using log levels as described here: https://godoc.org/github.com/go-kit/kit/log/level#example-package--Filtered

Is is possible to change the log level after the initial call to
`logger = level.NewFilter(logger, level.AllowInfo())`?

**Comment by ChrisHines** [comment]
You can add a [`log.SwapLogger`](https://godoc.org/github.com/go-kit/kit/log#SwapLogger) (or something similar) to the base logging stack and swap in different `level.NewFilter`s as needed.

**Comment by hshorter** [comment]
Thank you! So the strategy is to create a new logger with a filter at the desired level and use the SwapLogger to swap it in place.
