### ISSUE TITLE
HTTP Proxy Server Finalizer

### ISSUE THREAD

**Issue by Tapanito** [go-kit/kit#921]
In the current HTTP Proxy implementation there is no ServerFinalizer similar to the one in `transport/http` package. 

The use case for this feature is very similar to the one in `http` package. I want to add tracing information to proxied requests.

I would be more than happy to introduce this feature, if it's usefulness is agreed.

**Comment by peterbourgon** [comment]
What is the current HTTP proxy implementation you're referring to?
