### ISSUE TITLE
Add gokit to the service mesh landscape

### ISSUE THREAD

**Issue by leecalcote** [go-kit/kit#930]
Hi,

We would love to have gokit represented on the service mesh landscape here https://layer5.io/landscape. Will you consider a quick PR to add it? 

We ask project owners / maintainers to create their own listings, so that descriptions and the project's representation is as accurate as possible.

Thanks!

https://github.com/layer5io/layer5/issues/216

**Comment by basvanbeek** [comment]
Hi @leecalcote, congrats on the release of your book with @ZackButcher. I will take care of the listing for Go kit.

**Comment by leecalcote** [comment]
@basvanbeek Ha! Thank you. :) 

I appreciate you taking this issue on. 👍

**Comment by basvanbeek** [comment]
done per https://github.com/layer5io/layer5/pull/226
