### ISSUE TITLE
log level reset filter

### ISSUE THREAD

**Issue by jeffkbkim** [go-kit/kit#932]
is there no way to reset `level.NewFilter()`?
i can never reset the filter to a lower level.. is this really not possible?
```
	logger := log.NewJSONLogger(os.Stdout)
	logger = level.NewFilter(logger, level.AllowInfo())
	logger = level.NewFilter(logger, level.AllowDebug())
	level.Info(logger).Log("msg", "info level log")
        level.Debug(logger).Log("msg", "debug level log"))
```
expected: both info and debug logs
actual: info logs

**Comment by peterbourgon** [comment]
No, it's not possible to "reset" a log.Logger returned by e.g. level.NewFilter to a different level. You should keep the original log.Logger around and apply whichever filters you want to it independently. If you need to do this variously throughout the runtime of your program, consider a construct like e.g.

```go
type LevelLogger struct {
    base     log.Logger
    levelled log.Logger
}

func NewLevelLogger(next log.Logger, option level.Option) *LevelLogger {
    ll := &LevelLogger{base: next}
    ll.Set(option)
    return ll
}

func (ll *LevelLogger) Set(option level.Option) {
    ll.levelled = level.NewFilter(ll.base, option)
}

func (ll *LevelLogger) Log(keyvals ...interface{}) error {
    return ll.levelled.Log(keyvals...)
}
```

n.b. synchronization may be required.

**Comment by ChrisHines** [comment]
The base Go kit log package provides a [SwapLogger](https://godoc.org/github.com/go-kit/kit/log#SwapLogger) that may be useful when you want to change log levels while an application is running. See also #918.

**Comment by directionless** [comment]
For what it's worth, we do something like this in https://github.com/kolide/kit/tree/master/logutil to re-level
