### ISSUE TITLE
Better logger inputs

### ISSUE THREAD

**Issue by nasermirzaei89** [go-kit/kit#933]
This is a suggestion for the logger interface to be more clear and readable, also prevent developer mistakes.

Logger interface is now as below [godoc](https://godoc.org/github.com/go-kit/kit/log#Logger):

```go
type Logger interface {
    Log(keyvals ...interface{}) error
}
```

so, we put our key values in order. It's not as clear as something like `fmt.Printf` method.

Isn't it better to use options to make logging more restrict and readable? something like it:
```go
type Option func(Logger) error

type Logger interface {
    Log(message string, options ...Option) error
}

func StringValue(key, value string) Option {
    return func(l Logger) error {
        return l.SetValue(key, value)
    }
}
```

It's like implementation for `Logger.Info` method [godoc](https://godoc.org/go.uber.org/zap#Logger.Info_) in [uber.zap](https://github.com/uber-go/zap)

**Comment by peterbourgon** [comment]
Sorry, no.

**Comment by ChrisHines** [comment]
Another good reference is #21 where most of the current design was hashed out.
