### ISSUE TITLE
ambiguous import: found github.com/go-kit/kit/log/term in multiple modules: 

### ISSUE THREAD

**Issue by renyanduo** [go-kit/kit#934]
when I run 'go install' under the path: github.com/go-kit/kit/log/term
An err shows as follows:
![image](https://user-images.githubusercontent.com/15854055/68369048-57420500-0174-11ea-8d33-c14748e62c65.png)

**Comment by renyanduo** [comment]
An ambiguous import err comes.

**Comment by peterbourgon** [comment]
Why are you running "go install" there? There should be no need to do so.

**Comment by renyanduo** [comment]
> Why are you running "go install" there? There should be no need to do so.

To  statically compile a project which refers the project.
running "go mod" will also comes this.

**Comment by peterbourgon** [comment]
It is not necessary to run any go tool command against dependencies directly to statically compile dependent code.

**Comment by renyanduo** [comment]
ok

**Comment by renyanduo** [comment]
delete go.mod & run go mod init under github.com/go-kit/kit/ will fix this problem.
