### ISSUE TITLE
Remove sensitive token form .travis.yml file

### ISSUE THREAD

**Issue by moorara** [go-kit/kit#950]
There is  a token in `.travis.yml` file that causes some automated monitoring systems to raise an alarm when dependencies are managed via `vendor` folder. I suggest one of the following fixes:

  - Setting the token as environment variable in Travis-CI
  - Using GitHub Actions for sending test reports and set the token a secret.

I can help with the second approach if approved.

**Comment by peterbourgon** [comment]
I would rather convert the Travis CI to GitHub Actions, to be honest.
