### ISSUE TITLE
HTTP transport multiple WriteHeader

### ISSUE THREAD

**Issue by xyluet** [go-kit/kit#954]
Please take look the test below
```go
func TestErrorEncoderMultipleWriteHeader(t *testing.T) {
	handler := httptransport.NewServer(
		endpoint.Nop,
		httptransport.NopRequestDecoder,
		func(_ context.Context, w http.ResponseWriter, _ interface{}) error {
			w.WriteHeader(http.StatusOK)
			return errors.New("dang")
		},
	)
	w, r := httptest.NewRecorder(), httptest.NewRequest("", "/", nil)
	handler.ServeHTTP(w, r)
	if expect, got := http.StatusInternalServerError, w.Code; expect != got {
		t.Errorf("StatusCode expect: %d, got: %d", expect, got)
	}
}
```

Test will failed because when you already write the header and the encoding process error, while error encoder will set the header too, it still use the first header.

**Comment by peterbourgon** [comment]
Sorry, I don't really like this hack, and I don't think your test is valid.

If your ResponseEncoder writes status OK but then returns an error, it's correct for the client to receive status OK, even if the error encoder tries to write a different code. You should make sure not to call WriteHeader until you're confident that you'll successfully write a response to the client.

Am I overlooking something?

**Comment by xyluet** [comment]
Thank you for your considerations. So it's expected to behave like that?

How to ensure we successfully write a response, because WriteHeader has no effect after Write?

**Comment by peterbourgon** [comment]
Don't call WriteHeader until you've done all of your validations and tests.

```
// No
func encodeResponse
    write header 200
    try thing 1
    if error, return err
    try thing 2
    if error, return err
    write response

// Yes
func encodeResponse
    try thing 1
    if error, return err
    try thing 2
    if error, return err
    write header 200
    write response
```
