### ISSUE TITLE
+Inf silently prevents log from logging

### ISSUE THREAD

**Issue by mmat11** [go-kit/kit#968]
In this [minimal working example](https://play.golang.org/p/xRl0_8gr3my), the last log line is not getting logged, I suppose it's a bug

**Comment by peterbourgon** [comment]
[Check the error from the second logger.Log statement](https://play.golang.org/p/4U6lZ4yzdzb).

**Comment by mmat11** [comment]
Thanks! Should have checked myself. If that's the expected behavior feel free to close the issue

**Comment by peterbourgon** [comment]
For the record, while +Inf is no bueno with the JSONLogger, it works fine with the LogfmtLogger.
