### ISSUE TITLE
GRPC Reflection, HowTo?

### ISSUE THREAD

**Issue by wolf4git** [go-kit/kit#979]
I'm just starting with go-kit. 
Can't catch how to activate grpc.Reflection().
Here is a snipped from my code on direct GRPC-Server...
... grpcServer := grpc.NewServer(opts...)
... // Register reflection service on gRPC server.
... reflection.Register(grpcServer)

Hopefully you can guide me, how to enable grpc-Reflection within go-kit...THX

**Comment by alienatorZ** [comment]
Any update on this? I am trying the same thing.

**Comment by wolf4git** [comment]
Im sorry Adam, no News.
I‘m no longer working on this, as another developer is taken care of go-kit Integration.
He‘s not working on this topic,..so also no new from his side.

Sorry, but we don’t take care of this any longer.


Von meinem iPad gesendet

**Comment by wolf4git** [comment]
Hi Adam,
Some details how I got to the topic...
I got in contact to reflection by an Udemy-course of Stephane Maarek.
Chapter 50: gRPC reflection & Evan Cli 




Von meinem iPad gesendet

**Comment by alienatorZ** [comment]
Thank you.
I also found https://github.com/jhump/protoreflect which I am going to integrate in.
