### ISSUE TITLE
incompatible version 0.8.0 & 0.9.0

### ISSUE THREAD

**Issue by xq840622** [go-kit/kit#981]
There are two different version of func SendLoop in 0.8.0 and 0.9.0, as blow:
func (s *Statsd) SendLoop(c <-chan time.Time, network, address string)
func (s *Statsd) SendLoop(ctx context.Context, c <-chan time.Time, network, address string)

As I see, this function make these two version incompatible.
When I import two project which contains two incompatible version of kit, golang alway use the newest version included in go.mod. As a result, there will be an error. 

Is there a good way to solve this problem?

**Comment by peterbourgon** [comment]
Upgrade the dependency which relies on 0.8.0 to work with 0.9.0 — or, better yet, 0.10.0.
