### ISSUE TITLE
Asym Transport?

### ISSUE THREAD

**Issue by towens** [go-kit/kit#984]
Thinking about data pipelines. NATS in, HTTP out for example. Interesting? Not a goal?

**Comment by peterbourgon** [comment]
Whatever sends the "NATS in" will necessarily want a response to its event. If you send "HTTP out" without an incoming HTTP request it is an outgoing HTTP request, so that doesn't really make sense either. What are you trying to accomplish?

**Comment by towens** [comment]
It's a service that consumes a Kafka topic (yes, I said NATS) does some enrichment on the event and makes a POST over HTTP. If the POST succeeds, we commit the offset on the Kafka topic. If it fails, we don't commit the offset and log both the Kafka event and the enriched event.

It's just not in go-kit.

**Comment by peterbourgon** [comment]
If the service responds to "requests" received via Kafka then the "transport" layer is Kafka. The fact that the work it does is an HTTP POST is kind of irrelevant to the Go kit model. That could be a DB INSERT, or anything else.

Remember: Go kit implements the RPC (request/response) messaging pattern. If your service isn't RPC, then Go kit isn't a fit.

**Comment by towens** [comment]
Yep, definitely trying to make this more complicated than it needs to be. The clarification between the transport layer and "the work" is helpful.
