### ISSUE TITLE
Setting Secure HTTP Headers on All Responses

### ISSUE THREAD

**Issue by ChrisSargent** [go-kit/kit#985]
Hello,

It's important for some headers to be included on all responses on our HTTP server, even if (especially if!) the server has an error. I know we can set headers in the encoder functions but, for example, if there is an error in the decoder function, encoder functions don't get called. I tried to set something in the `ServerAfter` functions too, but they also don't get called in the case of an error in the decoder functions.

And, as far as I can tell, adjusting headers in the finalizer function is not possible.

So, how / where is it possible to add a default set of headers to ALL http responses?

Thanks!

Chris

Edit: I guess actually this should be achieved in the same ways the example for adding CORS headers - e.g. wrapping the handler and using `http.HandlerFunc`.

**Comment by peterbourgon** [comment]
> I guess actually this should be achieved in the same ways the example for adding CORS headers - e.g. wrapping the handler and using http.HandlerFunc.

+1. Does that solve the issue for you?

**Comment by ChrisSargent** [comment]
Yes, I've just tested it and it's working as expected, thanks.
