### ISSUE TITLE
New requests are created without GetBody methods

### ISSUE THREAD

**Issue by amariampolskiy** [go-kit/kit#995]
Inside go-kit/kit/transport/http/client.go func (c Client) Endpoint() endpoint.Endpoint, there is this logic

```		
                req, err := http.NewRequest(c.method, c.tgt.String(), nil)
		if err != nil {
			cancel()
			return nil, err
		}
```

The initial body is empty, which leads to the effect of new requests having an empty GetBody methods, which leads to inability to follow redirects correctly.

This is the code from http/client.go, redirectBehavior function

```
	case 307, 308:
		redirectMethod = reqMethod
		shouldRedirect = true
		includeBody = true
		if resp.Header.Get("Location") == "" {
			shouldRedirect = false
			break
		}
		if ireq.GetBody == nil && ireq.outgoingLength() != 0 {
			shouldRedirect = false
		}
	}
```

It is possible to make a workaround by creating new request with body and replacing created request with it on encoding step, but i think stuff like that should work out of the box.

**Comment by peterbourgon** [comment]
This is why we have the NewExplicitClient constructor, you can provide your own CreateRequestFunc that doesn't have this behavior. Does that not work for you?

**Comment by amariampolskiy** [comment]
Well, i guess i have an older version of the library. Sorry for bothering you.

**Comment by peterbourgon** [comment]
No worries!
