### ISSUE TITLE
SD:Consul - Index handling is incorrect per consul docs

### ISSUE THREAD

**Issue by schmidtw** [go-kit/kit#997]
The [loop](https://github.com/go-kit/kit/blob/master/sd/consul/instancer.go#L70) where index handling is incorrect.

Consul Docs
https://www.consul.io/api-docs/features/blocking#implementation-details

### Index goes backwards

In rare cases, the index can be returned that is before the last index.  In this case, the system can basically miss out on events for either a very long time or forever.  This can be pretty damaging if you depend on the consistency of the SD value & the value does not appropriately update.

### Index returned is zero

In rare cases the returned index can be zero.  In this case the code should backoff and try again to avoid a tight loop.

**Comment by schmidtw** [comment]
I have a proposed fix for these two errors in my local repo.
https://github.com/schmidtw/kit/commit/e539a98781cb06b55e5f787254627b720f21e8ff

**Comment by peterbourgon** [comment]
Happy to take a PR.

**Comment by sagikazarmark** [comment]
Fixed in #999
