### ISSUE TITLE
Go-kit supports nacos as a registry and configuration center

### ISSUE THREAD

**Issue by sanxun0325** [go-kit/kit#998]
Go-kit plans to integrate nacos?
For Go-kit users, nacos can be chosen as the registry and configuration center.

**Comment by sanxun0325** [comment]
I can do the work

**Comment by lzp0412** [comment]
https://nacos.io/en-us/
We can get some information about Nacos from this website.

**Comment by peterbourgon** [comment]
Sorry, no.
